### ISSUE TITLE
MJML is very slow and unable to work in Monterey and ventura.

### ISSUE THREAD

**Issue by vysakhjayadas** [mjmlio/mjml#2593] opened 2022-12-06 11:07 UTC
App is very slow in 13.x and 12.x macOS and unable to work. Working fine in Catalina. Please fix this issue. Its impacting the project.

**Comment by iRyusa** [comment] 2022-12-06 11:19
I guess you're referring to #2584 so I close this one but i'm on Monterey and I have 0 issue with MJML App.

And as you provide very little information we can't really help.

**Closed by iRyusa** 2022-12-06 11:19 UTC

**Comment by vysakhjayadas** [comment] 2022-12-06 11:25
@iRyusa  Yes. My colleagues are also facing the similar issue after OS upgrade.

**Comment by vysakhjayadas** [comment] 2022-12-06 11:26
Tried with 3.03 and 3.0.5 beta

**Comment by vysakhjayadas** [comment] 2022-12-06 11:27
Is there resolution for our issue?

**Comment by vysakhjayadas** [comment] 2022-12-06 11:42
can you share the link for downloading 3.1.0 version

**Comment by iRyusa** [comment] 2022-12-06 12:05
Releases · mjmlio/mjml-appgithub.comOn 6 Dec 2022, at 12:42, vysakhjayadas ***@***.***> wrote:﻿
can you share the link for downloading 3.1.0 version

**Comment by vysakhjayadas** [comment] 2022-12-06 12:12
@iRyusa same slowness for 3.10 beta also

**Comment by iRyusa** [comment] 2022-12-06 13:15
Tried a clean install on a new Mac and still no issue... We don't really know what's going on for you, check if the MJML process take 100% usage, remove every project/config file that you can find on MJML App side and try a clean install.

If we don't have any way to reproduce we can't provide any help.

**Comment by iRyusa** [comment] 2022-12-06 15:52
Please check on #2584 if you can provide anything that can help us to identify the root cause
