### ISSUE TITLE
@ declaration within an @declaration will break css in head (Gmail mobile app)

### ISSUE THREAD

**Issue by pvlachou** [mjmlio/mjml#840] opened 2017-10-16 01:47 UTC
Hi,

Just a note that in the Gmail mobile app, the standard @viewport declarations that MJML puts into each email head will cause other css to be stripped from the email. This is due to Gmail not liking @ declarations within @ declarations.

I'm referring to

`    <style type="text/css">
        @media only screen and (max-width:480px) {
            @-ms-viewport {
                width: 320px;
            }
            @viewport {
                width: 320px;
            }
        }
    </style>`

It took me forever to find out why the hell my email was losing part of its formatting in the Gmail app on iOS. It didn't matter if I was sending the email through mailchimp, mailjet or putsmail... so that's why I'm sure it's a problem with gmail. As soon as I deleted the bit of code I referenced above, everything worked perfectly.

**Comment by iRyusa** [comment] 2017-10-16 09:48
Hi @pvlachou 

Do you have an example with screenshot because i'm unable to reproduce ? https://mjml.io/try-it-live/SJB9Jbf6Z Here Gmail iOS/Android does apply the green color on span.

**Comment by iRyusa** [comment] 2017-10-23 13:12
Might be related to #844 are you using MailChimp to send your email ? 

I'm closing it for now, feel free to reopen if needed

**Closed by iRyusa** 2017-10-23 13:12 UTC

**Comment by pvlachou** [comment] 2017-10-31 01:48
Hi @iRyusa 

Sorry, I didn't respond to your posts. I thought I solved the issue by doing something else, but I was wrong. Regardless, now I know 100%, it definitely is an issue with mailchimp and the following conditional statement in the head

```
    <!--[if !mso]><!-->
    <style type="text/css">
        @media only screen and (max-width:480px) {
            @-ms-viewport { width: 320px; }
            @viewport { width: 320px; }
        }
    </style>
    <!--<![endif]-->
```

Once I removed that piece of code, Gmail + Gmail App both showed my emails as they're supposed to look. If you scroll down to point 5. in this article https://www.emailonacid.com/blog/article/email-development/12_things_you_must_know_when_developing_for_gmail_and_gmail_mobile_apps this is what I was referencing in my initial post with the @'s.

A couple of screenshots from Gmail desktop to show how it was affecting my email layout..

With Condition Statement: https://www.dropbox.com/s/5zygml0pmw5ihov/Screen%20Shot%202017-10-30%20at%209.26.28%20PM.png?dl=0

Without: https://www.dropbox.com/s/qotz7cvqxs6vdy4/Screen%20Shot%202017-10-30%20at%209.28.17%20PM.png?dl=0

**Comment by iRyusa** [comment] 2017-10-31 10:30
Yeah as mentioned in #844 mailchimp does alter the HTML with their "minifier" and merge every media queries inside one, causing to break the whole style block for gmail.
