### ISSUE TITLE
Empty HTML comments.

### ISSUE THREAD

**Issue by antonstsk** [mjmlio/mjml#1884] opened 2020-04-23 10:12 UTC
Don't really sure it's a bug but seems pretty bad idea to have empty comments and incorrectly defined directives:
```html
<!--[if !mso]><!-- -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--<![endif]-->
```

Just preprocess the .mjml file usding npm library.
`mjml test.mjml -o test.html`

What I expect to have is (according [Microsoft official guideline](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537512(v=vs.85)?redirectedfrom=MSDN)):
```html
<!--[if !mso]>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<![endif]-->
```

Environment:
 - MJML 4.6.2 (CLI tool)
 - MacOS Catalina

Not even sure that's affecting on rendering but when I've switched from VSCode tool to CLI and changed that "bug" email was rendered better on any platform.

**Comment by iRyusa** [comment] 2020-04-23 11:55
We're just applying this fix described here : https://www.emailonacid.com/blog/article/email-development/prevent-ie-edge-meta-tag-from-breaking-images-in-live-mail/

If you have any issues, please post more details.

**Comment by iRyusa** [comment] 2020-04-23 12:21
Closing because of duplicate of #1581

**Closed by iRyusa** 2020-04-23 12:21 UTC
