### ISSUE TITLE
Keep HTML safe chars after parsing

### ISSUE THREAD

**Issue by lessless** [mjmlio/mjml#738] opened 2017-07-11 09:14 UTC
Hello,

as of now `lt;script&gt;console.log('asd');&lt;/script&gt;` will be converted  to `<script>console.log('asd');</script>`, but instead we would like to keep `&lt;` and `&gt;` to avoid JS injections.

Example: https://mjml.io/try-it-live/ByvdzMfBb

**Comment by dalefish** [comment] 2017-07-11 09:47
This change would break behavior many people rely on.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment] 2017-07-11 10:52
Hi @lessless 

Well this is a concern, but any ending tag accept any html entities, so you can write any script tag in a mj-text too and we don't do anything about it.

In MJML4 they won't be encoded anymore, so they stay as `&lt;` etc. (But you can open any tag without closing them in `mj-raw` to keep the behaviour you're using @dalefish  )

**Comment by dalefish** [comment] 2017-07-11 11:07
Yay, thanks. Going to be refactoring our existing stuff for 4 anyway.

**Comment by iRyusa** [comment] 2017-07-20 11:07
I'm closing this one because it's a duplicate of #343

**Closed by iRyusa** 2017-07-20 11:07 UTC
