### ISSUE TITLE
<mj-text> component does not remove <mj-raw>

### ISSUE THREAD

**Issue by rhyswfbowles** [mjmlio/mjml#1626] opened 2019-06-21 10:28 UTC
**Describe the bug**
```<mj-text>``` component does not remove ```<mj-raw>``` tags from it's parsing

**To Reproduce**

- Using the MJML 'try it out live' tool on the mjml website.

- Create a template using this code ( or visit https://mjml.io/try-it-live/BJ7ByVcJS )

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>Hello <mj-raw>{{ world }}</mj-raw></mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

- Inspect the {{ world }} element and see that <mj-raw> still persists 

**Expected behavior**
While I understand the functionality of ```<mj-text>``` is to deliver items that are put into in their raw format, I do not believe ```<mj-raw>``` should be outputted in any scenario.
This, in my opinion should be an inert component which is **always** stripped and preserves it's content

**MJML environment:**
 - Currently windows but no belief it will behave different on others
 - MJML Version 4.3.0
 - All

**Comment by rhyswfbowles** [comment] 2019-06-21 11:53
While I appreciate the reply in #1482 it doesn't really come across as an answer asks **Why though?.**
Sure it leaves it in there and that is currently the functionality of `<mj-text>` but this functionality doesn't feel to be correct.

Leaving `<mj-raw>` inside of the `<mj-text>` element seems to provide no benefit and just feels like a forgotten artifact that should just be removed as in all other cases

Providing my specific use-case may provide light on why: 
Using the `gulp-mjml` project, I am 'auto-escaping' all my templating language elements with `<mj-raw>`
This means anything that looks like:
`{{` = `<mj-raw> {{`
`}}` = `}} </mj-raw>`
`{%` = `<mj-raw> {%`
`%}` = `%} </mj-raw>`

While this is obviously specfic to me and my use-case I believe the point still stands.

**Comment by iRyusa** [comment] 2019-06-21 12:25
Because `mj-text` node & other content node doesn't need to be parsed. The more we "clean" or parse the content the less flexible content tag becomes. Weird bugs appeared in the past where content had encoding issue, or output issue, those were fixed by just stopping to parse anything in content tag.

**Closed by iRyusa** 2019-06-21 12:25 UTC

**Comment by ankittaneja** [comment] 2019-11-15 11:19
I am facing a similar situation and it looks like this is a feature not a bug :P . @rhyswfbowles : Can you please share your gulp file? Will save me some to write the whole thing myself.

To mjml team, perhaps add this to the documentation, that when mj-raw is inside text it will not be parsed.
