### ISSUE TITLE
Group px width gets converted to percentages

### ISSUE THREAD

**Issue by adambullmer** [mjmlio/mjml#641] opened 2017-04-14 00:31 UTC
Noticed when I use a `mj-group` component and specify a pixel width, the output class is a calculated percentage instead of the provided pixel width.

**Comment by iRyusa** [comment] 2017-05-11 14:06
Hi @adambullmer 

I remember why we've done this. Mobile width could be anywhere from 300 to 480px, so set column in `px` could behave not as intended depending on the device. That's why we're using percentage width in column only to make it fluid

Does it make sense to you ?

**Comment by adambullmer** [comment] 2017-05-11 20:37
Yes and no. I saw where the group would be more responsive as a percentage. Maybe there's a better option than overriding the default. I unfortunately need a fixed width grouping container, and would love to write it all in mjml rather than opening a raw tag and doing it with tables manually. Maybe there could be an override like a `fixed-width` option for users who are aware of the implications.

**Comment by iRyusa** [comment] 2017-05-19 13:55
> On a side note, to me it feels like specifying pixels is not intended to be a responsive pattern in the first place, and feels like buggy or unexpected behavior. Might want to mention that caveat in the docs.
It's mostly the discussion we had  when implementing `mj-group`. To be fair you can still use new `css-class` attribute and inline the width with `mj-style`.  So it doesn't introduce some unclear behaviour to `mj-group` and anyone can still use a pixel width for group.

Does it seems an ok approach for you ?

**Comment by adambullmer** [comment] 2017-05-24 16:13
Yeah, that seems fair. What version will that `css-class` attribute be available? I see it on the website, but the latest non-master mjml renderer engine says it's not a valid property. (also tried pairing the `mj-class` property with the attribute and didn't have any luck with that either)

But, if I understood correctly I should get the desired result like this?

```html
<mjml>
<mj-head>
  <mj-attributes>
    <mj-class name="fixed-width" width="400px" />
  </mj-attributes>
</mj-head>
<mj-body>
  <mj-container>
    <mj-section>
      <mj-group width="400px" css-class="fixed-width">
        <mj-column>
          <mj-text>Column 1</mj-text>
        </mj-column>
        <mj-column>
          <mj-text>Column 2</mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
  </mj-container>
</mj-body>
</mjml>
```

**Comment by iRyusa** [comment] 2017-05-24 16:15
MJML.io doc is updated to 3.3.3 but it's not released yet. You can try this solution on beta 3.3.3-beta3

Not mj-class doesn't work like that : it only apply attributes on defined mj-element.

**Comment by adambullmer** [comment] 2017-05-24 16:27
so then a `mj-style` with a free form class, and then the `css-class` attribute on the element?

**Comment by iRyusa** [comment] 2017-06-21 14:25
I'm closing this issue, feel free to use `css-class` to bypass the behaviour but we won't let `px` width in `mj-group`.

**Closed by iRyusa** 2017-06-21 14:25 UTC
Labels: Discussion

**Comment by FoxWhite** [comment] 2017-06-30 16:45
@iRyusa could you guys please update documentation here then?
https://mjml.io/documentation/#mjml-group

**Comment by iRyusa** [comment] 2017-06-30 19:55
> Column inside a group must have a width in percentage, not in pixel

This is noticed in the doc already

**Comment by dalefish** [comment] 2017-06-30 21:02
I think it does say px in the table below that

**Comment by iRyusa** [comment] 2017-06-30 21:09
Well px are supported but converted as percent to ensure mobile view isn't broken might add a notice then nice catch @dalefish @FoxWhite
