### ISSUE TITLE
Line height on buttons

### ISSUE THREAD

**Issue by dalefish** [mjmlio/mjml#350] opened 2016-08-03 08:55 UTC
In 2.3.1, maybe before too, line height is not translated from MJML to the generated HTML for buttons.

It's preventing button text from showing on Outlook 2003 and older.

After a little digging, it looks like amending line 97 of the button JS does the trick.

Original
`lineHeight: mjAttribute('height'),`

Amended
`lineHeight: mjAttribute('line-height'),`

**Comment by ngarnier** [comment] 2016-08-03 15:22
Hey @dalefish, thanks for reporting this issue. It's actually a duplicate of #319 so if you don't mind I'll close this one to keep the discussion there.

**Closed by ngarnier** 2016-08-03 15:22 UTC
Labels: Feature request
