### ISSUE TITLE
[4.6.0] Uncaught Error: Specified filePath does not exist

### ISSUE THREAD

**Issue by DRoet** [mjmlio/mjml#1854] opened 2020-03-03 12:58 UTC
**Describe the bug**
Error is thrown when using mjml 4.6.0

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2. Render it to HTML by doing 'mjml2html(mjml)'
3. See error

**Expected behavior**
No errors are thrown

**MJML environment (please complete the following information):**
 - OS: WIN10
 - MJML Version 4.6.0

**Additional context**
It seems like filePath always defaults to '.' instead of null/undefined. overriding the filePath option fixes the error:

```js
mjml2html(mjml, {
    filePath: null
})
```

**Comment by DRoet** [comment] 2020-03-03 13:03
ah, its probably due to me trying to run mjml in the browser by mocking out fs/uglify.js (which works with 4.5.x) 

relevant code: https://github.com/mjmlio/mjml/blob/master/packages/mjml-parser-xml/src/index.js#L50

**Comment by kmcb777** [comment] 2020-03-03 13:21
@DRoet maybe, i can't reproduce the issue with a simple node script
We indeed made a few changes on this file, now filePath is checked using `fs` to know if it's a file or directory

**Comment by fireworks2005** [comment] 2020-03-04 05:18
@kmcb777 ,  i do experience the same file not found error after upgrading to 4.6.0.  Seems that the way mjml interpret filepath is different from the previous version.

**Comment by iRyusa** [comment] 2020-03-04 10:55
Can you provide more info about that please @fireworks2005 ?

**Comment by kmcb777** [comment] 2020-03-04 11:58
@fireworks2005 This error was happening when none of the `--config` options were used in the cli.
This should be already fixed in the latest release 👍 
I still couldn't reproduce when importing mjml in code and using mjml2html()
Did you have the error when using it like this, or with the cli ?

**Comment by fireworks2005** [comment] 2020-03-16 05:07
@kmcb777 , i am good now. i dont see any error with the latest version

**Comment by kmcb777** [comment] 2020-03-17 17:42
It seems ok for everyone now so i think we can close this one 👍

**Closed by kmcb777** 2020-03-17 17:42 UTC

**Comment by zh1314** [comment] 2022-12-28 14:02
i have the same error, and resoved by override filePath, I'm not sure if there are other effects

`mjml2html(mjml, {
    filePath: null
})`
