### ISSUE TITLE
Background image breaks on high resolution screen

### ISSUE THREAD

**Issue by SvenVdv** [mjmlio/mjml#518] opened 2017-01-26 13:40 UTC
The next code seems to break on a 4K screen in Outlook 365. It renders a square field of 200px x 200px (I'm guessing). It is completely fine on a regular screen.
```xml
<mj-section background-color="#ffffff" background-url="http://i.imgur.com/6GScU0Q.jpg" padding-bottom="27" padding-top="0">
          <mj-column width="100%" vertical-align="middle">
            <mj-text align="center" color="#000000" font-family="Georgia, 'Times New Roman', serif" font-size="13" padding-left="25" padding-right="25" padding-bottom="0" padding-top="0">
              <p><span style="font-weight: bold;"><span style="color: rgb(255, 255, 255);"><span style="font-size: 16px;"><br></span></span></span></p>
              <p><span style="font-weight: bold;"><span style="color: rgb(255, 255, 255);"><span style="font-size: 16px;"><br></span></span></span></p>
              <p><span style="font-size: 27px;"><a href="https://mjml.io" style="text-decoration: none; color: inherit;"><span style="font-weight: bold;"><span style="color: rgb(255, 255, 255);">Even checken ...</span></span></span></p>
              <p><span style="font-weight: bold;"><span style="color: rgb(255, 255, 255);"><span style="font-size: 16px;"><br></span></span></span></p>
              <p><span style="font-weight: bold;"><span style="color: rgb(255, 255, 255);"><span style="font-size: 16px;"><br></span></span></span></p>
            </mj-text>
          </mj-column>
        </mj-section>
```

[EDIT] Screenshot: 
![screenshot_bug](https://cloud.githubusercontent.com/assets/6322493/22336475/b8e53ef6-e3e2-11e6-8b1f-7732105fcec4.jpg)

Any idea what might be the problem and how to fix it?

**Comment by iRyusa** [comment] 2017-01-26 14:00
Hey @SvenVdv !

Can you provide a screenshot about the issue please ?

Thanks !

**Comment by SvenVdv** [comment] 2017-01-26 14:23
![screenshot_bug](https://cloud.githubusercontent.com/assets/6322493/22334491/4c08ba44-e3db-11e6-9139-4153eb3a0d9f.jpg)

Here you go :)

**Comment by iRyusa** [comment] 2017-03-28 15:22
Hey @SvenVdv is this still the case in MJML 3.3 ?

**Comment by SvenVdv** [comment] 2017-03-29 08:44
Yes, it still is 😄

**Comment by iRyusa** [comment] 2018-02-07 17:28
We slightly changed the VML in MJML4 (beta2 is available)

Would be nice if you're able to test it out to see if the new VML handle this better

**Comment by kmcb777** [comment] 2018-05-29 16:11
I couldn't reproduce the issue on a 4k screen on outlook.com (which is supposed to have the same render engine as outlook 365) so it was probably fixed in mjml4. It could be specific to outlook365, so if you can test this again it would be great @SvenVdv (if you're still around, this issue is a bit old) :)

**Comment by SvenVdv** [comment] 2018-06-25 12:45
I got upgraded to an iMac 😄 So no 4K Outlook 365 anymore. Maybe anyone else can check this?

**Comment by kmcb777** [comment] 2018-09-13 13:37
Since we can't reproduce, and there has been many changes since mjml3, i'll close this one, feel free to reopen if you can reproduce

**Closed by kmcb777** 2018-09-13 13:37 UTC
Labels: Outlook issue
