### ISSUE TITLE
Outlook 2000 - 2003 Image Alignment

### ISSUE THREAD

**Issue by NickScola** [mjmlio/mjml#758] opened 2017-07-26 18:10 UTC
Has anyone noticed images are not being centered align, or they are being pushed to the right? 

http://imgur.com/a/aFRxZ

**Comment by forethoughtde** [comment] 2017-07-30 20:00
Can you post your code here so that we can see what is wrong?

**Comment by NickScola** [comment] 2017-07-31 15:13
`<mj-section background-color="#ffffff" padding-bottom="0px">

  <mj-column>
    
    <mj-text padding="10px" font-size="12px" color="#ababab" font-family="Helvetica">
    	<a href="$prefilledform(campaignname())$" style="color: #ababab; margin: 0 5px; font-weight: 300; text-decoration: none;">View in Browser</a>
    </mj-text>
    
    <mj-image padding="15px 0 0" width="150" src="https://static.cdn.responsys.net/i5/responsysimages/trnkclb/contentlibrary/brands/images/TCNordstromLogo.png" alt="Trunk Club Nordstrom Logo"></mj-image>
    
    <mj-spacer></mj-spacer>
    
  </mj-column>

</mj-section>`

**Comment by NickScola** [comment] 2017-07-31 15:15
`<mj-section background-color="#ffffff" padding-bottom="0px"><mj-column><mj-image padding="15px 0 0" width="150" src="https://static.cdn.responsys.net/i5/responsysimages/trnkclb/contentlibrary/brands/images/TCNordstromLogo.png" alt="Trunk Club Nordstrom Logo"></mj-image></mj-column></mj-section>`

**Comment by Kant1-0** [comment] 2017-08-04 12:31
Actually the image is not center aligned with Outlook 2000 - 2003. Investigating the output HTML there is a `style="width:100%"` that seems to break the alignment. Just deleting it fixed the problem.

```
<td style="width:150px;"><img alt="Trunk Club Nordstrom Logo" title="" height="auto" 
src="https://static.cdn.responsys.net/i5/responsysimages/trnkclb/contentlibrary/brands/images/TCNordstromLogo.png"
style="border:none;border-radius:0px;display:block;font-size:13px;outline:none;text-decoration:none;width:100%;height:auto;"
width="150"></td>
```

**Comment by Kant1-0** [comment] 2017-08-04 12:40
Although I can't reproduce the right alignment problem.

**Comment by dalefish** [comment] 2017-08-04 12:54
Early outlooks don't like images that are too big for the space.

Try creating a smaller version of the logo and see if it helps.

Hard to know if that is the problem without seeing an example but it's a
start.

**Comment by iRyusa** [comment] 2017-08-07 11:51
Hi @NickScola

Can you provide the full template so we can investigate ?

**Comment by hkolsen** [comment] 2017-08-08 17:54
Having the same issue over here, images are not aligning center in Outlook 2000/2002/2003. Here is the MJML code:

`<mjml>
  <mj-body>
    <mj-container>
      <mj-section padding="0">
        <mj-column>
          <mj-image href="https://tacobell.com" align="center" alt="TACO BELL" title="Taco Bell Home" width="320" src="https://eroi-s3.s3.amazonaws.com/emailassets/clients/tacobell/2017/transact/global/tacobell_header-logo.jpg" />
         </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>`

Here is the [https://litmus.com/builder/documents/1730302](Litmus Builder) so you can see the compiled version and the result. Any ideas? Just removing the `style="width:100%"` didn't seem to do the trick.

**Comment by iRyusa** [comment] 2017-08-08 18:57
(Just post the slack reply here for other people checking the issue)

You can either replace width per max-width, but we don't really know if there's some downside on this solution : https://mjml.io/try-it-live/S18tEFvDZ

Or just keep the img at the natural size equal to his container (here 320 instead of 640) it's an old bug with outlook allocating more space than it should to display the img  you can read more here https://mjml.io/try-it-live/S18tEFvDZ

Same thing for you @NickScola 

I can close this issue now :) feel free to reopen if needed

**Closed by iRyusa** 2017-08-08 18:57 UTC
Labels: Bug, Outlook issue

**Comment by rogierslag** [comment] 2017-08-09 10:19
> Or just keep the img at the natural size equal to his container (here 320 instead of 640) it's an old bug with outlook allocating more space than it should to display the img you can read more here https://mjml.io/try-it-live/S18tEFvDZ

For documentation purposes it might be useful to include the correct link somewhere (the above one is off)

**Comment by iRyusa** [comment] 2017-08-09 11:54
Oops https://github.com/mjmlio/mjml/issues/618#issuecomment-289467937

**Comment by ParallelUniv3rse** [comment] 2018-09-26 13:20
If anyone stumbles upon this an easy fix that worked for me was including 
`<mj-style inline="inline">
      img {
        max-width: 100%;
      }
 </mj-style>
`
