### ISSUE TITLE
Columns not working on Gmail & Inbox by Gmail

### ISSUE THREAD

**Issue by gera446** [mjmlio/mjml#266] opened 2016-05-17 20:16 UTC
Columns are not working on Inbox by Gmail and Gmail.
I try even sending the demos and event de demos looks broken
Here is my code
```
<mj-section background-color="#FFF">
		<mj-column padding-top="30px" >
			<mj-image alt="Waumbaland" href="http://openhouse.cr" padding-top="35px" width="148" src="http://illusionseeds.com/openhouse/mail/happy/waumbaland.jpg">    
			</mj-image>
			<mj-text padding-top="40px" color="#000" align="center" font-size="15px" line-height="18px">
				Bebés – Kínder <br>	
				11:00 a.m. &amp; 12:30 p.m.
			</mj-text>
		</mj-column>
		<mj-column>
			<mj-image alt="Upstreet" href="http://openhouse.cr" width="111" src="http://illusionseeds.com/openhouse/mail/happy/upstreet.jpg">    
			</mj-image>
			<mj-text padding-top="26px" color="#000" align="center" font-size="15px" line-height="18px">
				Preparatoria – 4° grado <br>	
				11:00 a.m. &amp; 12:30 p.m.
			</mj-text>
		</mj-column>
		<mj-column>
			<mj-image alt="Transit" href="http://transit.cr/" padding-top="25px" width="136" src="http://illusionseeds.com/openhouse/mail/happy/transit.jpg">
			</mj-image>
			<mj-text  padding-top="41px" color="#000" align="center" font-size="15px" line-height="18px">
				5° – 8°grado <br>
				12:30 p.m.
			</mj-text>
		</mj-column>
		<mj-column>
			<mj-image alt="Insideout" href="http://openhouse.cr" width="96" src="http://illusionseeds.com/openhouse/mail/happy/insideout.jpg">    
			</mj-image>
			<mj-text padding-top="20px" color="#000" align="center" font-size="15px" line-height="18px">
				9°-12° grado <br>	
				12:30 p.m.
			</mj-text>
		</mj-column>
	</mj-section>
```

**Comment by g0ddish** [comment] 2016-05-17 20:30
I think this is a known issue #40 affecting Gmail vs Gmail app vs Inbox.

**Comment by iRyusa** [comment] 2016-05-18 12:27
Hello it's a duplicate of #40 so i'm closing it,

Gmail is working, but Google Apps gmail wont.

**Closed by iRyusa** 2016-05-18 12:27 UTC
