### ISSUE TITLE
html rendering add "mj-column-per-16"

### ISSUE THREAD

**Issue by Sarah-IFG** [mjmlio/mjml#1212] opened 2018-05-22 15:08 UTC
Hello !
I have a problem with mj-column :
- html rendering add "mj-column-per-16" while I haven't set any width on my column.

1. This is my code : 
```
<mjml>
<mj-body background-color="#ffffff">
  <mj-section>

    <!-- column 1 -->
    <mj-column padding="5px 0" background-color="#84707d" border-radius="10px">
      <mj-image src="img.jpg"></mj-image>
      <mj-text>blabla</mj-text>
    </mj-column>

    <!-- column 2 -->
    <mj-column padding="5px 0" background-color="#ff6493" border-radius="10px">
      <mj-image src="img.jpg"></mj-image>
      <mj-text>blabla</mj-text>
    </mj-column>

    <!-- column 3 -->
    <mj-column padding="5px 0" background-color="#0182ff" border-radius="10px">
      <mj-image src="img.jpg"></mj-image>
      <mj-text>blabla</mj-text>
    </mj-column>
  </mj-section>
</mj-body>
</mjml>
```

2. Html rendering : 
```
<!-- column 1 -->
<!--[if mso | IE]>
<td
 style="vertical-align:top;width:100px;"
>
<![endif]-->
<div class="mj-column-per-16 outlook-group-fix" style="font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;">
  <table background="#84707d" border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
    <tbody>
      <tr>
        <td style="background-color:#84707d;border-radius:10px;vertical-align:top;padding:5px 0;">
          <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%">
            <tr>
              <td align="center" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="border-collapse:collapse;border-spacing:0px;">
                  <tbody>
                    <tr>
                      <td style="width:50px;"> <img height="auto" src="img.jpg" style="border:0;display:block;outline:none;text-decoration:none;height:auto;width:100%;" width="50" /> </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <td align="left" style="font-size:0px;padding:10px 25px;word-break:break-word;">
                <div style="font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1;text-align:left;color:#000000;"> blabla </div>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<!--[if mso | IE]>
</td>
<![endif]-->
```

**Expected behavior:**
Columns should take all the width. I don't understand why is added "mj-column-per-16"
(I saw padding are available for mj-column on the documentation, but it doesn't work. Is it normal too ?)

**MJML version:**
4.0.5

Thank you for your help.

**Comment by iRyusa** [comment] 2018-05-22 15:10
Hi @Sarah-IFG 

This is a duplicate of #1152 and will be fix in 4.1 release a beta should be release soon, in the meantime just set the width manually on mj-column 

Thanks

**Closed by iRyusa** 2018-05-22 15:10 UTC
