### ISSUE TITLE
Issues with rendering in outlook 

### ISSUE THREAD

**Issue by Hodakhosravi** [mjmlio/mjml#2334] opened 2021-07-24 19:37 UTC
Hi again :) 
I developed UI blocks in mjml 4. and test them in email on acid. I have lots of issues with outlook. I searched and I get that it is better to have <table> instead of <div>  so I changed all div to table to render better in outlook. but I still have an issue with outlook. I attached one of the results from the test email in acid. 
1-is it true that the use of <div> tags in an email is fairly supported by mobile email applications and used in responsive emails, they can still lead to display errors in email clients such as Outlook and should be replaced with the <table> tag where possible.
2- what can I do for solving these issues? can I modify and add media query for outlook again?
![Untitled](https://user-images.githubusercontent.com/74387098/126879370-96e64f92-f514-498d-8dd7-674cbab8735b.png)

**Comment by Hodakhosravi** [comment] 2021-07-24 19:38
they should be rendered like this 
![Untitled](https://user-images.githubusercontent.com/74387098/126879438-461fc2ba-a605-4e08-92d2-01abc2c60dbf.png)

**Comment by Hodakhosravi** [comment] 2021-07-24 20:00
I also have an issue with rendering button rendering. and also CSS attribute display: none too. I define two different images for mobile view and desk view but it shows both of them

**Comment by Hodakhosravi** [comment] 2021-07-24 20:01
![Untitled](https://user-images.githubusercontent.com/74387098/126879938-7562a5a1-3507-4f05-82c4-5d4b36b8e69f.png)
in all of the views the buttons doesn't rendered

**Comment by Hodakhosravi** [comment] 2021-07-26 17:08
> Hi, could you please provide your mjml code for these examples ?
> It's nearly impossible to know what the problem can be without seeing the code, especially when it's on outlook

`<mjml>
  <mj-head>
    <mj-title>McMaster-CTAs</mj-title>
    <mj-attributes>
      <mj-raw>
        
      </mj-raw>
    </mj-attributes>
    <mj-raw>
      
    </mj-raw>
    <mj-style>@media (max-width:480px) {
      .center {
      text-align: center;
      }
      .ctaMobileF {
      font-size: 22px !important;

      }
      }
      .link {
      color: #ffffff;
      text-decoration:none;
      }
      .link-gray {
      color: #5E6A71;
      text-decoration:none;
      }
      .shadow {
      -webkit-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      -moz-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      box-shadow: 1px 1px 12px 5px rgb(219 219 221);
      /* box-shadow: 2px 2px 2px rgb(136, 136, 136); */
      }</mj-style>
  </mj-head>
  <mj-raw>
    
  </mj-raw>
  <mj-body background-color="#F3F1F1" width="600px">
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding="0px">
        <mj-text color="#222222" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">CTA Accept your offer 1</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section background-url="https://mcmaster.onlinefiles.ca/test_images/CTA_Block_v3.png" background-size="cover" background-repeat="no-repeat" padding="20px">
      <mj-column width="60%" padding="20px">
        <mj-text color="#ffffff" font-size="28px" line-height="32px" font-family="Helvetica, Arial, sans-serif">
          <div class="center ctaMobileF">
            <b>Accept your Offer</b>
          </div>
        </mj-text>
        <mj-raw>
          
        </mj-raw>
        <mj-button css-class="center" background-color="#FDBF57" color="#222222" font-size="15px" font-weight="bold" href="#" width="200px" padding="15px 15px" border-radius="25px" font-family="Helvetica, Arial, sans-serif">LOREM IPSUN</mj-button>
      </mj-column>
      <mj-column width="40%">
        <mj-raw>
          
        </mj-raw>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding="0px">
        <mj-text color="#222222" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">CTA Accept your offer 2</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section background-url="https://mcmaster.onlinefiles.ca/test_images/CTA_Block_v3_Alt.png" background-size="cover" background-repeat="no-repeat" padding="20px">
      <mj-column width="60%" padding="20px">
        <mj-text color="#ffffff" font-size="28px" line-height="32px" font-family="Helvetica, Arial, sans-serif">
          <div class="center ctaMobileF">
            <b>Accept your Offer</b>
          </div>
        </mj-text>
        <mj-raw>
          
        </mj-raw>
        <mj-button css-class="center" background-color="#FDBF57" color="#222222" font-size="15px" font-weight="bold" href="#" width="200px" padding="15px 15px" border-radius="25px" font-family="Helvetica, Arial, sans-serif">LOREM IPSUN</mj-button>
      </mj-column>
      <mj-column width="40%">
        <mj-raw>
          
        </mj-raw>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
  </mj-body>
</mjml>
`

**Comment by Hodakhosravi** [comment] 2021-07-26 17:09
> Hi, could you please provide your mjml code for these examples ?
> It's nearly impossible to know what the problem can be without seeing the code, especially when it's on outlook

<mjml>
  <mj-head>
    <mj-title>McMaster-CTAs</mj-title>
    <mj-attributes>
      <mj-raw>
        
      </mj-raw>
    </mj-attributes>
    <mj-raw>
      
    </mj-raw>
    <mj-style>@media (max-width:480px) {
      .center {
      text-align: center;
      }
      .ctaMobileF {
      font-size: 22px !important;

      }
      }
      .link {
      color: #ffffff;
      text-decoration:none;
      }
      .link-gray {
      color: #5E6A71;
      text-decoration:none;
      }
      .shadow {
      -webkit-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      -moz-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      box-shadow: 1px 1px 12px 5px rgb(219 219 221);
      /* box-shadow: 2px 2px 2px rgb(136, 136, 136); */
      }</mj-style>
  </mj-head>
  <mj-raw>
    
  </mj-raw>
  <mj-body background-color="#F3F1F1" width="600px">
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding="0px">
        <mj-text color="#222222" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">CTA Accept your offer 1</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section background-url="https://mcmaster.onlinefiles.ca/test_images/CTA_Block_v3.png" background-size="cover" background-repeat="no-repeat" padding="20px">
      <mj-column width="60%" padding="20px">
        <mj-text color="#ffffff" font-size="28px" line-height="32px" font-family="Helvetica, Arial, sans-serif">
          <div class="center ctaMobileF">
            <b>Accept your Offer</b>
          </div>
        </mj-text>
        <mj-raw>
          
        </mj-raw>
        <mj-button css-class="center" background-color="#FDBF57" color="#222222" font-size="15px" font-weight="bold" href="#" width="200px" padding="15px 15px" border-radius="25px" font-family="Helvetica, Arial, sans-serif">LOREM IPSUN</mj-button>
      </mj-column>
      <mj-column width="40%">
        <mj-raw>
          
        </mj-raw>
      </mj-column>
    </mj-section>
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding="0px">
        <mj-text color="#222222" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">CTA Accept your offer 2</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section background-url="https://mcmaster.onlinefiles.ca/test_images/CTA_Block_v3_Alt.png" background-size="cover" background-repeat="no-repeat" padding="20px">
      <mj-column width="60%" padding="20px">
        <mj-text color="#ffffff" font-size="28px" line-height="32px" font-family="Helvetica, Arial, sans-serif">
          <div class="center ctaMobileF">
            <b>Accept your Offer</b>
          </div>
        </mj-text>
        <mj-raw>
          
        </mj-raw>
        <mj-button css-class="center" background-color="#FDBF57" color="#222222" font-size="15px" font-weight="bold" href="#" width="200px" padding="15px 15px" border-radius="25px" font-family="Helvetica, Arial, sans-serif">LOREM IPSUN</mj-button>
      </mj-column>
      <mj-column width="40%">
        <mj-raw>
          
        </mj-raw>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
  </mj-body>
</mjml>

**Comment by Hodakhosravi** [comment] 2021-07-26 17:10
<mjml>
  <mj-head>
    <mj-title>McMaster-video</mj-title>
    <mj-attributes>
      <mj-raw>
        
      </mj-raw>
    </mj-attributes>
    <mj-raw>
      
    </mj-raw>
    <mj-style>@media (max-width:480px) {
      .center {
      text-align: center;
      }
      /* hide dividers in mobile */
      .hidden {
      display: none;
      }
      .videoTextPad {
      padding-top:30px !important;
      }

      }

      .link {
      color: #ffffff;
      text-decoration:none;
      }
      .link-gray {
      color: #5E6A71;
      text-decoration:none;
      }
      .shadow {
      -webkit-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      -moz-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      box-shadow: 1px 1px 12px 5px rgb(219 219 221);
      /* box-shadow: 2px 2px 2px rgb(136, 136, 136); */
      }</mj-style>
  </mj-head>
  <mj-raw>
    
  </mj-raw>
  <mj-body background-color="#F5F4F4" width="600px">
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding-bottom="0px">
        <mj-text color="#222222" padding-bottom="0px" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">video 1</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section background-url="https://mcmaster.onlinefiles.ca/test_images/video-bkg.png" background-size="cover" background-repeat="no-repeat" padding="20px">
      <mj-group>
        <mj-column width="100%" padding="10px">
          <mj-image src="https://mcmaster.onlinefiles.ca/test_images/Video.png" padding="0px"></mj-image>
        </mj-column>
        <mj-column width="100%" css-class="videoTextPad">
          <mj-text css-class="videoTextPad" color="#ffffff" align="left" font-weight="bold" font-size="29px" line-height="22px" font-family="Helvetica, Arial, sans-serif" padding-bottom="0px">
            <div class="center">Video Title</div>
          </mj-text>
          <mj-text color="#ffffff" align="left" font-weight="bold" font-size="18px" line-height="28px" padding-top="0px">
            <div class="center">
              <b>___</b>
            </div>
          </mj-text>
          <mj-text color="#ffffff" align="left" padding-top="0px" font-weight="400" font-size="18px" line-height="22px" font-family="Montserrat, sans-serif">
            <div class="center">sit amet lacus commodo maximus utsit amet lacus commodo maximus ut commodo.</div>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding="0px 1px" css-class="center">
        <mj-text color="#222222" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">video 2</mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-section background-url="https://mcmaster.onlinefiles.ca/test_images/video-bkg-yellow.png" background-size="cover" background-repeat="no-repeat" padding="20px ">
      <mj-group>
        <mj-column width="100%" padding="10px">
          <mj-image src="https://mcmaster.onlinefiles.ca/test_images/Video.png" padding="0px"></mj-image>
        </mj-column>
        <mj-column width="100%" css-class="videoTextPad">
          <mj-text css-class="videoTextPad" color="#222222" align="left" font-weight="bold" font-size="29px" line-height="22px" font-family="Montserrat, sans-serif" padding-bottom="0px">
            <div class="center">Video Title</div>
          </mj-text>
          <mj-text color="#222222" align="left" font-weight="bold" font-size="18px" line-height="28px" padding-top="0px">
            <div class="center">
              <b>___</b>
            </div>
          </mj-text>
          <mj-text color="#222222" align="left" padding-top="0px" font-weight="400" font-size="18px" line-height="22px" font-family="Helvetica, Arial, sans-serif">
            <div class="center">sit amet lacus commodo maximus utsit amet lacus commodo maximus ut commodo.</div>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
    <mj-raw>
      
    </mj-raw>
    <mj-section>
      <mj-column width="100%" background-color="#F5F4F4" padding="0px 1px" css-class="center">
        <mj-text color="#222222" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">end of video</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by Hodakhosravi** [comment] 2021-07-29 14:05
I found the solution for the buttons in outlook but I couldn't find ant for the video blocks 
after converting to HTML, I changed the <a></a>in button to <p></p> and I wrapped the button text in to <a>.

**Comment by iRyusa** [comment] 2021-07-29 14:12
https://mjml.io/try-it-live/xmQ83HTA9Gj
I don't know why would you need mj-group here as it has clearly no purpose. You have 200% of content inside a section, outlook cannot manage more than 100% of content as browser does. It should fix your rendering issue in outlook but you'll need to tweak the mobile version then.
For the button never add a `href="#"` to any links because Outlook won't render them you can safely use mj-button but add a valid url like `href="https://example.com"`

**Comment by Hodakhosravi** [comment] 2021-07-29 14:23
> https://mjml.io/try-it-live/xmQ83HTA9Gj
> I don't know why would you need mj-group here as it has clearly no purpose. You have 200% of content inside a section, outlook cannot manage more than 100% of content as browser does. It should fix your rendering issue in outlook but you'll need to tweak the mobile version then.
> For the button never add a `href="#"` to any links because Outlook won't render them you can safely use mj-button but add a valid url like `href="https://example.com"`

Thanks for your quick reply

**Comment by Hodakhosravi** [comment] 2021-07-29 14:27
> https://mjml.io/try-it-live/xmQ83HTA9Gj
> I don't know why would you need mj-group here as it has clearly no purpose. You have 200% of content inside a section, outlook cannot manage more than 100% of content as browser does. It should fix your rendering issue in outlook but you'll need to tweak the mobile version then.
> For the button never add a `href="#"` to any links because Outlook won't render them you can safely use mj-button but add a valid url like `href="https://example.com"`

you just delete the group here?

**Comment by Hodakhosravi** [comment] 2021-07-30 20:14
should I open a new issue if I have another issue like the above?

**Comment by GarryFlemings** [comment] 2021-07-30 21:14
You've gotten responses from the MJML authorities here. I'll try to support them with a simple part of this.

> should I open a new issue if I have another issue like the above?

If there's something here you'd like more information about, probably do it here. If it's a different issue, open another.

There's grey area between those. If there was a penalty for doing it wrong, I presume it would have been levied against me; it has not.

FYI: It's hard to read your earliest posts here. I've had similar experiences when I used the "less than" character in this editing window. When I substitute "&lt;" (no quotes) for each of those, everything reads better. You can check the final appearance in the "Preview" tab just to the right of your editing window headshot. Maybe your text has some different characteristics.

**Comment by Hodakhosravi** [comment] 2021-07-30 21:41
I have somehow the same problem with outlook rendering in this file too, I don't know if it happens whenever I use MJ group/or use it in the wrong way.  

`<mjml>
  <mj-head>
    <mj-title>McMaster-Image Cards</mj-title>

    <mj-attributes>
      <mj-raw>
        
      </mj-raw>

    </mj-attributes>
    <mj-raw>
      
    </mj-raw>
    <mj-style>@media (max-width:480px) {
      .center {
      text-align: center;
      }
      .mobileW{
      width:50% !important;
      }
      }
      .link {
      color: #ffffff;
      text-decoration:none;
      }
      .link-gray {
      color: #5E6A71;
      text-decoration:none;
      }
      .shadow {
      -webkit-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      -moz-box-shadow:1px 1px 12px 5px rgb(219 219 221);
      box-shadow: 1px 1px 12px 5px rgb(219 219 221);
      /* box-shadow: 2px 2px 2px rgb(136, 136, 136); */
      }</mj-style>
  </mj-head>
  <mj-raw>
    
  </mj-raw>
  <mj-body background-color="#F3F1F1" width="600px">
    <mj-raw>
      
    </mj-raw>
    <mj-section>
      <mj-column width="100%" background-color="#ffffff" padding="0px 1px">
        <mj-text color="#5E6A71" align="center" font-weight="bold" font-size="14px" line-height="25px" font-family="Helvetica, Arial, sans-serif">Image Cards 2</mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff" padding="20px 0px 5px 0px">
      <mj-column background-color="#ffffff" padding="0px" width="100%">
        <mj-text color="black" align="center" font-weight="400" font-size="25px" line-height="22px" font-family="Helvetica, Arial, sans-serif"><b>About McMaster</b></mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff" padding="20px">
      <mj-group width="61%">
        <mj-column background-color="#ffffff" padding="0px" width="49%" css-class="shadow">
          <mj-image src="https://mcmaster.onlinefiles.ca/test_images/Card_3.png" padding="0px"></mj-image>
          <mj-text color="black" align="left" font-weight="400" font-size="14px" line-height="18px" font-family="Helvetica, Arial, sans-serif"><b>sit amet lacus commodo maximus ut eu arcu.</b></mj-text>
        </mj-column>
        <mj-column width="2%">
          <mj-raw>
            
          </mj-raw>
          <mj-text color="#ffffff" align="center">_______</mj-text>
        </mj-column>
        <mj-column background-color="#ffffff" padding="0px" width="49%" css-class="shadow">
          <mj-image src="https://mcmaster.onlinefiles.ca/test_images/Card_4.png" padding="0px"></mj-image>
          <mj-text color="black" align="left" font-weight="400" font-size="14px" line-height="18px" font-family="Helvetica, Arial, sans-serif"><b>sit amet lacus commodo maximus ut eu arcu.</b></mj-text>
        </mj-column>
      </mj-group>
      <mj-column width="2%">
        <mj-raw>
          
        </mj-raw>
        <mj-text color="#ffffff" align="center">_______</mj-text>
      </mj-column>
      <mj-column background-color="#ffffff" padding="0px" width="30%" css-class="shadow mobileW">
        <mj-image src="https://mcmaster.onlinefiles.ca/test_images/Card_5.png" padding="0px"></mj-image>
        <mj-text color="black" align="left" font-weight="400" font-size="14px" line-height="18px" font-family="Helvetica, Arial, sans-serif"><b>sit amet lacus commodo maximus ut eu arcu.</b></mj-text>
      </mj-column>
    </mj-section>
    <mj-raw>
      
    </mj-raw>
  </mj-body>
</mjml>
`

in here in outlook view the table extend the 600 px

**Comment by GarryFlemings** [comment] 2021-07-31 02:40
Some observations here.

- Usually, if we introduce a different piece of code, we'd start a new Issue. Let's not. I'll answer only about the most recent code unless you ask specifically about the earlier code. We'll make this work.
- I copied your code into https://mjml.io/try-it-live/VZZhDj2FJcy. That's a great way to get code to us. This worked. [I added numbers to some of your Latin.]
- About `mj-group`: The purpose (https://documentation.mjml.io/#mj-group is that, "mj-group allows you to prevent columns from stacking on mobile." The MJML team wrote the `mj-group` component for authors of email with columns who want the columns within the groups to always be side-by-side. They recommend against using if for authors who are most interested in each column being easily consumed rather than jammed side-by-side on a narrow screen.
  - Perhaps this email is a hybrid. The section _after_ "About McMaster" has three children, a group (width 61%), and two columns (widths 2% and 30%). The sum of those is less than 100% (as mentioned earlier; good). The group has three columns (widths 49%, 2%, and 49%). Sum: 100%, good.
  - The first two columns on the screen are in the 49% columns in the group. The third column is in the 30% column outside the group. The code will always want the first two columns side-by-side and the third column with them, width permitting.
  - Indeed, Try-It-Live shows exactly that on my computer. In the top right corner are three icons, "View HTML", a phone, and a computer monitor. With the monitor icon selected, I see three columns. With the phone icon selected, I see two columns in a row; below that is a row with the third of your screen columns. By design.
- About 600px: You're probably seeing that because it's the MJML default email width (see https://documentation.mjml.io/#mj-body and the `width` attribute).
- This code uses a media query and hopes for good rendering in Outlook; you didn't mention which. Consider https://www.caniemail.com/search/?s=%40media. Probably you're not talking about the Outlook based on Apple macOS software; it shows green there. Your media query is an embedded one, which none of the Outlooks in yellow support. The Outlooks in red support no media queries. That's all the Outlooks. Outlook isn't alone; see Gmail, Yahoo!, AOL, and others. This explains your problems with Outlook and encourages thorough testing with the others, too. You may decide on a different email design!
  - The MJML team recommends writing email "mobile first" (default behavior is mobile; media queries cause desktop behavior).
  - Since this email uses media query `max-width:480px`, the default is desktop and the media query creates mobile behavior.
  - A much smaller portion of small-screen email clients support media queries than wide-screen email clients (many of them desktops). You'll reach your mailing list better.
- Your use of `mj-raw` confused me. Perhaps it isn't doing what you want.
  - If your purpose is to include those comments in your MJML code, you can remove the various `mj-raw` tags. MJML accepts comments in the same syntax.
  - If your purpose is to include those comments in your HTML code, it isn't working. For example, select "View HTML" string in the top right of Try-It-Live and search for this code's comment "FONTS". If it's there, I missed it. Then, search for this code's comment "STYLES". It's probably not in an expected place--it landed in the line preceding `</mj-head>`.

This writing isn't comprehensive feedback, but it'll probably cause some valuable thought! My purpose in writing is to save you problems; I'll claim I did that. Sadly, it probably looks like I caused more work, too. Sorry! And welcome to email HTML. Not easy. MJML is a great tool to have.

**Comment by Hodakhosravi** [comment] 2021-08-01 17:03
> Some observations here.
> 
> * Usually, if we introduce a different piece of code, we'd start a new Issue. Let's not. I'll answer only about the most recent code unless you ask specifically about the earlier code. We'll make this work.
> * I copied your code into https://mjml.io/try-it-live/VZZhDj2FJcy. That's a great way to get code to us. This worked. [I added numbers to some of your Latin.]
> * About `mj-group`: The purpose (https://documentation.mjml.io/#mj-group is that, "mj-group allows you to prevent columns from stacking on mobile." The MJML team wrote the `mj-group` component for authors of email with columns who want the columns within the groups to always be side-by-side. They recommend against using if for authors who are most interested in each column being easily consumed rather than jammed side-by-side on a narrow screen.
>   
>   * Perhaps this email is a hybrid. The section _after_ "About McMaster" has three children, a group (width 61%), and two columns (widths 2% and 30%). The sum of those is less than 100% (as mentioned earlier; good). The group has three columns (widths 49%, 2%, and 49%). Sum: 100%, good.
>   * The first two columns on the screen are in the 49% columns in the group. The third column is in the 30% column outside the group. The code will always want the first two columns side-by-side and the third column with them, width permitting.
>   * Indeed, Try-It-Live shows exactly that on my computer. In the top right corner are three icons, "View HTML", a phone, and a computer monitor. With the monitor icon selected, I see three columns. With the phone icon selected, I see two columns in a row; below that is a row with the third of your screen columns. By design.
> * About 600px: You're probably seeing that because it's the MJML default email width (see https://documentation.mjml.io/#mj-body and the `width` attribute).
> * This code uses a media query and hopes for good rendering in Outlook; you didn't mention which. Consider https://www.caniemail.com/search/?s=%40media. Probably you're not talking about the Outlook based on Apple macOS software; it shows green there. Your media query is an embedded one, which none of the Outlooks in yellow support. The Outlooks in red support no media queries. That's all the Outlooks. Outlook isn't alone; see Gmail, Yahoo!, AOL, and others. This explains your problems with Outlook and encourages thorough testing with the others, too. You may decide on a different email design!
>   
>   * The MJML team recommends writing email "mobile first" (default behavior is mobile; media queries cause desktop behavior).
>   * Since this email uses media query `max-width:480px`, the default is desktop and the media query creates mobile behavior.
>   * A much smaller portion of small-screen email clients support media queries than wide-screen email clients (many of them desktops). You'll reach your mailing list better.
> * Your use of `mj-raw` confused me. Perhaps it isn't doing what you want.
>   
>   * If your purpose is to include those comments in your MJML code, you can remove the various `mj-raw` tags. MJML accepts comments in the same syntax.
>   * If your purpose is to include those comments in your HTML code, it isn't working. For example, select "View HTML" string in the top right of Try-It-Live and search for this code's comment "FONTS". If it's there, I missed it. Then, search for this code's comment "STYLES". It's probably not in an expected place--it landed in the line preceding `</mj-head>`.
> 
> This writing isn't comprehensive feedback, but it'll probably cause some valuable thought! My purpose in writing is to save you problems; I'll claim I did that. Sadly, it probably looks like I caused more work, too. Sorry! And welcome to email HTML. Not easy. MJML is a great tool to have.

Hello Garry! Thank you for your response. I really appreciate the time you are giving to this issue.

**Closed** 2021-08-03 19:21 UTC

**Comment by GarryFlemings** [comment] 2021-08-03 19:39
Sorry for the slow response. I'll answer you. But first, a correction. (Better to own it than lead you astray or make someone else correct me.)

I said above the media query in this code is an embedded one. 😓 In this code the media query takes the form

```
@media (max-width:480px) {
   .a { [key:value]; }
   .b { [key:value]; }
}
```

I later did some web searching. First, caniemail.com used the term "nested"; I wish I had. 😥 Second, all references I found to nested media queries were of the form

```
@media (max-width:480px) {
   .a { [key:value]; }
   @media (max-height:1200px) {
      .b { [key:value]; }
   }
}
```

The second `@media` makes it different. Apologies.

The impact on my comments is: As with any yellow in caniemail.com, I'll recommend testing more thoroughly than otherwise if the email uses techniques "close" to the condition mentioned there. From the frequency of comments about this email with media queries on the Internet and from my experience, expect to find problems somewhere. The number of problems you find and the number of your readers that use those clients will inform your decision about redesign of the email.

To your note:

MJML 3 is a version of MJML the team deprecated over a year ago. If you're preparing your code based on the documentation most easily found on the web, you're writing in MJML 4. Useful results from using the conversion code seem likely to be coincidental; problems are expectable. If that code is adding the `mj-raw`s, that change is clutter.

If you're using an Atom with MJML 3, the team would advise you to find a way to upgrade. Perhaps it would be useful to start with this link
https://github.com/mjmlio/atom-mjml-preview/releases
That should get you MJML 4.8. Use that instead of either of the two links in our documentation--they're older. ​I'm not an Atom user; perhaps a question in Slack would yield more help if needed. (I've asked the team about changing the documentation.)

Recommended: Avoid MJML 3 unless absolutely necessary; the current MJML 4 has better syntax, attractive new features and better support.

The MJML Slack is
https://mjml.slack.com/
If you have trouble signing on, try
https://join.slack.com/t/mjml/shared_invite/zt-gqmwfwmr-kPBnfuuB7wof5httaTcXxg
It's a friendly group. If someone knows something, you'll get help. It might be succinct; it'll be polite.

**Comment by Hodakhosravi** [comment] 2021-08-03 19:57
> @media (max-width:480px) {
>    .a { [key:value]; }
>    @media (max-height:1200px) {
>       .b { [key:value]; }
>    }
> }

Thanks, Garry,I joined the slack and I think it will help me a lot. I try to check the Atom updates for MJML but since last week I didn't have any update in mjml plugins for Atom. about nested @media you mean I should put my value and key in [] ?

**Comment by GarryFlemings** [comment] 2021-08-03 21:48
Atom for updates: Here's a rare case when I'll suggest that you use software other than from the editor's vendor. I've looked on the Atom website. The immediate predecessor version to their current version is the same predecessor to the version on the MJML site. The author of that version is a highly respected (former) member of the MJML team. The author of the version on the MJML site (that's the URL I gave) is a highly respected (current) member of the MJML team. The version on the Atom website is not attributed or I missed it.

Decide for yourself; don't trust a stranger on the Internet (from another continent!) If it was me, I'd use the MJML version. Good luck.

nested @media: Please don't. That's the condition caniemail.com warns against. When you test, you'll get worse results than with your current code.

**Comment by Hodakhosravi** [comment] 2021-08-03 21:53
> Atom for updates: Here's a rare case when I'll suggest that you use software other than from the editor's vendor. I've looked on the Atom website. The immediate predecessor version to their current version is the same predecessor to the version on the MJML site. The author of that version is a highly respected (former) member of the MJML team. The author of the version on the MJML site (that's the URL I gave) is a highly respected (current) member of the MJML team. The version on the Atom website is not attributed or I missed it.
> 
> Decide for yourself; don't trust a stranger on the Internet (from another continent!) If it was me, I'd use the MJML version. Good luck.
> 
> nested @media: Please don't. That's the condition caniemail.com warns against. When you test, you'll get worse results than with your current code.

Thanks a lot for your time.
