### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by AlaJohnson** [mjmlio/mjml#2455] opened 2022-03-30 19:08 UTC
**Is your feature request related to a problem? Please describe.**
Easy solve for dark mode vs inline css everywhere

**Describe the solution you'd like**
section in the header to set link color, button color, font color, etc for dark mode 

**Describe alternatives you've considered**
Inline css for all components, but leaves a lot of room for error

**Additional context**
likely will be continuing to grow in use. 50% of our audience currently

**Comment by iRyusa** [comment] 2022-04-21 08:33
Duplicate of #2010

**Closed by iRyusa** 2022-04-21 08:33 UTC
