### ISSUE TITLE
Sample layout breaks on mobile

### ISSUE THREAD

**Issue by cbdtn** [mjmlio/mjml#142] opened 2016-03-21 06:29 UTC
Tried the basic layout sample at https://mjml.io/try-it-live/basic . The layout breaks on mobile due to a fixed width <mj-column width="400"> . Is there a fix?

**Comment by arnaudbreton** [comment] 2016-03-21 18:20
Hey @cbdtn, sorry to hear that. On which email client / device are you testing? Also, do you have a screenshot of the result, so we visualise better the issue? Thanks for your help.

**Comment by cbdtn** [comment] 2016-03-22 09:32
Thanks for your reply, @arnaudbreton . I tested out the sample layout in Android(gmail and inbox), iPhone(mail and gmail) and they seem to work fine in mail clients but seems to be breaking when opened in a mobile browser strangely. Also, the layout breaks when resized to a mobile width in Chrome - Mac and while using the Chrome's device mode.

You should be able to see a similar behaviour in the sample layout example( https://mjml.io/try-it-live/basic ) where a horizontal scroll happens when the mobile layout is picked . Do you see that as well?

<img width="398" alt="screen shot 2016-03-22 at 3 00 38 pm" src="https://cloud.githubusercontent.com/assets/3166995/13947178/f0214704-f03e-11e5-9a19-46ef3c5f2e62.png">

**Comment by Tlapi** [comment] 2016-03-23 19:39
The problem is with `min-width`, which is set to 400px when you set `width` of `mj-column` to `400`. I think there could be `max-width:100%` on a `mj-column` and `width` should be set instead of `min-width`.

What do you think?

**Comment by iRyusa** [comment] 2016-03-25 10:26
As @Tlapi mention `min-width` is the problem here. We have to check if we can remove it safely

**Comment by cbdtn** [comment] 2016-03-25 12:34
Thanks @Tlapi @iRyusa.

Instead of `min-width`, I would suggest you to use `max-width` will fix the problem. 

And one more thing, I just found out by testing the sample layout in **gmail client** at chrome browser - Mac. The two or three column grid won't work as expected. 

<img width="1499" alt="screen shot 2016-03-25 at 5 19 47 pm" src="https://cloud.githubusercontent.com/assets/3166995/14044080/0a24e622-f2b2-11e5-863d-0810e6183549.png">

In **outlook client** at chrome browser shows the good result, but when I **resizing the browser window** smaller that changes the email layout poor. 

And also I am checking few other things. Will give an update once I gone throw with it. Thanks.

**Comment by iRyusa** [comment] 2016-03-25 12:44
Keep in mind that MJML is designed with a mobile first approach, so `max-width` wont help much.

It's a bug with google apps gmail, there 's still an issue opened for google apps #24 . We're still trying to fix it

**Comment by cbdtn** [comment] 2016-03-25 12:46
Oh! Ok, I got it. Thanks.

**Comment by arnaudbreton** [comment] 2016-04-11 17:01
@cbdtn closing for now. Tracking GApps issue through #24. Feel free to comment there.

**Closed by arnaudbreton** 2016-04-11 17:01 UTC
Labels: Render issue
