### ISSUE TITLE
<mj-image> is resized to 50px in <mj-hero-content>

### ISSUE THREAD

**Issue by gdavalos** [mjmlio/mjml#546] opened 2017-02-09 23:58 UTC
I'm trying to add an image inside an `<mj-hero-content>` but the generated html puts the image inside a 50px `<td>` even if I try to set the image's width to anything bigger.

Here's the code (and here's a link to the [online editor](https://mjml.io/try-it-live/BkdSRO9ue) where I tried it)
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-hero>
            <mj-hero-content>
              <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>
            </mj-hero-content>
          </mj-hero>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment] 2017-02-10 01:07
Hello @gdavalos 

`Mj-Hero` cannot live inside a `mj-section` or `mj-column` it should be within `mj-container`. But it looks like it has the same issue with the width, so i'll keep the issue open.

**Comment by mikwraae** [comment] 2017-03-27 15:19
Did anyone find a workaround for this? 

Or any status on a fix?

**Comment by iRyusa** [comment] 2017-03-28 14:44
Still no fix available, we're focusing on the 3.3.2 release with `mj-button` and `css-class` support.

I think there's an issue with `parentWidth` to `undefined` when you got an `mj-image` so that's why the image-width is miss-calculated

**Comment by iRyusa** [comment] 2017-04-06 15:10
As a temporary fix, you can set a non standard `width` attribute on `mj-hero-content` and it will work as intended @gdavalos @mikwraae

**Comment by daaain** [comment] 2017-08-17 15:46
I couldn't figure out what "non-standard width" means in this context, but strangely it seems if you set a pixel `width` on `mj-hero-content` it'll be applied, but with `50px` subtracted, so when I set it to be the width of the image `-50px` it did what it should :)

Luckily this explicit width didn't break the fluid width either, so working well on mobile too. Just thought I'd share in case anyone else is wondering.

I haven't yet tested this extensively across various clients though, will report back if there's breakage.

**Comment by iRyusa** [comment] 2017-08-17 15:56
@daaain This is because mj-image removes the padding to the width ( so it's width - padding-left - padding-right )

**Comment by iRyusa** [comment] 2017-10-17 14:10
This will be fixed in MJML4, 3.x branch will still require the width on mj-hero-content

**Comment by ngarnier** [comment] 2018-01-25 10:50
This is fixed in the latest beta for MJML 4, install with `npm install mjml@next`. Note that the syntax for hero changed, it is now like that: 

```xml
<mjml>
  <mj-body>
    <mj-hero
      mode="fixed-height"
      height="469px"
      width="100%"
      background-width="600px"
      background-height="469px"
      background-url="https://cloud.githubusercontent.com/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg"
      background-color="#2a3448"
      padding="100px 0px">
        <mj-image width="100px" src="https://mjml.io/assets/img/logo-small.png"></mj-image>
    </mj-hero>
  </mj-body>
</mjml>
```

**Closed by ngarnier** 2018-01-25 10:50 UTC
Labels: Bug, MJML 4

**Comment by VampireGirl** [comment] 2018-10-26 09:29
> This is fixed in the latest beta for MJML 4, install with `npm install mjml@next`. Note that the syntax for hero changed, it is now like that:
> 
> ```
> <mjml>
>   <mj-body>
>     <mj-hero
>       mode="fixed-height"
>       height="469px"
>       width="100%"
>       background-width="600px"
>       background-height="469px"
>       background-url="https://cloud.githubusercontent.com/assets/1830348/15354890/1442159a-1cf0-11e6-92b1-b861dadf1750.jpg"
>       background-color="#2a3448"
>       padding="100px 0px">
>         <mj-image width="100px" src="https://mjml.io/assets/img/logo-small.png"></mj-image>
>     </mj-hero>
>   </mj-body>
> </mjml>
> ```

Hi, I had the same issue. My image stayed tiny and I couldn't change the width but I tried `width="100%"` and it worked in the preview, but I get this error saying **Attribute width is illegal.**
(The width attribute worked for me before though, without any errors.)

This is my code:
```
<mj-hero width="100%" background-color="#fff" padding-top="60px" padding-left="30px" padding-right="30px">
      <mj-image src="gsoc.openmrs.png"></mj-image>
      <mj-text font-size="30px" line-height="40px" align="center" mj-class="secondary-color">
        Thank you<br>
        <b>{{username}}</b>
        <br>for your contribution to OpenMRS, during the GSoC.
      </mj-text>
    </mj-hero>
```

Please help me fix this error.
Thanks
