### ISSUE TITLE
Uglify-js dependency error

### ISSUE THREAD

**Issue by jamesmart77** [mjmlio/mjml#2562] opened 2022-10-25 17:50 UTC
**Describe the bug**
I have a serverless app that is trying to build an email but keep getting this error. 
`Error: Error: ENOENT: no such file or directory, open '../../uglify-js/lib/utils.js'`

I can see that `uglify-js` is a dependency within `mjml-cli`.
└─┬ mjml@4.13.0
  └─┬ mjml-cli@4.13.0
    └─┬ html-minifier@4.0.0
      └── uglify-js@3.17.4

I've tried installing `uglify-js` directly, deleting package-lock and node-modules then reinstalling (both node 14.20.0 and 16.17.0) but still the same issue.

I can see in the node-modules that the uglify-js/lib/utils.js file is there so the relative reference seems to be off??
![image](https://user-images.githubusercontent.com/29242164/197845894-4b3774a6-624f-4512-8619-0eb165c2b010.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/29242164/197845634-db12903b-4e01-46d8-a205-200a7381499b.png)

**Comment by iRyusa** [comment] 2022-10-25 18:03
Is it happening on your server or on your local machine ?Any repository to reproduce ? Seems weird as require is resolved by node. Do you have any stack trace ?On 25 Oct 2022, at 19:50, James Martineau ***@***.***> wrote:﻿
Describe the bug
I have a serverless app that is trying to build an email but keep getting this error.
Error: Error: ENOENT: no such file or directory, open '../../uglify-js/lib/utils.js'
I can see that uglify-js is a dependency within mjml-cli.
└─┬ ***@***.***
└─┬ ***@***.***
└─┬ ***@***.***
└── ***@***.***
I've tried installing uglify-js directly, deleting package-lock and node-modules then reinstalling (both node 14.20.0 and 16.17.0) but still the same issue.
I can see in the node-modules that the uglify-js/lib/utils.js file is there so the relative reference seems to be off??

Screenshots

**Comment by iRyusa** [comment] 2022-10-31 10:50
Closing for now. Feel free to reopen if you add more details.

**Closed by iRyusa** 2022-10-31 10:50 UTC

**Comment by mobeigi** [comment] 2024-09-19 05:57
Getting same issue with Next.js 15 (app router).

Solution is discussed here: https://github.com/vercel/next.js/issues/50042

Add to: `next.config.js`

```
module.exports = {
  serverExternalPackages: ['mjml'],
};
```
