### ISSUE TITLE
Attributes containing `&quot;` break when inline mj-style is applied

### ISSUE THREAD

**Issue by jeissler** [mjmlio/mjml#2576] opened 2022-11-16 19:26 UTC
**Describe the bug**
Mjml attribute strings which contain `&quot;` break the rendered html output when also applying an inline mj-style. This only happens once an inline style has been applied to the same element as the attribute containing `&quot;`. This doesn't seem isolated to any single element or attribute, any combination of `&quot;` in attributes + `<mj-style inline="inline">` on the same element produces the bad output. 

This seems like a bug since these values work fine when not combined w/ an inline mj-style tag. In our case not using the inline attribute for mj-style or `&quot;`'s in our values isn't an option and currently are working around this using string replacement where necessary. 

Example mjml attribute value:
`font-family="Garamond, &quot;Adobe Garamond Pro&quot;, Palatino, &quot;Times New Roman&quot;, serif"`

Example bad html output:
`font-family: Garamond, " undefined: AdobeGaramondPro" undefined: ,Palatino," undefined: TimesNewRoman" undefined: ,serif;`

**To Reproduce**
Paste the below mjml into the `mjml.io/try-it-live` editor and inspect the rendered html output for the font attributes on each element:

```
<mjml>
  <mj-head>
  	<mj-style inline="inline">
    	.navbar a {
      	display: block!important;		
      }
      .button p {
      	display: block!important;		
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section background-color="#ef6451">
      <mj-column>
        <mj-navbar css-class="navbar" base-url="https://mjml.io" hamburger="hamburger" ico-color="#ffffff">
          <mj-navbar-link href="/gettings-started-onboard" color="#ffffff" font-family="Garamond, &quot;Adobe Garamond Pro&quot;, Palatino, &quot;Times New Roman&quot;, serif">Getting started</mj-navbar-link>
          <mj-navbar-link href="/try-it-live" color="#ffffff" font-family="Garamond, &quot;Adobe Garamond Pro&quot;, Palatino, &quot;Times New Roman&quot;, serif">Try it live</mj-navbar-link>
          <mj-navbar-link href="/templates" color="#ffffff" font-family="Garamond, &quot;Adobe Garamond Pro&quot;, Palatino, &quot;Times New Roman&quot;, serif">Templates</mj-navbar-link>
          <mj-navbar-link href="/components" color="#ffffff" font-family="Garamond, &quot;Adobe Garamond Pro&quot;, Palatino, &quot;Times New Roman&quot;, serif">Components</mj-navbar-link>
        </mj-navbar>
      </mj-column>
    </mj-section>
    <mj-section>
    	<mj-column>
      	<mj-button css-class="button" font-family="Garamond, &quot;Adobe Garamond Pro&quot;, Palatino, &quot;Times New Roman&quot;, serif">
        	Button
        </mj-button>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment] 2022-11-16 20:21
I don't really get why would you need to encode those quotes here as it
won't work at the end ?

I think the issue is in Juice itself so you should be able to test it here
https://automattic.github.io/juice/ and not on MJML side.

Keep in mind that in your case, you can just remove those quotes.

**Comment by jeissler** [comment] 2022-11-16 23:10
@iRyusa thanks very much for your response and contributions to mjml! 

The encoded quotes `&quot;` do work inside mjml attributes though; the rendered html is correct until adding an inline mj-style. I think you are correct as passing an example into the juice inliner online w/ encoded quotes does seem to fail badly. I hadn't looked at the mjml code closely enough to know this was being done w/ a separate package.

We have an internal implementation that sets mjml attributes which unfortunately has data formatted w/ these values and is not easily updated.

**Comment by iRyusa** [comment] 2022-11-17 08:32
It works but won't serve any purpose as they won't get decoded anywhere, and as said you can juste remove those quotes as 99.9% of font-families are valid css identifier so there's no need to put quote around them.

I'm closing as there's nothing we can do about this

**Closed by iRyusa** 2022-11-17 08:32 UTC
