### ISSUE TITLE
How to achieve equal height on two columns?

### ISSUE THREAD

**Issue by chesterlaykin** [mjmlio/mjml#2211] opened 2021-03-18 16:06 UTC
I have an example here where there is text and an image in the left column. I'd like this column to be the same height as the right column, but there is no suppot for a "height" property. 

So can you give some guidance how to make the text container of the left column expand in height so the total height is the same as the right. See this example:

[mjml example](https://mjml.io/try-it-live/bId4Fd_fmCC)

```
<mjml>
   <mj-head>
      <mj-breakpoint width="750px" />
      <mj-attributes>
         <mj-body width="750px"></mj-body>
         <mj-wrapper padding-top="0px" padding-bottom="0px" padding-left="0px" padding-right="0px"></mj-wrapper>
         <mj-font name="Oswald" href="https://fonts.googleapis.com/css?family=Oswald" />
         <mj-text font-family="Oswald, Arial, Helvetica, sans-serif" align="left" padding-top="0px" padding-bottom="0px" padding-left="0px" padding-right="0px" color="#101010" font-size="12px" line-height="19px">
         </mj-text>
         <mj-section padding-top="0px" padding-bottom="0px" padding-right="0px" padding-left="0px"></mj-section>
         <mj-column padding="0"></mj-column>
         <mj-button background-color="#2D59DC" text-transform="uppercase" line-height="120%" inner-padding="15px 24px" padding="0px" font-weight="bold">
         </mj-button>
         <mj-image padding="0px"></mj-image>
         <mj-divider border-color="transparent" border-width="1px" padding-top="0px" padding-bottom="0">
         </mj-divider>
      </mj-attributes>
     
   </mj-head>
   <mj-body background-color="#F2F2F2">
      <mj-wrapper>
         <mj-section  background-size="cover" padding-top="10px" padding-bottom="10px">
         </mj-section>
      </mj-wrapper>
     
      <mj-wrapper background-color="#ffffff">
        
         <mj-section padding-bottom="0">
           
            <mj-column>
               <mj-text container-background-color="#E0D8D8" padding-left="36px" padding-right="36px" padding-top="28px" padding-bottom="20px" font-size="12px">
                  <b>Here is title</b>
               </mj-text>
               <mj-text container-background-color="#E0D8D8" padding-left="36px" padding-right="36px" padding-bottom="28px">
                  <div>Hello some text</div>
               </mj-text>
               <mj-image src="https://images.unsplash.com/photo-1611095971113-9f7542655338?ixid=MXwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=3151&q=80" padding="0"></mj-image>
            </mj-column>
           
           
           
            <mj-column padding-top="0px" background-color="white">
               <mj-text padding-top="11px" padding-left="36px" padding-right="36px" padding-bottom="11px" font-size="15px" container-background-color="#2D59DC" color="#101010">
                  <b>More!</b>
               </mj-text>
               <mj-text padding-top="20px" padding-left="36px" padding-right="36px" padding-bottom="13px" font-size="15px" color="#2D59DC">
                  <b>box content</b>
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="20px">Optimization
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="13px" font-size="15px" color="#2D59DC">
                  <b>  design options</b>
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="20px">
                  <p><b>  design options.</b></p>
                  <p><br></p>
                  <p>  design options</p>
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="13px" font-size="15px" color="#2D59DC">
                  <b>box content</b>
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="20px">
                  <div>omnis necessitatibus iure adipisci vel. Nihil quia pariatur totam doloremque eos itaque vel aut officiis nobis laborum, eligendi  laborum, eligendi  laborum, eligendi vitae quidem nisi illo quo ducimus quisquam ores praesentium! Ea, doloremque.</div>
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="13px" font-size="15px" color="#2D59DC">
                  <b>box content</b>
               </mj-text>
               <mj-text padding-left="36px" padding-right="36px" padding-bottom="20px">
                  &nbsp;box content
                  <div>&nbsp;box content
                  </div>
                  <div>&nbsp;box content
                  </div>
                  <div>&nbsp;box content
                  </div>
                  <div><br></div>
               </mj-text>
            </mj-column>
         </mj-section>
      </mj-wrapper>
      <mj-wrapper padding-bottom="70px">
      </mj-wrapper>
   </mj-body>
</mjml>
```

**Comment by iRyusa** [comment] 2021-03-18 16:49
Duplicate of #1582

**Closed by iRyusa** 2021-03-18 16:49 UTC
