### ISSUE TITLE
Web Outlook Office 365 Issues with mj-button

### ISSUE THREAD

**Issue by nvassos** [mjmlio/mjml#875] opened 2017-11-07 22:56 UTC
Hi guys, has anyone seen an issue with the mj-button rendering on the Web Version of Outlook in Office 365. Please check link below, the white box is supposed to be a button but it is the only browser that breaks it. 

[![Screenshot from Gyazo](https://gyazo.com/849413213034b2f4fea4e01a2df3ac2d/raw)](https://gyazo.com/849413213034b2f4fea4e01a2df3ac2d)

**Comment by ngarnier** [comment] 2017-11-08 08:11
Hi @nvassos, did you add a valid `href` on `mj-button`? Outlook doesn't like invalid hrefs so that's very likely the issue.

If not, please provide the MJML used.

**Comment by nvassos** [comment] 2017-11-08 16:52
Hey there @ngarnier. Every single browser renders fine, including other outlooks. The issue only happens on the Web Version of Office 365 Outlook. And yes the href has a valid url. 

          <mj-button href="http://www.theagencyre.com" font-weight="bold" font-size="18px" inner-padding="15px 45px" font-family="Arial" background-color="black" color="white" border="1px solid white" border-radius="0" padding="20px 0 10px 0"> view current listing
          </mj-button>

**Comment by ngarnier** [comment] 2017-11-08 16:56
I don't have any issue when trying your snippet, you can see the Litmus result here: https://litmus.com/checklist/emails/public/3cb452a#chromeoutlookcom.

Therefore, I suspect the issue is from some other code/style in your template. Really no way for you to share the whole MJML template?

**Comment by nvassos** [comment] 2017-11-08 17:35
Hey @ngarnier , I think Campaign Monitor is adding/removing something. There is a weird font-size:0px, which if I remove, the button shows up fine. I will keep playing with it. I will follow up when I figure it out... CampaignMonitor SUCKS.

**Comment by ngarnier** [comment] 2017-11-09 09:10
Ha that's annoying! I'm closing as it's an issue with Campaign Monitor then but please let us know what the exact issue is and if there's a workaround when you get an answer!

**Closed by ngarnier** 2017-11-09 09:10 UTC

**Comment by Serginyo90** [comment] 2018-10-03 17:18
@ngarnier @nvassos Hey, guys. Did you solve the issue?

**Comment by ngarnier** [comment] 2018-10-04 14:57
In some way as we identified it to be on Campaign Monitor side... so nothing we can do on our end.
