### ISSUE TITLE
MJ-image tags and HTML 5

### ISSUE THREAD

**Issue by masfi** [mjmlio/mjml#925] opened 2017-12-20 21:17 UTC
Is there any way in the mjml library to stop using self-closing tags like the issue with https://github.com/artf/grapesjs-mjml/issues/41?

**Comment by ngarnier** [comment] 2017-12-21 08:33
Hi @masfi, 

Seems the issue is with using self-closing tag (`<mj-image />`) in grapejs-mjml, to avoid it just use the normal closing tag (`<mj-image></mj-image>`) as it's supported too in MJML and won't cause any issue in grapejs.

Also seems that the issue was solved anyway in grapejs in the meantime.

**Closed by ngarnier** 2017-12-21 08:33 UTC
