### ISSUE TITLE
4.2.1 difference to 4.2.0 : Outlook on Android columns with mj-group

### ISSUE THREAD

**Issue by jackfranklin** [mjmlio/mjml#1436] opened 2018-11-23 11:18 UTC
Firstly, thank you for MJML! It's made emails so much nicer for us to work with.

4.2.1 seems to have introduced some behaviour that breaks `<mj-group>` on Outlook for Android.

Here's the behaviour on 4.2.0:
https://cl.ly/c22361c184eb/Screen%20Shot%202018-11-23%20at%2011.16.06.png

And here's the same email (no changes to the MJML source) on 4.2.1:
https://cl.ly/24b29b611424/Screen%20Shot%202018-11-23%20at%2011.16.47.png

I'm not seeing this change on any other client that we test. We are minifying our HTML.

Our code looks like this (I did wonder if it's the `mj-raw` with the templating that's causing a change)?

```
    <mj-raw>{% for item_row in items_for_email %}</mj-raw>
    <mj-section padding="0">
      <mj-group>
        <mj-raw>{% for item in item_row %}</mj-raw>
        <mj-column width="50%">
          <mj-image border-radius="6px" padding="0 5%" src="{{item.img}}" />
          <mj-text mj-class=" item-details" padding-top="0">
            <p style="font-weight:bold;">{{item.brand}}</p>
            <p>{{item.title}}</p>
            <p>{{item.price}} · <span style="color: #787878;">{{item.size}}</span></p>
          </mj-text>
        </mj-column>
        <mj-raw>{% endfor %}</mj-raw>
      </mj-group>
    </mj-section>
    <mj-raw>{% endfor %}</mj-raw>
```

The screenshots above are taken from Litmus.

**Comment by jackfranklin** [comment] 2018-11-23 11:48
Quick update : I started deleting content from the columns to find the issue; and it turned out it was the paragraphs inside the `mj-text` doing it. I've ditched them (for more `mj-text` elements, not nested) and Outlook is happy again.

Feel free to close this if you like :)

**Comment by kmcb777** [comment] 2018-11-23 13:59
Hi @jackfranklin, in the end did you get a different result with the same template with 4.2.1 vs 4.2.0, or was it caused by the content ?
The only components that have been modified on 4.2.1 are hero and social, so this would be surprising 🤔

**Comment by kmcb777** [comment] 2018-11-26 14:01
@jackfranklin i think litmus shouldn't affect the result
Unfortunately it's hard to test without having the actual template generated with your variables.
Also outlook for android is not available on emailonacid, but i made a few tests with a template that could be generated from this (see below) and i didn't notice a difference on any client
```<mjml>
  <mj-body>

    <mj-section padding="0">
      <mj-group>
        <mj-column width="50%">
          <mj-image border-radius="6px" padding="0 5%" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350" />
          <mj-text mj-class=" item-details" padding-top="0">
            <p style="font-weight:bold;">Base London</p>
            <p>Greenwich Washed</p>
            <p>$79.99 · <span style="color: #787878;">UK 11 / EU45</span></p>
          </mj-text>
        </mj-column>
        <mj-column width="50%">
          <mj-image border-radius="6px" padding="0 5%" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350" />
          <mj-text mj-class=" item-details" padding-top="0">
            <p style="font-weight:bold;">Base London</p>
            <p>Greenwich Washed</p>
            <p>$79.99 · <span style="color: #787878;">UK 11 / EU45</span></p>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
    <mj-section padding="0">
      <mj-group>
        <mj-column width="50%">
          <mj-image border-radius="6px" padding="0 5%" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350" />
          <mj-text mj-class=" item-details" padding-top="0">
            <p style="font-weight:bold;">Base London</p>
            <p>Greenwich Washed</p>
            <p>$79.99 · <span style="color: #787878;">UK 11 / EU45</span></p>
          </mj-text>
        </mj-column>
        <mj-column width="50%">
          <mj-image border-radius="6px" padding="0 5%" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=350" />
          <mj-text mj-class=" item-details" padding-top="0">
            <p style="font-weight:bold;">Base London</p>
            <p>Greenwich Washed</p>
            <p>$79.99 · <span style="color: #787878;">UK 11 / EU45</span></p>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>

  </mj-body>
</mjml>
```

**Comment by stephenrust** [comment] 2018-11-26 14:14
@jackfranklin Sorry to go off topic here, but which templating language are you using in your template?

**Comment by iRyusa** [comment] 2018-11-29 15:56
As we can't really reproduce, I'm closing this issue

**Closed by iRyusa** 2018-11-29 15:56 UTC
