### ISSUE TITLE
Building a Receipt

### ISSUE THREAD

**Issue by DanyeWest** [mjmlio/mjml#1411] opened 2018-10-30 17:46 UTC
I actually was able to find an MJML template and copied it for a general layout, and that is working. I'm still having an issue with the text being very cramped in mobile. 

**Reproduction Steps:**

1. View in Desktop mode (looks good)
2. View in Mobile (looks cramped)

**Expected behavior:**
See what is happening with "brown shoes"/ column 2? the entire text "Size 9.5" is showing up in one row

**Observed behavior:**

text is breaking up mid word

**Screenshots and GIFs**
![screen shot 2018-10-30 at 11 44 38 am](https://user-images.githubusercontent.com/22229237/47738698-4d202900-dc39-11e8-9638-a75179869f7b.png)
![screen shot 2018-10-30 at 11 44 47 am](https://user-images.githubusercontent.com/22229237/47738706-527d7380-dc39-11e8-9138-b4ecf71a7587.png)

**MJML version:**
4.1.2

**Email clients the bug is seen on:**
MJML app

**Comment by ngarnier** [comment] 2018-10-30 17:56
hey @DanyeWest, you missed the most important part, aka the MJML code so we can reproduce :).

**Comment by DanyeWest** [comment] 2018-10-30 18:01
Oh, I'm sorry!

**Comment by DanyeWest** [comment] 2018-10-30 18:02
<mjml>
  <mj-body background-color="#e9e9e9">
    <mj-section>
      <mj-column vertical-align=" middle">
        <mj-image align="center" src="https://cdn.shopify.com/s/files/1/0269/7759/files/Welcome-Knotty-Logo-Header_large.png?v=1539726845" alt="Knotty Tie logo" target="_blank" width="75px"></mj-image>
      </mj-column>
    </mj-section>
    <mj-section background-color="#607482" padding="0px">
      <mj-column>
        <mj-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/GoodToGo_large.png?v=1540843076" alt="Good to Go! Image of a sewing machine" align="center" padding-left="0px" padding-right="0px" padding-bottom="0px" padding-top="0px"></mj-image>
      </mj-column>
    </mj-section>
    <mj-section background-color="#f6893e" padding-bottom="0px" padding-top="0">
      <mj-column width="50%">
        <mj-text align="center" color="#ffffff" font-size="12px" padding-left="25px" padding-right="25px" padding-bottom="15px" padding-top="15px">
          <strong style="font-family: Veranda,Ariel,sans-serif; font-size:25px">ORDER #17902</strong>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff">
      <mj-column width=90%>
        <mj-text color=#f6893e padding-bottom=0px>
          <p style="font-family: Helvetica,Ariel,sans-serif; font-size:20px;">Hi (Name),</p>
          <p>We're making your order! We'll get in touch when we put your order in the mail!</p>
        </mj-text>
      </mj-column>
      <mj-column width=30%>
        <mj-text color=#000000 padding-bottom=0px padding-top=0px>
          <p style="font-family: Helvetica,Ariel,sans-serif; font-size:12px"><strong>Order Date:</strong> 10/22/2018</p>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section vertical-align="middle" background-color="#ffffff">
      <mj-raw>
        
      </mj-raw>
      <mj-column vertical-align="middle" width="30%">
        <mj-image padding="25px" align="left" mj-class="img-bordered" src="https://cdn.shopify.com/s/files/1/0269/7759/files/bow_tie-07_large.png?v=1540853250" alt="Bow Tie Image" width="150px"></mj-image>
      </mj-column>
      <mj-raw>
        
      </mj-raw>
      <mj-group vertical-align="middle" width="70%">
        <mj-column>
          <mj-text align="left"><strong>Nani Floral Bow Tie</strong><br />
            Standard/Light Blue<br />
            Quantity: 1</mj-text>
        </mj-column>
        <mj-raw>
          
        </mj-raw>
        <mj-column>
          <mj-text align="right"><strong>Price: $40.00</strong></mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
        <mj-section vertical-align="middle" background-color="#ffffff">
      <mj-raw>
        
      </mj-raw>
      <mj-column vertical-align="middle" width="30%">
        <mj-image padding="25px" align="left" mj-class="img-bordered" src="https://s13.postimg.org/r3otqmynn/shoes.png" alt="Brown shoes" width="150px"></mj-image>
      </mj-column>
      <mj-raw>
        
      </mj-raw>
      <mj-group vertical-align="middle" width="70%">
        <mj-column>
          <mj-text align="left"><strong>Brown shoes</strong><br />
            Size: 9.5<br />
            Quantity: 1</mj-text>
        </mj-column>
        <mj-raw>
          
        </mj-raw>
        <mj-column>
          <mj-text align="right"><strong>Price: $79.99</strong></mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
        <mj-section vertical-align="middle" background-color="#ffffff">
      <mj-raw>
        
      </mj-raw>
      <mj-column vertical-align="middle" width="30%">
        <mj-image padding="25px" align="left" mj-class="img-bordered" src="https://s13.postimg.org/r3otqmynn/shoes.png" alt="Brown shoes" width="150px"></mj-image>
      </mj-column>
      <mj-raw>
        
      </mj-raw>
      <mj-group vertical-align="middle" width="70%">
        <mj-column>
          <mj-text align="left"><strong>Brown shoes</strong><br />
            Size: 9.5<br />
            Quantity: 1</mj-text>
        </mj-column>
        <mj-raw>
          
        </mj-raw>
        <mj-column>
          <mj-text align="right"><strong>Price: $79.99</strong></mj-text>
        </mj-column>
      </mj-group>
    </mj-section>

    <mj-section background-color="#ffffff" padding-bottom="0px" padding-top="10px">
      <mj-column width=45%>
        <mj-text>
          <strong style="font-family: Helvetica,Ariel,sans-serif; font-size:12px">Shipping Address</strong>
          <hr style="border: 1px solid #f7bf40" />
          <p style="line-height: 1px; font-family: Helvetica,Ariel,sans-serif; font-size:12px">Kevin Gaertner</p>
          <p style="line-height: 1px;font-family: Helvetica,Ariel,sans-serif; font-size:12px">926 W 10th Ave</p>
          <p style="line-height: 1px;font-family: Helvetica,Ariel,sans-serif; font-size:12px">Denver, CO 80204</p>
          <p style="line-height: 1px;font-family: Helvetica,Ariel,sans-serif; font-size:12px">United States</p>
        </mj-text>
      </mj-column>
      <mj-column width=45%>
        <mj-text>
          <strong style="font-family: Helvetica,Ariel,sans-serif; font-size:12px">Billing Address</strong>
          <hr style="border: 1px solid #f7bf40" />
          <p style="line-height: 1px; font-family: Helvetica,Ariel,sans-serif; font-size:12px">Kevin Gaertner</p>
          <p style="line-height: 1px;font-family: Helvetica,Ariel,sans-serif; font-size:12px">926 W 10th Ave</p>
          <p style="line-height: 1px;font-family: Helvetica,Ariel,sans-serif; font-size:12px">Denver, CO 80204</p>
          <p style="line-height: 1px;font-family: Helvetica,Ariel,sans-serif; font-size:12px">United States</p>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff" padding-bottom="0px" padding-top="0">
      <mj-column>
        <mj-text align="center">
          <hr style="border: 1px solid #f7bf40" />
          <strong style="font-family: Impact,Ariel,sans-serif; font-size:25px; color:#607482; line-height:60px; letter-spacing:1px">WHILE YOU WAIT...</strong>
        </mj-text>
      </mj-column>
    </mj-section>
    <mj-section background-color="#ffffff" padding-bottom="20px" padding-top="0">
      <mj-column width=3%></mj-column>
      <mj-column width=30% background-color="#eeedee">
        <mj-text align=center padding-bottom=0px>
          <p style="font-family: Veranda,Ariel,sans-serif; font-size:15px; color:#fa8739">CURIOUS ABOUT OUR RETURN POLICY?</p>
        </mj-text>
        <mj-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/OrderConfirmation_FINAL-04_2fcf62de-8808-4637-934a-d11f529b548d_large.png?v=1540845996" alt="image of a shipping box with arrows around it" align="center" width="150px" padding-bottom="0px" padding-top="0px">
        </mj-image>
        <mj-text align=center padding-bottom=5px>
          <p style="color:#607482;font-family: Helvetica,Ariel,sans-serif; font-size:12px;">Click here to learn more!</p>
        </mj-text>
      </mj-column>
      <mj-column width=2%></mj-column>
      <mj-column width=30% background-color="#eeedee">
        <mj-text align=center padding-bottom=0px>
          <p style="font-family: Veranda,Ariel,sans-serif; font-size:15px; color:#fa8739">WANT TO CHECK YOUR ORDER STATUS?</p>
        </mj-text>
        <mj-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/OrderConfirmation_FINAL-05_d799af8a-7d23-4d24-83f3-f7d4c930425d_large.png?v=1540846003" alt="image of shipping box with magnifying glass" align="center" width="150px" padding-bottom="0px" padding-top="0px">
        </mj-image>
        <mj-text align=center padding-bottom=5px>
          <p style="color:#607482;font-family: Helvetica,Ariel,sans-serif; font-size:12px;">Click here to contact our team!</p>
        </mj-text>
      </mj-column>
      <mj-column width=2%></mj-column>
      <mj-column width=30% background-color="#eeedee">
        <mj-text align=center padding-bottom=0px>
          <p style="font-family: Veranda,Ariel,sans-serif; font-size:15px; color:#fa8739">NEED TO MAKE CHANGES TO YOUR ORDER?</p>
        </mj-text>
        <mj-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/OrderConfirmation_FINAL-06_large.png?v=1540846011" alt="image of a piece of paper with a pencil and arrows" align="center" width="150px" padding-bottom="0px" padding-top="0px">
        </mj-image>
        <mj-text align=center padding-bottom=5px>
          <p style="color:#607482;font-family: Helvetica,Ariel,sans-serif; font-size:12px;">Click here to learn how to do so!</p>
        </mj-text>
      </mj-column>
      <mj-column width=3%></mj-column>
    </mj-section>
    <mj-section background-color="#607482" padding-bottom="0px" padding-top="0">
      <mj-group>
        <mj-column padding-top=20px>
          <mj-image src="https://cdn.shopify.com/s/files/1/0269/7759/files/Submission_Recieved_Email_Final-02_large.png?v=1539807221" alt="question mark"></mj-image>
        </mj-column>
        <mj-column padding-bottom="10px">
          <mj-text padding-bottom=0px; padding-top=10px color=#fa8739>
            <p style="font-size:16px; font-family:Veranda,Arial,sans-serif;"><strong>Got Questions?</strong></p>
          </mj-text>
          <mj-text padding-top=0px>
            <p style="line-height: 16px; margin: 0px 0;font-size:12px; color:#ffffff; font-family:Helvetica,Arial,sans-serif">For questions on our design process, pricing, or turnaround, check out our <a style="color: #f7bf40; text-decoration: none" href="http://help.knottytie.com/">FAQ page</a></mj-imag>.
              To chat with our design team, email <a style="color:#f7bf40; text-decoration: none" href="mailto:team@knottytie.com">team@knottytie.com</a>.</p>
          </mj-text>
        </mj-column>
      </mj-group>
    </mj-section>
    <mj-section background-color="#e9e9ea">
      <mj-column width="15%">
        <mj-image align="center" src="http://cdn.shopify.com/s/files/1/0269/7759/files/Welcome-Twitter-Footer_large.png?v=1539726625" href="https://twitter.com/KnottyTie" alt="Twitter" target="_blank" width="75px"></mj-image>
      </mj-column>
      <mj-column width="15%">
        <mj-image align="center" src="http://cdn.shopify.com/s/files/1/0269/7759/files/Welcome-Facebook-Footer_b5696815-4058-48cb-a0a9-de4b2692225d_large.png?v=1539726613" href="https://www.facebook.com/KnottyTie/" alt="Facebook" target="_blank" width="75px"></mj-image>
      </mj-column>
      <mj-column width="15%">
        <mj-image align="center" src="http://cdn.shopify.com/s/files/1/0269/7759/files/Welcome-Instagram-Footer_large.png?v=1539726619" href="https://www.instagram.com/knottytie/" alt="Instagram" target="_blank" width="75px"></mj-image>
      </mj-column>
    </mj-section>
    <mj-section padding="0px">
      <mj-column>
        <mj-image align="center" padding-top="0px" padding-bottom="20px" src="https://cdn.shopify.com/s/files/1/0269/7759/files/Welcome-Knotty-Logo-Footer_large.png?v=1539727475" alt="Knotty Logo, Made in Colorado, Recycling Sign" target="_blank" width="200px"></mj-image>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>

**Comment by ngarnier** [comment] 2018-10-31 15:59
Hey @DanyeWest, 

There is a lot of issues in your markup, you're missing quotes around many attributes (see the yellow warnings here: https://mjml.io/try-it-live/B1mUyUD2m). 

The text is wrapping simply because there's not enough space to display it inline. Set a width on each column and it should work fine (see https://mjml.io/try-it-live/B1mUyUD2m also). 

I'm closing as I think it solves your issue but feel free to reopen if it's not the case.

**Closed by ngarnier** 2018-10-31 15:59 UTC
