### ISSUE TITLE
Display image inline block

### ISSUE THREAD

**Issue by mdrick** [mjmlio/mjml#223] opened 2016-05-04 09:37 UTC
Hi,

I have a question. 

I don't succeed to display image in inline-block with mj-image tag.

Can I have some help please ?

**Comment by iRyusa** [comment] 2016-05-04 10:15
Hello @mdrick 
What do you want to achieve ? Looks like you want to do a 2 column layout. Such as : 
```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
         <mj-column>
           <mj-image ... />
         </mj-column>
         <mj-column>
            <mj-text ... /> 
         </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>

**Comment by younes0** [comment] 2016-05-04 11:50
I think that @mdrick means something like that:
![image](https://cloud.githubusercontent.com/assets/886042/15013288/03e8e5c6-11ff-11e6-9bd7-c348f41b098f.png)
I'm also interested in knowing how please

**Comment by lohek** [comment] 2016-05-04 11:57
You can try this

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
         <mj-column>
           <mj-text>
             <img src="http://puu.sh/oFRKF/fe5c62d40a.png" /> Hello
           </mj-text>
         </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
![](http://puu.sh/oFRQI/5a56e343f8.png)

It's not perfect, but it's a start solution

**Comment by younes0** [comment] 2016-05-04 12:02
@lohek Thanks, got it. I thought that HTML elements were forbidden in the MJML markup :) 
Next I have to play with vertical-align, not sure that it's well supported in email clients.

There's also this solution: 
> Use padding-top, and padding-bottom with a negative value.
source: http://stackoverflow.com/questions/16926941/valign-not-working-in-outlook-html-emails

**Comment by lohek** [comment] 2016-05-04 12:44
And this ?

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
         <mj-column>
           <mj-table>
             <tr>
               <td style="width: 38px;">
                 <img src="http://puu.sh/oFRKF/fe5c62d40a.png" />
               </td>
               <td>
                 Hello
               </td>
             </tr>
           </mj-table>
         </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

![](http://puu.sh/oFTVN/d8eefe59ff.png)

**Comment by lohek** [comment] 2016-05-04 12:53
Mobile
![](http://puu.sh/oFUfn/4f3d8e656a.png)

Desktop
![](http://puu.sh/oFUg7/3617a98dce.png)

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>
            <h1>
              Best email ever
            </h1>
          </mj-text>
          <mj-image src="http://191n.mj.am/img/191n/3s/xxr.png" />
        </mj-column>
      </mj-section>
      <mj-section>
         <mj-column>
            <mj-table>
              <tr>
                <td width="15%">
                  <img src="http://puu.sh/oFRKF/fe5c62d40a.png" />
                </td>
                <td width="35%">
                  Hello 1
                </td>
                <td width="15%">
                  <img src="http://puu.sh/oFRKF/fe5c62d40a.png" />
                </td>
                <td width="35%">
                  Hello 2
                </td>
              </tr>
            </mj-table>
            <mj-text>
              You've got a mail
            </mj-text>
         </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-divider />
          <mj-text>
            Such w0w
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
Maybe you can use pixel width for column (but beware for responsive)

**Comment by younes0** [comment] 2016-05-04 12:56
@lohek Yes it's vertical-aligned now!, my only concern is that I didn't manage to align right the second TD. I'd like to achieve this: 
![image](https://cloud.githubusercontent.com/assets/886042/15014783/430ab9ec-1208-11e6-9a81-d04a59c7f5fc.png)

**Comment by younes0** [comment] 2016-05-04 12:58
OKay I succeded by doing this:
```xml
      <!-- header -->
      <mj-section padding-bottom="0">
        <mj-column>
           <mj-image padding-left="0" width="120" align="left" src="http://www.mylogo.com/" />
        </mj-column>

        <mj-column> 
      <mj-table padding-top="25px" align="right" padding="0">
             <tr align="right">
               <td>
                 <img src="http://www.mylogo.com/" width="14px" />
               </td>
               <td width="150px">
                 Allo: 04 67 XX XX XX 
               </td>
             </tr>
           </mj-table>
        </mj-column>
      </mj-section>

**Comment by lohek** [comment] 2016-05-04 13:02
A little more tricky... but :

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>
            <h1>
              Best email ever
            </h1>
          </mj-text>
          <mj-image src="http://191n.mj.am/img/191n/3s/xxr.png" />
        </mj-column>
      </mj-section>
      <mj-section>
         <mj-column>
            <mj-table>
              <tr>
                <td width="50%" align="left">
                  <table>
                    <tr>
                      <td width="15%">
                        <img src="http://puu.sh/oFRKF/fe5c62d40a.png" />
                      </td>
                      <td width="35%">
                        Hello 1
                      </td>
                    </tr>
                  </table>
                </td>
                <td width="50%" align="right">
                  <table>
                    <tr>
                      <td width="15%">
                        <img src="http://puu.sh/oFRKF/fe5c62d40a.png" />
                      </td>
                      <td width="35%">
                        Hello 2
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </mj-table>
            <mj-text>
              You've got a mail
            </mj-text>
         </mj-column>
      </mj-section>
      <mj-section>
        <mj-column>
          <mj-divider />
          <mj-text>
            Such w0w
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by younes0** [comment] 2016-05-04 13:06
this seems like a a good candidate for a new component, will try to PR

**Comment by arnaudbreton** [comment] 2016-05-06 12:33
Thanks @younes0 for your contribution! Until you open a PR, I'm closing this issue which looks solved to me. Feel free to reopen if something is still missing to you.

**Closed by arnaudbreton** 2016-05-06 12:33 UTC

**Comment by younes0** [comment] 2016-05-09 13:42
I ended up using `mj-social` since the above solutions were not as we expected on some devices/clients. A `mj-social` `icon-url` instead of `base-url` parameter would be a nice addition

**Comment by talarari** [comment] 2017-05-18 13:27
i need to do the same thing, basically show a text and an icon right next to it.
what's the current recommended way of achieving this?
using mj-social feels really hacky, also i need the icon to be on the right of the text not the left.
thanks!

**Comment by ngarnier** [comment] 2017-05-18 13:34
Hey @talarari, can you explain more in details your need? A mockup/design would help.

Also, feel free to create your own issue for assistance as this one is >1 year old.

**Comment by SPChristopher** [comment] 2019-09-16 21:24
If you want to take advantage of the functionality of mjml and save code, try this.

<mj-social>
          <mj-social-element color="#fff" src="assets/telefono.png">
            <span>(01)500 0000</span>
          </mj-social-element>

          <mj-social-element color="#fff" src="assets/whatsapp.png">
            <span>977 822 185</span>
          </mj-social-element>
        </mj-social>

**Comment by tpoussard** [comment] 2020-07-01 13:45
Hye there,
I red in the documentation that it's possible to make the mj-social not clickable by not adding an href attribute, but the html generated still contain <a> element that display pointer on hover and have redirection. Any idea how to make mj-social element not clickable ?

**Comment by iRyusa** [comment] 2020-07-01 14:12
I can't really reproduce https://mjml.io/try-it-live/rkoVuzqRL ?

**Comment by tpoussard** [comment] 2020-07-01 15:00
Indeed, when I paste your code inside my local code, it becomes clickable and in reverse, when I paste my code inside this codepen, it becomes not clickable ...

**Comment by iRyusa** [comment] 2020-07-01 15:07
Maybe you have an old mjml version ?

**Comment by tpoussard** [comment] 2020-07-01 16:16
I'm using the vscode extension and you're right, it uses mjml 4.2.0 and in the releases, I've seen that the feature i'm seeking was released with the version 4.5.0.
Thanks a lot for your help !

**Comment by iRyusa** [comment] 2020-07-01 16:41
You might want to switch to our fork then

**Comment by shanjai7** [comment] 2021-03-30 10:47
Guys, I would want to use an image in the MJML email template that I am creating. I am using the image as a Link that is hosted on AWS. But the image does not seem to be working and it does not show the image. Could anyone help me with this?

**Comment by iRyusa** [comment] 2021-03-30 11:07
No so much we can do without code here. MJML rely on standard html  img tag
so most likely an issue not related with mjml

**Comment by moojen** [comment] 2021-11-17 11:47
It is related to the way MJML handles multiple images next to each other (using MJML version 4.8.1 in the macos app v3.0.3). I'm experiencing the same when adding multiple images and adding a css-class which has only display:"inline-block".
When adding a <mj-social> block, all is transformed into one table. But when adding several images in one column, all images are placed in one big table and for each image, a row and within that row the image placed in a separate table. This of course blocks you from using the inline-block.

**Comment by alex-pobeditel-2004** [comment] 2022-07-12 17:59
@SPChristopher your solution is truly genious! So clean and customizable! Saved a lot of time for me, thanks! =)
