### ISSUE TITLE
extra column when you type html comment in <mj-group>

### ISSUE THREAD

**Issue by xunuo** [mjmlio/mjml#1621] opened 2019-06-18 09:44 UTC
**Describe the bug**
extra column when you type html comment in `<mj-group>`

**To Reproduce**

```
<mj-group>
  <!-- foreach($n){ -->
  <mj-column>
    ....
  </mj-column>
  <!-- } -->
  <mj-column>
    ....
  </mj-column>
</mj-group>
```

will build 4 columns, and for each width will be 16%

**Expected behavior**
only 2 column

**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.2.0

**Comment by iRyusa** [comment] 2019-06-18 10:09
Hi,

I think this is fixed in 4.3.X https://mjml.io/try-it-live/r1vAwVU1r ? 

You should use `mj-raw` for that instead of using html comment like that: 

```
<mj-group>
<mj-raw>foreach($n){ </mj-raw>
  <mj-column>
    ....
  </mj-column>
<mj-raw>}</mj-raw>
  <mj-column>
    ....
  </mj-column>
</mj-group>
```

**Comment by xunuo** [comment] 2019-06-18 15:37
> Hi,
> 
> I think this is fixed in 4.3.X https://mjml.io/try-it-live/r1vAwVU1r ?
> 
> You should use `mj-raw` for that instead of using html comment like that:
> 
> ```
> <mj-group>
> <mj-raw>foreach($n){ </mj-raw>
>   <mj-column>
>     ....
>   </mj-column>
> <mj-raw>}</mj-raw>
>   <mj-column>
>     ....
>   </mj-column>
> </mj-group>
> ```

thanks for answer, but it's not working...

![image](https://user-images.githubusercontent.com/698455/59698304-0d25aa80-91f8-11e9-889e-1caa1237080e.png)

**Comment by iRyusa** [comment] 2019-06-18 15:46
Oh you're right ! cc @kmcb777 maybe we can add this to 4.4, i think you just need to blacklist raw children ?

A temporary fix would be to define the width to 50% directly on both column inside mj-group !

**Comment by kmcb777** [comment] 2019-06-20 13:56
@iRyusa we already blacklisted raw children ✌️

@xunuo iRyusa is right on this point : you have to put any templating language in a mj-raw to keep it unchanged by mjml.
Concerning the extra column problem, i couldn't reproduce your issue, could you paste the full template you're using here plz ?
I tried with the part i can see on your screen shot, and i get the expected behavior : 
<img width="1640" alt="Screen Shot 2019-06-20 at 15 55 12" src="https://user-images.githubusercontent.com/8144509/59854796-dffe0700-9373-11e9-855c-d6ad05422b92.png">

**Comment by kmcb777** [comment] 2019-06-20 14:53
@xunuo Hi, thanks for reporting this, there was indeed a problem 👍
It will be fixed in the next release

Raw elements were correctly ignored in mj-section but not in mj-group

**Comment by xunuo** [comment] 2019-06-26 13:38
> @xunuo Hi, thanks for reporting this, there was indeed a problem 👍
> It will be fixed in the next release
> 
> Raw elements were correctly ignored in mj-section but not in mj-group

Thanks!!! look forward it!

**Comment by xunuo** [comment] 2019-06-27 13:28
@kmcb777 hello, could we use the new version now, we have a project need it :)

**Comment by xunuo** [comment] 2019-06-27 13:30
how to use the newest version :)

**Comment by iRyusa** [comment] 2019-06-27 13:53
This has not been released yet, it should be available soon. As a temporary fix just fix the column width to `50%` manually in the group

**Comment by kmcb777** [comment] 2019-07-02 17:35
Hi @xunuo , new version has been released, you can check if this problem is fixed. Still in beta so you need to install with the tag `mjml@next`

**Closed** 2019-07-17 15:41 UTC
