### ISSUE TITLE
Bug in mj-image width? #144

### ISSUE THREAD

**Issue by manu2195** [mjmlio/mjml#1038] opened 2018-03-09 06:40 UTC
Hi, I am experiencing the same problem now again.
Setting the width of mj-image in pixels, it is putting 100% width on the surrounding td and the image tag, which leads to the scaling of image with respect to column.

Mjml version used: 3.3.5

**Comment by ngarnier** [comment] 2018-03-09 08:43
It is VERY hard to help you without more details. When you create an issue, there is a template providing the things we need to help you (it's quite obvious, but one is the MJML code causing the issue). Help us help you, please use it.

Anyway, if the issue is within MJML v3.3.5, we won't fix it as MJML v4 was released. Please upgrade your MJML version.

**Closed by ngarnier** 2018-03-09 08:43 UTC
