### ISSUE TITLE
href links with variable is possible?

### ISSUE THREAD

**Issue by sinsunsan** [mjmlio/mjml#893] opened 2017-11-26 09:02 UTC
I am struggling to make dynamic link with variable. 
Don't seem possible? (Would be an important limitation)
````
<mj-inline-links base-url="https://mjml.io">
            <mj-link href="{{var:firstPath}}">{{var:firstPathName}}</mj-link>
            <mj-link href="/documentation">Documentation</mj-link>
          </mj-inline-links>
````

**Comment by sinsunsan** [comment] 2017-11-26 09:02
The result is `{{var:firstPath}}` being stringified but not evaluated

**Comment by iRyusa** [comment] 2017-11-27 08:26
Hi @sinsunsan 

This is a duplicate of https://github.com/mjmlio/mjml/issues/410#issuecomment-346861140 so here's the link to the related issue. 

I'm closing this one, the other one will be updated when MJML 4 is out from alpha

**Closed by iRyusa** 2017-11-27 08:26 UTC

**Comment by sinsunsan** [comment] 2017-11-27 09:47
Hi @iRyusa 

Not sure it is the same problem. As in the issue you mentioned  it seems to be a php $ problem.

My problem is when sending emails giving only a templateId of a mailjet transactional templates. 
I am unable to use the variable `{{var:customUrl:'http://www.default.url"}}`in an html attributes, and the attribute I would like to use is href so that I can set an url dynamically. 
So `<a href="{{var:customUrl:'http://www.default.url"}}">` do not works

I could of course compile the template in my server,  but I liked to be able to do it in mailjet. 

Thanks

**Comment by iRyusa** [comment] 2017-11-27 09:49
Did you check that `{{` aren't encoded in the outputted html ?

**Comment by dalefish** [comment] 2017-11-27 09:57
There's a quote mismatch in that variable. Might not be the issue in
question but should be fixed to eliminate it as a possible cause.

Change:

{{var:customUrl:'http://www.default.url"}} | <a href="{{var:customUrl:'
http://www.default.url"}}">

Into:

{{var:customUrl:'http://www.default.url'}} | <a href="{{var:customUrl:'
http://www.default.url'}}">

Might not help, but might do

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by sinsunsan** [comment] 2017-12-01 10:56
I will compare a MJML   version made with you WYSIWYG with variable in the attribute like href, and my version to track down the problem. 
If I fix it I will put it here.

**Comment by torcelly** [comment] 2018-01-14 02:48
Did you fix it? Thanks

**Comment by sinsunsan** [comment] 2018-01-14 06:24
Sorry I found the same bug with a copy of of html procuded by the WYSIWYG... But not at all time, it was quite irregular.
And did not want to spend to much time. Also I felt that there is no way to share part of  a template with your online template editor between multiple template

So I decided to get back to my old technic compiling the template in my node.js backend that allows more flexibility and sharing the HEAD of all email + header and footer which is essential for me as it defines all layout.

**Comment by torcelly** [comment] 2018-01-14 09:29
Thanks for the response. I was testing @dalefish approach and finally, it works. I wrote:

`<mj-button href="{{var:urlscheme:''}}">
            Reset Your Password
</mj-button>`

**Comment by lgrdHenoc** [comment] 2020-10-02 08:28
I've got an error when i send my mail...

expression parsing error ## Unknown identifier: services' ## near ## {{var:url:'https://www.google.fr/' ##

**Comment by ngarnier** [comment] 2020-10-02 14:56
@lgrdHenoc this issue has been closed for 2 years plus your problem isn't even related to MJML but to Mailjet. Please open a support ticket from your Mailjet account.

**Comment by MukeshKumarBagaria** [comment] 2023-07-25 11:48
<mj-button href={{customUrl}} title="Verify Account">Verify Account</mj-button> 
 
 and then in your templateData just pass the customUrl it works for me
