### ISSUE TITLE
Image are not fully render on outlook 2013

### ISSUE THREAD

**Issue by mmativ** [mjmlio/mjml#867] opened 2017-11-03 05:18 UTC
Hi, i test this template [onepage](https://mjml.io/try-it-live/templates/onepage) into putsmail and check into my outlook 2013 and i got this issue, same issue with my template, the image render only 10%-20% of the height.

![image](https://user-images.githubusercontent.com/15825968/32361251-74d38c88-c099-11e7-8a13-08843c5a956a.png)

Its totally weird.

**Comment by dalefish** [comment] 2017-11-03 07:00
That's normal for outlook. Increasing line-height should fix it.

**Comment by mmativ** [comment] 2017-11-03 07:02
@dalefish you mean line-height for image?

**Comment by dalefish** [comment] 2017-11-03 07:04
Hard to tell exactly where in your case, tr, TD, mj-image possibly the
section too. Depends how it's put together.

**Comment by ngarnier** [comment] 2017-11-03 08:24
Hey @mmativ, did you do any change to the template? I just tried in the builder + via putsmail on a Litmus checklist and I can't reproduce: https://litmus.com/checklist/emails/public/f3baafc

**Comment by mmativ** [comment] 2017-11-03 09:41
@ngarnier i d'dint chance any code on that template, and i forgot if i check the 

> Move my CSS inline when I click Send Email (for best results in Gmail and Outlook)

on putsmail, after that i just follow this advise, and my image render properly.
https://www.campaignmonitor.com/forums/topic/7376/view/page/2/
![image](https://user-images.githubusercontent.com/15825968/32367710-03c20900-c0be-11e7-9e01-2f72b8f4c71e.png)

**Comment by iRyusa** [comment] 2017-11-07 15:28
Well as we can't reproduce the issue ( see @ngarnier comment ) i'm closing this issue feel free to reopen if you got step to reproduce

**Closed by iRyusa** 2017-11-07 15:28 UTC
