### ISSUE TITLE
Padding on mobile stacked columns with images

### ISSUE THREAD

**Issue by vicmunez85** [mjmlio/mjml#1162] opened 2018-04-24 18:59 UTC
Hey All, I know this was discussed before(https://github.com/mjmlio/mjml/issues/630, https://github.com/mjmlio/mjml/issues/263), but i haven't been able to find a solution.. 

Is there a way to remove padding or gutter from mobile stacked columns with images?

Desktop Version Screenshot:
https://imghost.io/images/2018/04/24/Desktop.jpg

Mobile Version Screenshot:
https://imghost.io/images/2018/04/24/Mobile.jpg

I'm using the MJML App v2.9.0.

**Comment by ngarnier** [comment] 2018-04-25 07:59
Hey @vicmunez85, the issue is not really about a padding, but rather that the image keeps its desktop size in the mobile version (instead of going full-width). 

We'll release a new feature in v4.1.0 to support images going full-width on mobile, so I'll close this one in favour of #263.

**Closed by ngarnier** 2018-04-25 07:59 UTC
