### ISSUE TITLE
2 columns completely broken on Live Mail, Outlook 2003 and Lotus Notes

### ISSUE THREAD

**Issue by Tlapi** [mjmlio/mjml#312] opened 2016-06-22 07:59 UTC
E-mail is completely broken when using two columns layout on these e-mail client. I did quite few tests and it seems there really is an issue.

EOA test: https://www.emailonacid.com/app/acidtest/display/summary/UD9mEHCwhYmoiLWE3EBHtc2XazyvB46MpLSEGP4LaFlNB/shared

MJML:

```
<mjml>
    <mj-body>
        <mj-container background-color="#f0f0f0">
            <mj-section padding="0px" background-color="#ffffff">
                <mj-column width="50%">
                    <mj-image src="https://ecomail-accounts.s3-eu-west-1.amazonaws.com/jan/2016/Jun/Wed/1466012577."></mj-image>
                </mj-column>
                <mj-column width="50%">
                    <mj-image src="https://ecomail-accounts.s3-eu-west-1.amazonaws.com/jan/2016/Jun/Wed/1466012577."></mj-image>
                </mj-column>
            </mj-section>
        </mj-container>
    </mj-body>
</mjml>
```

Generated HTML:

```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title></title>
  <style type="text/css">
    #outlook a {
      padding: 0;
    }

    .ReadMsgBody {
      width: 100%;
    }

    .ExternalClass {
      width: 100%;
    }

    .ExternalClass * {
      line-height: 100%;
    }

    body {
      margin: 0;
      padding: 0;
      -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
    }

    table,
    td {
      border-collapse: collapse;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
    }

    img {
      border: 0;
      height: auto;
      line-height: 100%;
      outline: none;
      text-decoration: none;
      -ms-interpolation-mode: bicubic;
    }

    p {
      display: block;
      margin: 13px 0;
    }
  </style>
  <!--[if !mso]><!-->
  <style type="text/css">
    @media only screen and (max-width:480px) {
      @-ms-viewport {
        width: 320px;
      }
      @viewport {
        width: 320px;
      }
    }
  </style>
  <!--<![endif]-->
  <!--[if mso]>
<xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml>
<![endif]-->
  <style type="text/css">
    @media only screen and (min-width:480px) {
      .mj-column-per-50,
      * [aria-labelledby="mj-column-per-50"] {
        width: 50%!important;
      }
    }
  </style>
  <style type="text/css">
    @media only screen and (max-width:480px) {
      .mj-hero-content {
        width: 100% !important;
      }
    }
  </style>
</head>

<body style="background: #f0f0f0;">
  <div style="background-color:#f0f0f0;">
    <!--[if mso | IE]>
      <table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;">
        <tr>
          <td style="line-height:0px;font-size:0px;mso-line-height-rule:exactly;">
      <![endif]-->
    <div style="margin:0 auto;max-width:600px;background:#ffffff;">
      <table cellpadding="0" cellspacing="0" style="font-size:0px;width:100%;background:#ffffff;" align="center" border="0">
        <tbody>
          <tr>
            <td style="text-align:center;vertical-align:top;font-size:0px;padding:0px;">
              <!--[if mso | IE]>
      <table border="0" cellpadding="0" cellspacing="0"><tr><td style="vertical-align:top;width:300px;">
      <![endif]-->
              <div aria-labelledby="mj-column-per-50" class="mj-column-per-50" style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;width:100%;">
                <table cellpadding="0" cellspacing="0" width="100%" border="0">
                  <tbody>
                    <tr>
                      <td style="word-break:break-word;font-size:0px;padding:10px 25px;" align="center">
                        <table cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px;" align="center" border="0">
                          <tbody>
                            <tr>
                              <td style="width:250px;"><img alt="" height="auto" src="https://ecomail-accounts.s3-eu-west-1.amazonaws.com/jan/2016/Jun/Wed/1466012577." style="border:none;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="250"></td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!--[if mso | IE]>
      </td><td style="vertical-align:top;width:300px;">
      <![endif]-->
              <div aria-labelledby="mj-column-per-50" class="mj-column-per-50" style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;width:100%;">
                <table cellpadding="0" cellspacing="0" width="100%" border="0">
                  <tbody>
                    <tr>
                      <td style="word-break:break-word;font-size:0px;padding:10px 25px;" align="center">
                        <table cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px;" align="center" border="0">
                          <tbody>
                            <tr>
                              <td style="width:250px;"><img alt="" height="auto" src="https://ecomail-accounts.s3-eu-west-1.amazonaws.com/jan/2016/Jun/Wed/1466012577." style="border:none;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="250"></td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <!--[if mso | IE]>
      </td></tr></table>
      <![endif]-->
  </div>
</body>

</html>
```

**Comment by iRyusa** [comment] 2016-06-27 13:59
Hi,

From what I test we can reproduce with a simple two column text too. I have no how this happen. If someone has any clue of what's going on with Outlook 2003 feel free to help

**Comment by zrb0529** [comment] 2016-06-29 12:20
I'm not seeing an issue in Outlook 2003: http://screencast.com/t/6Xv0lJX1GWm

**Comment by Tlapi** [comment] 2016-06-29 12:22
@zrb0529 Try provided mjml

**Comment by zrb0529** [comment] 2016-06-29 13:09
It seems the issue is with Outlook 2003 (and perhaps other) having a dislike for % width on images. Change the width: 100% to width: 200px and the issue is resolved on these clients though it may (**read: almost certainly will**) cause rendering issues elsewhere without further hand tuning.

**Comment by iRyusa** [comment] 2016-08-09 16:09
Anyone tried with an image that match the column `width` ? cc @Tlapi

**Comment by Lea-lynx** [comment] 2016-08-24 14:20
Just so you know the only workaround that i have found it's to remove the `width:100%` in ouput html.

![capture d ecran 2016-08-24 a 16 17 38](https://cloud.githubusercontent.com/assets/11275402/17933992/7f140644-6a16-11e6-9e7e-b10953c715c1.png)

Then the elements will be next to each others and still have a nice display on mobile.

**Comment by iRyusa** [comment] 2016-08-24 14:27
Removing `width: 100%` isn't a valid option, it will completely remove Gmail Android compatibility

**Comment by Lea-lynx** [comment] 2016-08-24 14:31
Well i have tested on android and ios and it worked ...weird

**Comment by Lea-lynx** [comment] 2016-08-24 14:33
i'll do more test (already test on desktop gmail / outlook / yahoo and gmail mobile ios and android since it's the most hard to render) but for the moment it's seemed the best option.

**Comment by iRyusa** [comment] 2016-08-24 14:37
Removing `width: 100%` will affect every mobile version, column will not stack anymore. Since the media queries are applied in gmail & yahoo `width: 100%` isn't an issue for them.

**Comment by Lea-lynx** [comment] 2016-08-24 14:37
Ok. I'll try other options thanks

**Comment by Tlapi** [comment] 2016-09-12 19:56
@iRyusa I have a solution. Replacing ```width:100%``` with ```min-width:100%``` works well as this gets ignored by desktop Outlook.

See here: https://www.emailonacid.com/app/acidtest/display/summary/W0H5VPu6THI3ThH28FRozjCP2OvHpQnifWL2CYnhd1mJY/shared

Pretty easy, right?

**Comment by dalefish** [comment] 2016-09-12 19:57
How does that test in everything else?

**Comment by Tlapi** [comment] 2016-09-12 19:59
@dalefish You can see the test here: https://www.emailonacid.com/app/acidtest/display/summary/W0H5VPu6THI3ThH28FRozjCP2OvHpQnifWL2CYnhd1mJY/shared

**Comment by iRyusa** [comment] 2016-09-12 20:04
Well if it that's simple it's cool but there's much more to test than a simple 2 image column imo

**Comment by dalefish** [comment] 2016-09-12 20:07
Progress in outlook.com though, it's a start

**Comment by Tlapi** [comment] 2016-09-12 20:09
Sure, there is. 

But still, if you think about it, ```width:100%``` and ```min-width:100%``` is the same right? With the only difference that Outlook ignores ```min-width```

**Comment by iRyusa** [comment] 2017-07-12 14:42
From our testing, it comes from images native width being wider than the column. min-width (even if well supported) could lead to wrong behaviour in some clients from our testing template so I'm closing this.

Just resize the image to fit the column size to avoid this effect.

**Closed by iRyusa** 2017-07-12 14:42 UTC
Labels: Community help needed, Outlook issue, Render issue
