### ISSUE TITLE
Double hyphen within comment: <!--[if !mso]><!

### ISSUE THREAD

**Issue by michaelwittwer** [mjmlio/mjml#1894] opened 2020-05-04 14:32 UTC
**Describe the bug**
When generating html from mjml for a very simple template i get the error `Double hyphen within comment: <!--[if !mso]><!-- -->` by the parser. 

**To Reproduce**
1. Create a file with this MJML code:
```
<mjml>
    <mj-body>
        <mj-section>
            <mj-column>

                <mj-image width="100px" src="/assets/img/logo-small.png"></mj-image>

                <mj-divider border-color="#F45E43"></mj-divider>

                <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
```
2. Render it to HTML by doing 'mjml src/sample.mjml -o ./dist/sample.html'
3. Open the rendered HTML within IntelliJ (This is just the first few lines)
```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
  <title>
  </title>
  <!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--<![endif]-->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
```

**Expected behavior**
I would expect the code 
```
<!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--<![endif]-->
```
to be
```
<!--[if !mso]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<![endif]-->
```
**MJML environment (please complete the following information):**
 - OS: MacOS
 - MJML Version 4.6.2
 - MJML tool used MJML CLI

**Email sending environment(for rendering issues)**:
 - No E-Mail was sent it

**Comment by iRyusa** [comment] 2020-05-04 14:52
Duplicate of #1884 #1581

As said in those issues we're applying the fix described here https://www.emailonacid.com/blog/article/email-development/prevent-ie-edge-meta-tag-from-breaking-images-in-live-mail/

**Closed by iRyusa** 2020-05-04 14:52 UTC
