### ISSUE TITLE
Android sections create thin lines

### ISSUE THREAD

**Issue by Wizardsmegid** [mjmlio/mjml#1101] opened 2018-03-28 14:31 UTC
Android seems to put small gaps between sections resulting in thin outlines. 

If I observed correctly, the problem is visible, when you set mj-body background-color to black and mj-section to white. That way you can see these line:
![image](https://user-images.githubusercontent.com/37873494/38035189-224eeaf2-32a4-11e8-9d5d-c81d78702e5d.png)

I expected there to be no gaps at all like every other mail client is rendering it.

MJML version 4.0.2

**Comment by iRyusa** [comment] 2018-03-28 14:39
Hi

Can you detail a bit, android version/client, MJML to reproduce/...

Thanks

**Comment by Wizardsmegid** [comment] 2018-03-28 15:21
Hey,
I can only confirm this issue on Sasmsung Android 5 and 6 (the only test possibilities we have) with their standard Email client.
`
<mj-body background-color="#000">
  <mj-section background-color="#fff" padding="0" padding-bottom="15px">
            <mj-column width="35%" css-class="mobile-hidden">
                <mj-image src="http://fakeimg.pl/150x100/" alt="FakeImage" padding="0 0 0 25px" />
            </mj-column>
            <mj-column width="65%" css-class="teaser-list-right">
                <mj-text padding="10px 25px 0 20px" color="#000" font-family="TodayLight, Arial" font-size="12pt" font-weight="400" line-height="12pt" text-transform="uppercase" align="left">
                    <span style="font-weight:600;color:#f99700">E-Commerce</span> - Januar 2018<br />
                    <br />
                    Vielleicht eine Messe, die der Kunde besuchen sollte&nbsp;&nbsp;<img src="https://www.medienwerft.de/showroom/mw-nl/nl_prototype/img/arrow_white.jpg" alt=">" style="height:11px;" />
                </mj-text>
            </mj-column>
        </mj-section>
        <mj-section background-color="#fff" padding="0" padding-bottom="15px">
            <mj-column width="35%" css-class="mobile-hidden">
                <mj-image src="http://fakeimg.pl/150x100/" alt="FakeImage" padding="0 0 0 25px" />
            </mj-column>
            <mj-column width="65%" css-class="teaser-list-right">
                <mj-text padding="10px 25px 0 20px" color="#000" font-family="TodayLight, Arial" font-size="12pt" font-weight="400" line-height="12pt" text-transform="uppercase" align="left">
                    <span style="font-weight:600;color:#f99700">Marketing</span> - Januar 2018<br />
                    <br />
                    Vielleicht ein Webinar, die der Kunde besuchen sollte&nbsp;&nbsp;<img src="https://www.medienwerft.de/showroom/mw-nl/nl_prototype/img/arrow_white.jpg" alt=">" style="height:11px;" />
                </mj-text>
            </mj-column>
        </mj-section>
</mj-body>
`

This should reproduce the issue showing on screen. I set the background-color of the body to black, because the main part of the mailing is black. Our creatives want these white areas in side of there.

**Comment by iRyusa** [comment] 2018-03-28 15:24
You have to use a triple backtick see here : https://guides.github.com/features/mastering-markdown/

Did you tried to minify the output before sending it ? How did you send the email ?

**Comment by Wizardsmegid** [comment] 2018-03-28 15:33
Nope, I just copy the whole generated html and paste it inside the Newsletter tool mailingwork.com. I'm not using their email creating options because that leads to other, much worse problems.
Mailingwork has a test option to screenshot your mailings on different email clients so you can see how they will appear. That's where I took the screenshot but I also confirmed the issue on actual devices.

**Comment by iRyusa** [comment] 2018-03-28 15:41
Does it do the same on MJML3.3.5 ? Is it a regression in MJML4 ?

Looks like minify doesn't do the trick here

**Comment by Wizardsmegid** [comment] 2018-03-28 15:43
Yes, I noticed the same issue with MJML3.3.3 already but I was waiting for 4 to be released. I hoped it would be gone magicaly :D

**Comment by iRyusa** [comment] 2018-03-28 15:52
Well, tried few things to debug but got no luck. Probably an issue with border collapse or something like that but got no luck yet

**Comment by mattlub** [comment] 2018-04-10 08:34
I was having a similar problem (in mjml 3) which was improved by adding top and bottom border to the sections.

So in your case, a white border.

**Comment by kmcb777** [comment] 2018-05-28 12:55
@Wizardsmegid A workaround for your situation would be to wrap your sections in a `<mj-wrapper background-color="white">` . This successfully gets rid of the grey lines.

I tried different solutions, and Android seems to render some kind of transition borders that depends on the background-color of the parent element. It can actually happen with any element (i.e. a white column inside a black section can have these same lines). Therefore any fix for this would require far too many modifications, and since the problem does come from Android, i'll close this issue. Feel free to reopen or PR if you came up with a better solution :)

**Closed by kmcb777** 2018-05-28 12:55 UTC
Labels: Help needed
