### ISSUE TITLE
(mj-inline-links)(mj-link) "href" attribute missing in documentation

### ISSUE THREAD

**Issue by mattez** [mjmlio/mjml#599] opened 2017-03-16 12:56 UTC
"href" is pretty important attribute. I'm missing more info about it in [documentation](https://mjml.io/documentation/#mjml-link).

Should be always relative to path defined in a parrent's (mj-inline-links) attribute _base-url_?
```html
<mj-inline-links base-url="https://mjml.io">
	<mj-link href="/components">Components</mj-link>
	<mj-link href="/documentation">Documentation</mj-link>
</mj-inline-links>
```
or there can be full URL also? (Empty _base-url_ must be preserved?)
```html
<mj-inline-links base-url="">
	<mj-link href="https://mjml.i/components">Components</mj-link>
	<mj-link href="https://github.com/mjmlio/">Github</mj-link>
</mj-inline-links>
```
Thanks in advance for clarification.

**Comment by ngarnier** [comment] 2017-03-16 13:03
Hi @mattez, it's not mentioned because you can use both, cf this example: https://mjml.io/try-it-live/Hyrd3busg

Cheers

**Comment by mattez** [comment] 2017-03-16 13:30
hi @ngarnier thank you for response.
When I want to use all links with "full url" like here https://mjml.io/try-it-live/Hy-eJM_se then I don't need _base-url_ attribute. So I deleted it and this triggers an error _MJML badly formatted_ - see this https://mjml.io/try-it-live/BJf6TW_se .
IMHO It's not intuitively expected behavior.

**Comment by ngarnier** [comment] 2017-03-16 13:44
Ha indeed, thanks for reporting! `base-url` should be set ton an empty url by default (see https://github.com/mjmlio/mjml/blob/master/packages/mjml-navbar/src/InlineLinks.js#L11), please use a dummy base-url in the meantime :-).

**Comment by mattez** [comment] 2017-03-16 15:34
And should be mentioned in documentation that _href_ attribute content of _mj-link_  is URL-encoded (url-safe) when redered. So my variable `{{myvariable}}` changed to this `%7B%7Bmyvariable%7D%7D` or `[[myvariable]]` to `%5B%5Bmyvariable%5D%5D`.
IMHO It's not intuitively expected behavior also.
Can I somehow turn URL-encoding off?

**Comment by iRyusa** [comment] 2017-03-16 15:52
Can you try with MJML 3.3 beta, it should be fixed ?

**Comment by mattez** [comment] 2017-03-16 16:16
Hi @iRyusa my setup is:
```bash
$ node -v
v7.5.0
$ mjml --version
3.3.0-beta.8
``` 
My MJML code is **_mj-inline-links_ empty _base-url_** ():
```html
...
<mj-inline-links base-url="">
	<mj-link href="{{linktest1}}">Test link 1</mj-link>
	<mj-link href="{{linktest2}}">Test link 2</mj-link>
</mj-inline-links>
...
```
and I run `$ mjml input.mjml -o content.html` it render
```html
...
<a href="%7B%7Blinktest1%7D%7D" style="...">Test link 1</a>
...
<a href="%7B%7Blinktest2%7D%7D" style="...">Test link 2</a>
...
```

**Comment by markclaxton** [comment] 2017-03-23 08:48
Is it possible to use images within the <mj-link></mj-link>

**Comment by mattez** [comment] 2017-03-24 08:13
@iRyusa so it is separate issue right? It more important then "missing in documentation".

It annoying. Every time I have to replace URLencoded Smarty variables back to original state.
(From this `%7B%7Blinktest1%7D%7D` to this `{{linktest1}}`.

Please help ;D

**Comment by iRyusa** [comment] 2017-10-17 15:19
So that's a duplicate of #664 now, I can close this one

**Closed by iRyusa** 2017-10-17 15:19 UTC
Labels: Bug, MJML 4
