### ISSUE TITLE
Extend core components

### ISSUE THREAD

**Issue by maximeparisse** [mjmlio/mjml#612] opened 2017-03-24 14:03 UTC
Hello.

I'm playing a bit with custom components but i have a little issue with it.

Let say i've created a custom component `<epic-section>`, that is the `<mjml-section>` base code with some modifications.

How can i tell to core components ( `<mjml-column>` for example ) it can now be in a parent `epic-section` and not only in `mj-section`, `mj-group` or `mj-navbar` ?

**Comment by iRyusa** [comment] 2017-03-24 14:13
Hi @maximeparisse !

Well, I have no real answer for that, did you try to import `mjml-column` and push your tagName it to `.parentTag` ? I think this could work.

In MJML4 this will be way easier to push new dependencies to the core, you'll be able to inject them with a simple API.

**Comment by maximeparisse** [comment] 2017-03-24 14:21
Hummm, thanks for the answer @iRyusa, i will try that even if i'm not really expert with jsx and react components.

By any chance, do you have an approximative release date for mjml4 ?

**Comment by iRyusa** [comment] 2017-03-27 12:26
Well we're working to get as many components ready to release a minimal beta with base components ( like section column image text divider ... ). So no date yet, but a beta should be available this month.

Directly in your components, you may have to add the package `mjml-column` to your package.json

**Comment by Laslo89** [comment] 2017-03-31 08:09
i have the same Problem:
<section>
  <custom-component>
    <mj-text>
      ...
    </mj-text>
  </custom-component>
</section>
is this supposed to be working? The Compiler tells me that it does not work by design:
> Line 111 (mj-text) — mj-text cannot be used inside robo-speechbouble, only inside: mj-column, mj-hero-content

Is there a update-save way to extend the parent-tag of a core comp?

**Comment by iRyusa** [comment] 2017-04-03 14:08
As said, dependencies are hard coded into components in MJML3. You can try to edit the MjText.parentTag @Laslo89 but I don't know if it works

Note that validation is completely and purely optional, your document will render fine in a `skip/soft` level.

In MJML 4 it will be completely different, components are independent and you'll have to define dependencies explicitely

**Comment by kmcb777** [comment] 2018-01-31 12:04
should be possible now with `mjml-validator/registerDependencies`

**Comment by iRyusa** [comment] 2018-02-07 17:29
👆 Closing the issue because it's available in the Beta. Feel free to reopen if you have any issue with it !

**Closed by iRyusa** 2018-02-07 17:29 UTC
Labels: Documentation, MJML 4
