### ISSUE TITLE
Output pure mjml after processing includes, for easy copy paste into try-it-live

### ISSUE THREAD

**Issue by martyzz1** [mjmlio/mjml#2556] opened 2022-10-03 11:26 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to test the mjml from my project in the try-it-live editor, without having to manually copy and paste individual "includes" into the editor piecemeal.

**Describe the solution you'd like**
add an option to the mjml cli call to say output-format=mjml

**Describe alternatives you've considered**
thought about doing a bash script, but it would be rubbish and clunky.

**Comment by nbouvrette** [comment] 2022-10-03 19:38
I've been playing with `mjml` for a few days now and I am seeing a lot of challenges around tooling. For example, there is a decent amount of dependency on the online tool to make this solution viable.

An alternative would be to send emails every time you make a modification which would be quite inefficient.

Now, since the tool doesn't come with templating capabilities, what happens when you start adding templating markup in your template... well the live editor reports all sorts of markup errors. At least this is what happens when you use EJS and I bet it would be the same if you use anything other than handlebars.

I'm still trying to wrap my head around what are good functionalities VS the ones you should avoid.. including files, for now, have been something I was trying to avoid for the reasons you are mentioning.

**Comment by iRyusa** [comment] 2022-10-03 19:45
We have everything to do so, someone need to open a PR on this
https://github.com/mjmlio/mjml/issues/2465#issuecomment-1109515536

**Comment by nbouvrette** [comment] 2022-10-04 17:07
@iRyusa it looks like this would solve the problem to put the content in the editor but did you think about how to merge back the edits into the individual files?

**Comment by iRyusa** [comment] 2022-10-04 17:19
There’s no way to do so easily.On 4 Oct 2022, at 19:07, Nicolas Bouvrette ***@***.***> wrote:﻿
@iRyusa it looks like this would solve the problem to put the content in the editor but did you think about how to merge back the edits into the individual files?

**Comment by nbouvrette** [comment] 2022-10-04 20:15
I agree... I was thinking of either:

- "[codesandbox](https://codesandbox.io/)"-alike editor where you have some sort of download option to get back your files. This would be a lot of work and possibly tricky to reproduce local paths to create packages...
- VSCode plugin where you can see the preview directly in VSCode, using your local environment - seems like a good option for developers. Not sure how much work it would be and this probably wouldn't be aligned with your (Mailjet) commercial goals for developing this tool.

**Comment by iRyusa** [comment] 2022-10-04 20:34
I'm not affiliated with Mailjet. Both project would require too much time
and effort.
Let's not deviate too much from original issue

**Comment by nbouvrette** [comment] 2022-10-04 22:12
I mean unless you have better ideas, I think it's a complex problem that would require a non-negligible investment. It's always easier to find time for this when it aligns with someone's business goals.

**Comment by iRyusa** [comment] 2022-10-04 22:31
There's enough creative way to tackle this today, and It's not the place to
discuss about it. If you want it, feel free to start build it, and ask for
help on MJML slack we'll provide as much as we can. https://parcel.io/ have
lot of tool around MJML that enhance the experience and might provide a way
better dev ex than any of our plugins.

**Comment by nbouvrette** [comment] 2022-10-04 22:37
I already have my own open source projects that I support for free so I can't tackle that kind of project. Having said this, if I had spare time I would probably invest it into proper Prettier support. I just ran into an issue where the content of my email was not showing up in gmail because I had a semicolon badly placed in my inline CSS. And with the current tools, this error was completely invisible which is kind of dangerous in my opinion.

**Comment by iRyusa** [comment] 2022-10-04 22:47
As said : this is not the place to talk about that, feedback are always
welcomed, but please use a proper issue/slack thread/...

**Comment by iRyusa** [comment] 2023-08-23 15:07
Closing for now feel free to open a PR about this

**Closed by iRyusa** 2023-08-23 15:07 UTC
