### ISSUE TITLE
Display bug image in gmail - width : NaN

### ISSUE THREAD

**Issue by Sarah-IFG** [mjmlio/mjml#539] opened 2017-02-06 15:01 UTC
Hi !

- MJML 3.2.0 - 
- try on litmus and gmail -
- bug on gmail (all browsers), gmail app (android) and inbox -

I have a problem with the display of the images in gmail. 
Currently, if you don't add manually a size of the image we have a width set with NaN value, while we have inside the style attribute width:100%
`<img alt="" title="" height="auto" src="http://cdn/my-image.jpg" style="border:none;border-radius:;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="NaN">`

The problem is fixed if I set the width on 100% value.

I think we can resolved this issue in two ways :
- either to add the ability to set the width of the `<mj-image>` with percent unit
- copy/link the value between style attribute and width

![capture d ecran 2017-02-06 a 15 49 36](https://cloud.githubusercontent.com/assets/12659073/22652160/af2fc916-ec85-11e6-9b86-ba262b2fb1a8.png)

**Comment by ngarnier** [comment] 2017-02-07 10:06
Hi @Sarah-IFG, thanks for reporting this issue. 

Unfortunately, I can't reproduce the issue with `NaN`, can you provide your MJML markup?

If I try to reproduce and don't add a width to my image, here is what my image styles look like: `<img alt="" title="" height="auto" src="/assets/img/logo-small.png" style="border:none;border-radius:;display:block;outline:none;text-decoration:none;width:100%;height:auto;" width="550">`

Example here: https://mjml.io/try-it-live/SkMkhzwOx

**Comment by Sarah-IFG** [comment] 2017-02-07 11:09
Hi, 
Trying to reproduce the bug, I understood that was my mistake... I put a section tag into an other section tag as `<mj-wrapper>` was not yet available. 

```
<mj-body>
  <mj-container background-color="#ff6f72">

    <mj-section>
      <mj-column width="95%" background-color="#ffffff" border-radius="15px">

        <!-- HEADER - round corner -->
        <mj-section border-radius="15px 15px 0 0" background-color="#ffe8d8" padding="0" >
          <mj-column >
            <mj-spacer height="25px"/>
          </mj-column>
        </mj-section>

        <!-- HEADER - img -->
        <mj-section padding="0">
          <mj-column>
            <mj-image src="/assets/img/logo-small.png" href="#" />
          </mj-column>
        </mj-section>

        ......

      </mj-column>
    </mj-section>
    
  </mj-container>
</mj-body>
```


Besides, I realized that we can't add a width value to the `<mj-wrapper>`. It would be very helpful to add this attribute.
In my case, it was to create gutter in mobile.
![capture d ecran 2017-02-07 a 11 50 18](https://cloud.githubusercontent.com/assets/12659073/22688713/c4093d9c-ed2d-11e6-9a6a-03a0f069977d.png)

**Comment by ngarnier** [comment] 2017-02-07 13:54
Indeed you nested columns and sections inside another column and section which might lead to issues.

In [MJML v3.3.0 (in beta now)](https://github.com/mjmlio/mjml/releases/tag/3.3.0-beta.3), you can use mj-wrapper.

Why not wrap your section in a wrapper and apply a padding on the image, like so: https://mjml.io/try-it-live/ByoqgIPOx

**Comment by Rouby** [comment] 2017-02-09 08:17
I had the same issue the other day, the image-element has no information about the parentWidth and thus `parseInt` returns NaN.

My image-element was nested in a custom component and I could fix it by re-applying the attributes of the custom component: `<Image {...mjmlAttrs} src={image} />`. I don't know if this is working-as-intended?

**Comment by Sarah-IFG** [comment] 2017-02-09 09:36
@ngarnier thanks but it is not the behavior I needed. I need to have gutter outside the wrapper not inside, I do not see how to do without being able to change the width of the wrapper.

**Comment by ngarnier** [comment] 2017-02-09 09:37
@Sarah-IFG Why not add the padding on the wrapper then? https://mjml.io/try-it-live/H1YEO2KOl

**Comment by iRyusa** [comment] 2017-02-09 12:57
@Rouby we're aware that deep nesting a component in a custom component misbehave, we're working on it

**Comment by iRyusa** [comment] 2017-03-28 15:29
Hi @Sarah-IFG !

i'm closing this one, if you're still having the issue feel free to reopen !

Note that you have to remove the padding left+right on your image width to avoid the overflow

**Closed by iRyusa** 2017-03-28 15:29 UTC
Labels: Discussion
