### ISSUE TITLE
Image width is not working with 2 columns (mobile breakpoint)

### ISSUE THREAD

**Issue by mcamprodon** [mjmlio/mjml#1256] opened 2018-06-26 14:13 UTC
Why in mobile version the image width can't be 100% if I use two columns?

```
<mjml>
  <mj-body>
    <mj-section>
        <mj-column>
          <mj-image src="https://fakeimg.pl/600x300/" href="#" />
        </mj-column>
        <mj-column>
          <mj-text font-weight="bold" align="left"><a href="#">Title</a></mj-text>
          <mj-text align="left">Summary</mj-text>
        </mj-column>
      </mj-section>
  </mj-body>
</mjml>
```

![2018-06-26 16_09_48-mjml](https://user-images.githubusercontent.com/2518620/41917982-a4d31ee6-795b-11e8-9407-3e22aff04542.png)

And with one column it's working fine:

```
<mjml>
  <mj-body>
    <mj-section>
        <mj-column>
          <mj-image src="https://fakeimg.pl/600x300/" href="#" />
          <mj-text font-weight="bold" align="left"><a href="#">Title</a></mj-text>
          <mj-text align="left">Summary</mj-text>
        </mj-column>
      </mj-section>
  </mj-body>
</mjml>
```

![2018-06-26 16_10_56-mjml](https://user-images.githubusercontent.com/2518620/41917987-aa38815a-795b-11e8-8eb3-265b693f2fd4.png)

**Comment by iRyusa** [comment] 2018-06-26 14:55
Hi @mcamprodon 

Well, the issue is older outlook like 2000-2003 doesn't behave properly with a fixed width for an image. So we have to fix (by default) the image width with column size minus paddig left/right.

So on mobile, the image won't go full-width. Everything is explained here : #263 

We're introducing a new attributes that use a media query for mobile version to scale up to 100% (so mobile client has to support media queries in order to have the image in full-width). This is the best compromise we've found yet without breaking any major client in our compatibility list.

I'm closing this one because it's a duplicate of #263

**Closed by iRyusa** 2018-06-26 14:55 UTC

**Comment by kmcb777** [comment] 2018-06-26 15:19
Hi @mcamprodon note that mj-image has a default padding, if you set `padding="0px"` on your mj-image it will be larger, and with the `fluid-on-mobile` attribute introduced un 4.1 beta it will really be 100%

**Comment by mcamprodon** [comment] 2018-06-26 15:29
Thanks @kmcb777 ! It's possible to run 4.1 beta with mjml-app?

**Comment by kmcb777** [comment] 2018-06-26 16:03
@mcamprodon not really, the only way would be to rebuild it from the source, but when 4.1 is released there will be an app release

**Comment by iRyusa** [comment] 2018-06-26 16:04
You can provide an external folder with an MJML install but it hasn't been tested yet I think
