### ISSUE TITLE
Thunderbird and web emial clients open always mobile version

### ISSUE THREAD

**Issue by zertex** [mjmlio/mjml#2077] opened 2020-11-05 19:35 UTC
Thunderbird and web emial clients open always mobile version

**To Reproduce**
1. Create new project from any template
2. Send email

**MJML environment (please complete the following information):**
 - OS: Windows 10
 - MJML Version LAST
 - MJML App LAST

**Email sending environment(for rendering issues)**:
 - mailjet

**Affected email clients (for rendering issues):**
 - Thunderbird, mail.ru
 - OS: Windows 10
 - Firefox

**Screenshots**
![111](https://user-images.githubusercontent.com/6353201/98287969-2f6bc400-1fb7-11eb-80e1-23f91c64fc9c.png)

**Comment by iRyusa** [comment] 2020-11-05 19:39
Duplicate of #2068 i'm closing.

**Closed by iRyusa** 2020-11-05 19:39 UTC
