### ISSUE TITLE
MJML and macOS Monterey not working

### ISSUE THREAD

**Issue by ghost** [mjmlio/mjml#2597] opened 2022-12-06 15:02 UTC
**Describe the bug**
Since updating my macOS from Catalina to Monterey, MJML has been incredibly slow to use. 

**To Reproduce**
Opening MJML, takes a long time to load all templates. Once I click on one, it loads fine and I can work on the code, but when I go back to the main screen, it takes around 45 seconds to load and has made using the platform very frustrating and slow. 

**Expected behavior**
Normal performance like before on Catalina

**MJML environment (please complete the following information):**
- macOS Monterey
 - MJML Version 3.0.2
 - MJML App

**Comment by iRyusa** [comment] 2022-12-06 15:27
Duplicate of #2584 

Still no luck on reproducing this with a fresh setup on our end.

**Closed as not planned by iRyusa** 2022-12-06 15:27 UTC

**Comment by iRyusa** [comment] 2022-12-06 15:51
Locking here, more details needed to help identify what can be the root cause of this.
