### ISSUE TITLE
&nbsp; is replaced with space

### ISSUE THREAD

**Issue by jsit** [mjmlio/mjml#37] opened 2016-02-09 21:42 UTC
`&nbsp;` entities seem to get stripped and replaced with a space when rendering html.

If I wrap it in `<mj-raw>`, the space disappears entirely.

**Comment by iRyusa** [comment] 2016-02-10 10:04
Hello there,

I can't reproduce here, can you provide your mjml please ?

mjml:
```xml
<mj-body>
    <mj-section>
      <mj-column>
        <mj-text>Hello &nbsp; !</mj-text>
        <mj-raw>Hello &nbsp; !</mj-raw>
      </mj-column>
    </mj-section>
  </mj-body>
```

output:
```sh
➜  mjml git:(master) ✗ ./node_modules/.bin/babel-node ./test.js
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title></title>
  <style type="text/css">

  #outlook a { padding: 0; }
  .ReadMsgBody { width: 100%; }
  .ExternalClass { width: 100%; }
  .ExternalClass * { line-height:100%; }
	body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
	table, td { border-collapse:collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
  img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
  p {
    display: block;
    margin: 13px 0;
  }

  </style>
  <!--[if !mso]><!-->
  <style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300);
  </style>
  <style type="text/css">
    @media only screen and (max-width:480px) {
      @-ms-viewport { width:320px; }
      @viewport { width:320px; }
    }
  </style>
  <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300" rel="stylesheet" type="text/css">
  <!--<![endif]-->
<style type="text/css">
    @media only screen and (min-width:480px) {
    .mj-column-per-100, * [aria-labelledby="mj-column-per-100"] { width:100%!important; }
}</style></head>
<body id="YIELD_MJML" style=""><div class="mj-body"><!--[if mso]>
  		<table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;"><tr><td>
  		<![endif]--><div style="margin:0 auto;max-width:600px;"><table class="" cellpadding="0" cellspacing="0" style="width:100%;font-size:0px;" align="center"><tbody><tr><td style="text-align:center;vertical-align:top;font-size:0;padding-top:20px;padding-bottom:20px;"><!--[if mso]>
      <table border="0" cellpadding="0" cellspacing="0"><tr><td style="width:600px;">
      <![endif]--><div style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;" class="mj-column-per-100" aria-labelledby="mj-column-per-100"><table width="100%"><tbody><tr><td style="font-size:0;padding-top:10px;padding-bottom:10px;padding-right:25px;padding-left:25px;" align="left"><div class="mj-content" style="cursor:auto;color:#000000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;">Hello &nbsp; !</div></td></tr>Hello &nbsp; !</tbody></table></div><!--[if mso]>
      </td></tr></table>
      <![endif]--></td></tr></tbody></table></div><!--[if mso]>
  		</td></tr></table>
  		<![endif]--></div></body>
</html>
```

**Comment by jsit** [comment] 2016-02-10 15:16
That very example gives me `Hello   !`. I'm on mjml 1.0.3, installed via
npm on a Mac.

On Wed, Feb 10, 2016 at 5:04 AM, Maxime Brazeilles <notifications@github.com

**Comment by iRyusa** [comment] 2016-02-10 16:37
In your example you're nesting a `mj-raw` inside a `mj-text` that's forbidden you can nest any standard html tag in `mj-text` but no mjml component. 

Can you provide me your full mjml document, and if you use with the cli or in a js file ?

**Comment by jsit** [comment] 2016-02-10 16:57
Full mjml document is identical to your example above:

```
<mj-body>
  <mj-section>
    <mj-column>
      <mj-text>Hello &nbsp; !</mj-text>
      <mj-raw>Hello &nbsp; !</mj-raw>
    </mj-column>
  </mj-section>
</mj-body>
```

Output:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>
      undefined
    </title>
    <style type="text/css">
/*<![CDATA[*/

    #outlook a { padding: 0; }
    .ReadMsgBody { width: 100%; }
    .ExternalClass { width: 100%; }
    .ExternalClass * { line-height:100%; }
        body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
        table, td { border-collapse:collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
    img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
    p {
    display: block;
    margin: 13px 0;
    }

    /*]]>*/
    </style><!--[if !mso]><!-->

    <style type="text/css">
/*<![CDATA[*/
    @import url(https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300);
    /*]]>*/
    </style>
    <style type="text/css">
/*<![CDATA[*/
    @media only screen and (max-width:480px) {
      @-ms-viewport { width:320px; }
      @viewport { width:320px; }
    }
    /*]]>*/
    </style>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300" rel="stylesheet" type="text/css" /><!--<![endif]-->

    <style type="text/css">
/*<![CDATA[*/
    @media only screen and (min-width:480px) {
    .mj-column-per-100, * [aria-labelledby="mj-column-per-100"] { width:100%!important; }
    }
    /*]]>*/
    </style>
  </head>
  <body id="YIELD_MJML" style="">
    <div class="mj-body">
      <!--[if mso]>
                <table border="0" cellpadding="0" cellspacing="0" width="600" align="center" style="width:600px;"><tr><td>
                <![endif]-->
      <div style="margin:0 auto;max-width:600px;">
        <table class="" cellpadding="0" cellspacing="0" style="width:100%;font-size:0px;" align="center">
          <tbody>
            <tr>
              <td style="text-align:center;vertical-align:top;font-size:0;padding-top:20px;padding-bottom:20px;">
                <!--[if mso]>
      <table border="0" cellpadding="0" cellspacing="0"><tr><td style="width:600px;">
      <![endif]-->
                <div style="vertical-align:top;display:inline-block;font-size:13px;text-align:left;" class="mj-column-per-100" aria-labelledby="mj-column-per-100">
                  Hello   !
                  <table width="100%">
                    <tbody>
                      <tr>
                        <td style="font-size:0;padding-top:10px;padding-bottom:10px;padding-right:25px;padding-left:25px;" align="left">
                          <div class="mj-content" style="cursor:auto;color:#000000;font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:22px;">
                            Hello   !
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div><!--[if mso]>
      </td></tr></table>
      <![endif]-->
              </td>
            </tr>
          </tbody>
        </table>
      </div><!--[if mso]>
                </td></tr></table>
                <![endif]-->
    </div>
  </body>
</html>
```

I'm using the cli, both -w and -r produce this output.

**Comment by iRyusa** [comment] 2016-02-10 17:06
Ok the issue is related to the client i'm able to reproduce thanks for details !

**Comment by GuillaumeBadi** [comment] 2016-02-11 17:45
Hey @jsit !

This should be solved by the last release! :)

Can you make sure it works on your side, and if so, close the issue ?

Regards,
Guillaume

**Comment by arnaudbreton** [comment] 2016-02-12 11:56
@jsit closing the issue for now, please confirm it works for you, or re-open if still experiencing the issue. Thanks!

**Closed** 2016-02-12 11:55 UTC
Labels: Bug, Client

**Comment by jsit** [comment] 2016-02-12 14:18
Looks good to me. Thanks!

**Comment by roibeart** [comment] 2017-06-14 10:19
Hello, I noticed that in the compiled html the &nbsp; characters are replaced with a character that in text editors are indistinguishable from normal spaces.
It happened that a newsletter service substituted somehow the unbreakable space with a normal space and this issue was hard to notice. Is it possible to preserve the &nbsp; character in the compiled version?

**Comment by dalefish** [comment] 2017-06-14 10:54
&amp;nbsp; should do it.

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by roibeart** [comment] 2017-06-14 12:43
Nice trick, thank you!

Now I wonder: implementing this also inside the components that make use of the unbreakable spaces (e.g. mj-divider) could be a good idea?

**Comment by iRyusa** [comment] 2018-05-07 10:30
Well, this is an issue with the way we encode/decode attributes. It should be fixed in MJML4. In MJML3 the &amp;nbsp; was the only way to prevent this, really weird it doesn't do the trick for you.

**Comment by ngarnier** [comment] 2018-11-09 14:49
@xiddevelop Hm nope. You can see on this link that the space is preserved (even without `&nbsp;`): https://mjml.io/try-it-live/ByBQAM7TQ. 

Your issue is probably coming from elsewhere.
