### ISSUE TITLE
Some Problem with adaptivity

### ISSUE THREAD

**Issue by wireinet** [mjmlio/mjml#937] opened 2018-01-09 15:32 UTC
Hello Developers and users!
I have a problem - like this one;
![2018-01-09_18-23-39](https://user-images.githubusercontent.com/23517333/34728318-a45206fa-f56a-11e7-9573-5c9d53b06e82.png)

as you see - product cards - align in column - but must be in row like in editor:
![2018-01-09_18-24-25](https://user-images.githubusercontent.com/23517333/34728454-0243c244-f56b-11e7-99dd-0012a390a4f0.png)

his snippets in side of them and selected - cant understand. Three items in row or two items - no matter - in client they looks like mobile layout

**Comment by ngarnier** [comment] 2018-01-09 15:34
How did you send? You're probably using a sending platform that alters the HTML and breaks responsiveness. Try using [Putsmail](https://putsmail.com/) (free, no account required) and *DO NOT* check "Move my CSS inline when I click Send Email".

**Comment by wireinet** [comment] 2018-01-09 15:49
trying to send few times - error
![image](https://user-images.githubusercontent.com/23517333/34729498-e057fac6-f56d-11e7-9f91-43b256b320d1.png)

**Comment by ngarnier** [comment] 2018-01-09 15:51
🤔 

Can you share the MJML causing the issue?

**Comment by wireinet** [comment] 2018-01-09 16:07
sure. This is it

[email.zip](https://github.com/mjmlio/mjml/files/1615755/email.zip)

**Comment by ngarnier** [comment] 2018-01-09 16:15
I asked for MJML, but eh. Just tried sending with Putsmail (which worked fine for me) and got the proper result (see below).

The issue is not related with MJML so I'll close it, but here is where to look: 
- the way you send the test
- the version of Gmail you use (you can try to send it to me: ngarnier@mailjet.com and I'll show you how I receive it)

![](https://puu.sh/yXDRc/9350e939c3.png)

**Closed by ngarnier** 2018-01-09 16:15 UTC

**Comment by wireinet** [comment] 2018-01-09 17:20
Thank you for participation! :)
I send you email from thunderbird as usual - please answer as you get it
Thank you for participation! :)
I send you email from thunderbird as usual - please answer as you get it

**Comment by wireinet** [comment] 2018-01-09 18:02
![fireshot capture 44 - _ _ - https___mail rambler ru_](https://user-images.githubusercontent.com/23517333/34735337-2a551660-f580-11e7-91f9-30ba62b7fced.png)
using your service i send few tests - to gmail, rambler and yandex mails client - Only gmail is correct render html  - other two - all blocks in columns
![fireshot capture 43 - _ - https___mail yandex ru_](https://user-images.githubusercontent.com/23517333/34735304-0a9aa56a-f580-11e7-8308-924ec79d35d3.jpg)

very sad...
i use mjml as a part of my work...dont understand how to do this to work

**Comment by dalefish** [comment] 2018-01-09 18:07
Yandex doesn't support media queries, at a guess neither does the other one.

**Comment by wireinet** [comment] 2018-01-09 22:06
hm...strange...but how i know- query need to "re-layout" email, from its original state...in original - 600px i have row with three item - after open on mobile (320) - all rearrange to column - or i wrong and its mobile first?

**Comment by wireinet** [comment] 2018-01-09 22:21
Thankyou for help! Perhaps need to forget about queries in emails

**Comment by ngarnier** [comment] 2018-01-10 08:31
Yep, while now most email clients support responsive styles, Yandex (and probably rambler which I don't know) still doesn't. Sad indeed!
