### ISSUE TITLE
Need a little help with mjml to html !

### ISSUE THREAD

**Issue by uscsnostromo** [mjmlio/mjml#345] opened 2016-07-29 13:42 UTC
Hello all,

I apologize, this is nor a bug report nor an enhancement. But I'm hoping if I get replies that these can help out other people! I'm trying to re-create this with mjml:
![image](https://cloud.githubusercontent.com/assets/20725144/17249314/711f51a0-556d-11e6-81a7-cd77fd4b90b3.png)

So I've created a mjml-divider and the box but they are too far apart, my markup produces this:

![image](https://cloud.githubusercontent.com/assets/20725144/17249425/e524e268-556d-11e6-941f-e3de4ebd6c79.png)

I'm looking for hints to bring these together. Here is my code:

      <mj-section>
        <mj-column>
          <mj-divider border-width="2px" border-style="solid" border-color="#00aeef" padding-bottom="0" padding-top="0" />
        </mj-column>
      </mj-section>

      <mj-section>
        <mj-column>
          <mj-text padding-bottom="0" padding-top="0" align="center">
            <table border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td bgcolor="#00aeef" style="text-transform:uppercase; color:#ffffff; font-family:Arial, Helvetica, sans-serif; font-size: 18px; line-height:18px; padding: 10px 12px; ">discover</td>
              </tr>
            </table>
          </mj-text>
        </mj-column>
      </mj-section>

Any help appreciated, if it's not the proper place to ask this please forgive me and kindly suggest another place.

Thanks!

Thomas

**Comment by dalefish** [comment] 2016-07-29 13:55
Take the top/bottom padding off the sections, might also need vertical alignment on the discover element

**Comment by uscsnostromo** [comment] 2016-08-01 19:05
Thanks @dalefish, tried that but it didn't do the trick.

**Comment by dalefish** [comment] 2016-08-02 07:22
Tested this, it works.

```
 <mj-section padding-bottom="0" padding-top="0">
    <mj-column>
      <mj-divider border-width="2px" border-style="solid" border-color="#00aeef" padding-bottom="0" padding-top="0" />
    </mj-column>
  </mj-section>

  <mj-section padding-bottom="0" padding-top="0">
    <mj-column>
      <mj-text align="center" padding-bottom="0" padding-top="0">
        <table border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td bgcolor="#00aeef" style="text-transform:uppercase; color:#ffffff; font-family:Arial, Helvetica, sans-serif; font-size: 18px; line-height:18px; padding: 10px 12px; ">discover</td>
          </tr>
        </table>
      </mj-text>
    </mj-column>
  </mj-section>

```

I personally use a reset before I start so I know where I am:

` <mj-attributes>
   <mj-all padding="0">
  </mj-attributes>
 </mj-head>`

**Comment by uscsnostromo** [comment] 2016-08-02 18:57
Thanks @dalefish, I had misunderstood what you meant by "take off the padding from the sections". Appreciate your patient help! :)

**Comment by ngarnier** [comment] 2016-08-03 08:30
I believe the issue is fixed so I'm closing @uscsnostromo, feel free to reopen if it's not. 

Big thanks to @dalefish for his help!

**Closed by ngarnier** 2016-08-03 08:30 UTC
Labels: Discussion
