### ISSUE TITLE
Interaction between mj-body width attribute and mj-accordian border attribute

### ISSUE THREAD

**Issue by GarryFlemings** [mjmlio/mjml#1391] opened 2018-10-21 16:53 UTC
**Is your feature request related to a problem? Please describe.**

Demo at https://mjml.io/try-it-live/B14J0adi7
Also (because it's short and we might be changing the code as we work):

    <mjml>
      <mj-body width="690px" >
        <mj-wrapper padding="20px" >
          <mj-section padding="20px 0 0 0" >
            <mj-column>
              <mj-accordion border="solid blue 1px"
                            icon-height="24px"
                            icon-width="24px" >
                <mj-accordion-element>`
    
                  <mj-accordion-title>
                    accordion title
                  </mj-accordion-title>
    
                  <mj-accordion-text>
                    accordion text
                  </mj-accordion-text>

                </mj-accordion-element>
              </mj-acordion>
            </mj-column>
          </mj-section>
        </mj-wrapper>
      </mj-body>
    </mjml>

With the line
`<mj-body width="690px" >`, the output is
![image](https://user-images.githubusercontent.com/14095071/47268931-93300b00-d51c-11e8-99b6-ddbcf186facc.png)

Note that `<mj-accordion>` includes `border="solid blue 1px"` and the result has no left border.

**Describe the solution you'd like**

Left border.

**Additional info**

With the line
`<mj-body>`, the output is
![image](https://user-images.githubusercontent.com/14095071/47268991-5ca6c000-d51d-11e8-872c-69515aaef993.png)

There are no other changes to the source. Note that the left border is present.

In the category of additional info, I'll note the many warnings the editor gives (perhaps this explains the behavior):
* line 7, unclosed XML attribute
* lines 15 to 20, end tag name mismatches

**Sigh**

This may be hard to reproduce. As I wrote this, I got the behavior the pictures show. When I restored the file to the original state (replacing `<mj-body>` with `<mj-body width="690px" >`, I now get the left border on both variants. I don't know when the behavior changed, so it's possible the HTML analysis below was after the change, making it not useful.

On the other hand, I copied the `<mj-body width="690px" >` HTML before I changed the line to `<mj-body>`. Unless the behavior change occurred because of clicking "View HTML", I should have gotten the right HTML for `<mj-body width="690px" >`.

**HTML differences**

The six relevant differences between the generated HTML files are all expectable for the differences between the custom width of 690px and the default width of 600px, and adjustments for padding.

In each file,
* The second table in the HTML listing has the attributes
`border-collapse:collapse;border:solid blue 1px;border-bottom:none;`
* The HTML table containing the "accordion title" string has the attribute `border-bottom:solid blue 1px;`.

**Comment by iRyusa** [comment] 2018-10-23 08:52
cc @kmcb777 
This looks like accordion need the same treatment to include the border size in the calc ?

**Comment by kmcb777** [comment] 2018-10-29 22:28
@iRyusa actually the Accordion never uses the `containerWidth`
@GarryFlemings unfortunately i can't reproduce, it seems fine on all clients, maybe this is caused by the rendering on the try-it-live, there were a few times where i also saw a slight rendering difference when switching to 'view html' then switching back

**Comment by iRyusa** [comment] 2018-11-06 13:54
Well closing it for now, feel free to re-open with more information

**Closed by iRyusa** 2018-11-06 13:54 UTC

**Comment by GarryFlemings** [comment] 2019-03-10 02:52
So sorry to be just seeing this. "Closed" is right. I no longer see this behavior. Thanks.
