### ISSUE TITLE
mjml-button button with href attribute has in Outlook different height than without href attribute

### ISSUE THREAD

**Issue by tomaszchabinka** [mjmlio/mjml#759] opened 2017-07-26 20:08 UTC
Hey,
as mjml-button with href evaluates to _<a href></a>_ html element, and mjml-button without any link evaluates to _<p></p>_ html, this two elements have in effect different height, when displayed in Outlook

**Comment by Kant1-0** [comment] 2017-07-31 11:42
Hi @tomaszchabinka can you share a live snippet so I can try ?

**Comment by iRyusa** [comment] 2017-08-07 11:40
Hi @tomaszchabinka 

Some clients have differents default style for html tags. So you might need to reset it sometimes. 
Button with href uses a simple `a` tag, and without href it uses a `p` tag. 

I'm not able to reproduce on any Outlook so I'm closing the issue. 

If you want to reopen please add more info like outlook version, a live snippet as @Kant1-0 asked and a screenshot so we can provide help on this

**Closed by iRyusa** 2017-08-07 11:40 UTC
