### ISSUE TITLE
Padding on columns

### ISSUE THREAD

**Issue by lrae24** [mjmlio/mjml#564] opened 2017-02-24 10:02 UTC
Hi Guys , 

I need some assistance please , i needed 2 columns but then need to insert a space between them . padding would be ideal i think and according to you documentation  your columns don't support padding. 

Please can you assist me or point me in the right direction.

**Comment by ngarnier** [comment] 2017-02-24 11:23
Hi @lrae24, this is not "natively" possible but we look forward to adding support for gutters. However, there are a few workarounds, such as adding an empty column between the columns:
```
<mjml>
  <mj-body>
    <mj-container>
      <!-- First solution -->
      <mj-section>
        <mj-column background-color="red" width="49%">

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
        </mj-column>
        <mj-column background-color="#FFFFFF" width="2%"> 
        </mj-column>
        <mj-column background-color="blue" width="49%">

          <mj-image width="100" src="/assets/img/logo-small.png"></mj-image>

          <mj-divider border-color="#F45E43"></mj-divider>

          <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
It should look ok in all clients: https://litmus.com/checklist/emails/public/ba3d879

PS: prefer the v3.2.2 for this, there's an issue in the beta version of v3.3.0 when using such a layout, it will be fixed next week.

I'm closing as it's a duplicate of #160.

**Closed by ngarnier** 2017-02-24 11:23 UTC

**Comment by lrae24** [comment] 2017-02-24 11:46
Thanks but just one more question i have tried this  now and currently it works fin on desktop and on mobile the columns no fall underneath each other  but they exclude the spacing added that you see on desktop mail clients so is there any solution that caters for both scenarios  , as the column solution you gave is perfect for desktop  but the spacing falls away or is non existent on mobile??

**Comment by iRyusa** [comment] 2017-02-24 12:22
You can probably add a `mj-spacer`in it
