### ISSUE TITLE
A config file

### ISSUE THREAD

**Issue by acutedeveloper** [mjmlio/mjml#72] opened 2016-02-18 14:51 UTC
I was thinking a nice feature would be to have config file that allows you to set the default values you need. So padding, fonts, width and so on

**Comment by arnaudbreton** [comment] 2016-02-18 17:47
Hey @acutedeveloper we're working on defining the best solution here and include it in a future release. I'm closing here since it is a duplicate of #49. Let's push the discussion there, thanks!

**Closed by arnaudbreton** 2016-02-18 17:47 UTC
