### ISSUE TITLE
Html character encoding

### ISSUE THREAD

**Issue by schurpf** [mjmlio/mjml#347] opened 2016-07-30 13:41 UTC
Hi guys,

awesome tool you are building here!

we are having problem with the following:

```
<mjml>
  <mj-body>
    <mj-container>
      <mj-section >
        <mj-column>
          <mj-text>
            Gr&uuml;ezi
          </mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

results in the &uuml; being converted back to `Grüezi`

From my perspective this was unexpected and undesired. 

Best,

Michael

**Comment by ngarnier** [comment] 2016-08-02 09:44
Hi @schurpf and thanks for opening this issue. As it is a duplicate of #343, I'll close this one so we keep everything on the same issue.

**Closed by ngarnier** 2016-08-02 09:44 UTC
Labels: Bug
