### ISSUE TITLE
quoted font-family issue on buttons when using mj-style and mj-attributes

### ISSUE THREAD

**Issue by levilansing** [mjmlio/mjml#486] opened 2016-12-29 04:28 UTC
Given the following MJML:

```xml
<mjml>
  <mj-head>
    <mj-style>p { margin: 0 0 1.5em 0 }</mj-style>
    <mj-attributes>
      <mj-all font-family="'Arial Black'"/>
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container width="600px">
      <mj-section>
        <mj-column>
          <mj-button>button</mj-button>
          <mj-text><p>text</p></mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```
The [html output](https://mjml.io/try-it-live/B1--CWMrl) for the button has a broken inline style for font-family: `font-family: ' undefined: ArialBlack' font-size: 13px;`

If you remove the `mj-style` tag OR oddly enough the single quotes around the font-family in the `mj-all` tag, the generated inline styles are fine for the button. This doesn't affect paragraph tags in `mj-text`.

If the answer is simply "Quoted font family names are not supported" it would be nice to have in the docs.

(thanks for the awesome library!)

**Comment by ngarnier** [comment] 2017-01-04 09:54
Hey @levilansing, thanks for reporting this issue, we'll look into it.

**Comment by iRyusa** [comment] 2017-03-28 15:26
Hey @levilansing !

`font-family:'Arial Black'`

Looks like to be fixed with MJML 3.3, feel free to reopen if needed

**Closed by iRyusa** 2017-03-28 15:26 UTC
Labels: Render issue

**Comment by osdiab** [comment] 2020-07-02 09:45
Hmmm I ran into the same issue now actually, on MJML 4.6.2 via `mjml-react`

I have this tag:

```
        <MjmlAll
          fontFamily="'Basis Grotesque', 'Helvetica', 'Arial', 'sans-serif'"
          fontSize={`${numPxTextSizes[TextSize.s]}px`}
          padding={0}
        />
```

When I make this `MjmlStyle` tag have the inline attribute:

```
      <MjmlStyle inline>{`
body {
  color: ${LIGHT_EMAIL_THEME.text.body};
}

h1 {
  font-size: ${numPxTextSizes[TextSize.xl]}px;
}
h2 {
  font-size: ${numPxTextSizes[TextSize.l]}px;
  font-weight: 400;
}
h3, h4, h5, h6 {
  font-size: ${numPxTextSizes[TextSize.m]}px;
}

h1, h2, h3, h4, h5, h6 {
  line-height: 1.25;
}

h1, h2, h3, h4, h5, h6, p, ul, ol {
  margin-top: 0;
  margin-bottom: ${spacing.l};
}

ol, ul {
  margin-left: ${spacing.l};
}

a {
  font-weight: 500;
  text-decoration: none;
  color: ${LIGHT_EMAIL_THEME.accent.small};
}

a:hover {
  color: ${LIGHT_EMAIL_THEME.accent.smallHighlight};
  text-decoration: underline;
}

a.preventAutolink, a.preventAutolink:hover {
  font-weight: inherit;
  color: ${LIGHT_EMAIL_THEME.text.body};
}

.darkTheme {
  color: ${DARK_EMAIL_THEME.text.body};
}

.darkTheme a {
  color: ${DARK_EMAIL_THEME.accent.small};
}

.darkTheme a:hover {
  color: ${DARK_EMAIL_THEME.accent.smallHighlight};
}

.darkTheme a.preventAutolink, .darkTheme a.preventAutoLink:hover {
  color: ${DARK_EMAIL_THEME.text.body};
}
      `}</MjmlStyle>
```

Result is some elements like `MjmlButton` end up with this `font-family`:

```
font-family: ' undefined: BasisGrotesque' undefined: ,' undefined: Helvetica' undefined: ,' undefined: Arial' undefined: ,' undefined: sans-serif' font-size: 16px
```

But removing the `inline` attribute doesnt cause this problem. Any thoughts @iRyusa ?

**Comment by iRyusa** [comment] 2020-07-02 10:05
It works fine on mjml package here so if there's an issue it's on mjml-react side

**Comment by osdiab** [comment] 2020-07-02 13:10
Looking at the mjml-react code though all it does is create the equivalent mjml native elements and then run it through the mjml compiler - it’s possible that’s where the problem lies but I’ll try to reproduce in bare mjml
