### ISSUE TITLE
Carousel issue on Outlook desktop

### ISSUE THREAD

**Issue by juliealchin** [mjmlio/mjml#545] opened 2017-02-09 20:20 UTC
When you view the carousel in outlook on desktop, Chrome and Safari I've tried so far, in the preview pane it displays the thumbnails and first image, the thumbnails aren't responding though, hover or click. When you open up the email it just shows you the first image, which is the fallback it's meant to display.

Shouldn't the preview pane have the same behaviours as the opened email?

**Comment by ngarnier** [comment] 2017-02-14 14:36
Hey @juliealchin, thanks for creating this issue.

Could you please provide screenshots of the preview pane and once opened? 

Cheers!

**Comment by juliealchin** [comment] 2017-02-14 19:29
Sure @ngarnier :

![outlook-preview](https://cloud.githubusercontent.com/assets/15878971/22945335/bda09f46-f358-11e6-8eba-0f44dacfec85.png)
![outlook-opened](https://cloud.githubusercontent.com/assets/15878971/22945349/c47fbec8-f358-11e6-89f2-e71c31abb017.png)

**Comment by iRyusa** [comment] 2017-07-19 10:04
hi @juliealchin 

I am not able to reproduce the issue how did you send this email ?

**Comment by iRyusa** [comment] 2017-10-17 15:05
Well with no news on that, I'm closing the issue.

**Closed by iRyusa** 2017-10-17 15:05 UTC
Labels: Render issue

**Comment by scottmay2020** [comment] 2023-09-29 18:03
Seems that Outlook and GMail do not allow interactivity with emails. Therefore these types of components will not work. Which may explain why you can not find the accordion or carousel in the mjml-compatibility sections.
