### ISSUE TITLE
HTML minification not working

### ISSUE THREAD

**Issue by kailasnadh790** [mjmlio/mjml#2360] opened 2021-09-14 14:32 UTC
Even with minify: true , the HTML output is not getting minified and is causing issue on gmail.
![image](https://user-images.githubusercontent.com/53608019/133277278-4dbc3313-747e-4d85-9dad-e513ac77c6ab.png)

**Comment by iRyusa** [comment] 2021-09-17 12:57
I'm not really able to reproduce here can you provide more info ?

**Comment by iRyusa** [comment] 2021-09-21 11:11
I'm closing for now because I can't reproduce.  Feel free to reopen with a repo to reproduce so we can investigate

**Closed by iRyusa** 2021-09-21 11:11 UTC
