### ISSUE TITLE
Watching Directory Issue

### ISSUE THREAD

**Issue by bundabrg** [mjmlio/mjml#1870] opened 2020-03-26 09:00 UTC
**Describe the bug**
If I watch a folder using a fully qualified name it will only see changes to the first file.
If I use a relative name then it works fine.

**To Reproduce**
1. Create a folder test, test/src, test/output. Add several mjml files into src.
2. cd into test
3. Try to watch using full name:
```
mjml -w /mydir/test/src/\*.mjml -o /mydir/test/output/
```
It only works for the first file. Note I escaped the glob. If I don't escape it then it works but that's because my shell expands it and it won't notice new files.

4. Try watch using relative name:
```
mjml -w src/\*.mjml -o output/
```

Note the output doesn't need to be relative and has no bearing on this issue.

**Expected behavior**

**MJML environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - MJML Version [e.g. 4.2.0]
 - MJML tool used [e.g MJML App]

**Email sending environment(for rendering issues)**:
 - Platform used to send the email [e.g [Putsmail](https://putsmail.com/)]  

**Affected email clients (for rendering issues):**
 - Email Client [e.g Gmail] 
 - OS: [e.g. Windows]
 - Browser [e.g. Google Chrome]

**Dockerfile to reproduce environment**
```
####################################################################################################################
# Global Arguments
####################################################################################################################

ARG APP_ROOT=/app

####################################################################################################################
# Template Builder
####################################################################################################################
FROM node:13-alpine as templates-builder

# Setup Environment
ARG APP_ROOT

WORKDIR ${APP_ROOT}
ENV PATH="${APP_ROOT}:${PATH}"
ENV APP_ROOT=${APP_ROOT}

# Install Dependencies
RUN \
    apk add --no-cache \
        dumb-init

RUN \
    npm install -g mjml && \
    mkdir ${APP_ROOT}/src ${APP_ROOT}/output

ENTRYPOINT ["dumb-init"]
CMD ["build"]
```

**Comment by iRyusa** [comment] 2020-03-30 14:26
Can you paste the output of the command and a `ls` of the folder ?

I can't reproduce on 4.2 
```
➜  mjmltest yarn mjml -w \*.mjml -o output/
yarn run v1.15.2
Now watching: *.mjml

/Users/maximebrazeilles/mjmltest/p.mjml - Change detected
/Users/maximebrazeilles/mjmltest/s.mjml - Change detected
/Users/maximebrazeilles/mjmltest/test.mjml - Change detected
/Users/maximebrazeilles/mjmltest/testlo.mjml - Change detected
/Users/maximebrazeilles/mjmltest/test.mjml - Successfully compiled
/Users/maximebrazeilles/mjmltest/s.mjml - Successfully compiled
/Users/maximebrazeilles/mjmltest/p.mjml - Successfully compiled
/Users/maximebrazeilles/mjmltest/testlo.mjml - Successfully compiled
```

**Comment by iRyusa** [comment] 2020-04-12 22:13
Closing here can't seem to reproduce, feel free to re open with more info

**Closed by iRyusa** 2020-04-12 22:13 UTC
