### ISSUE TITLE
Border radius for mj-wrapper is not respected when borders are present

### ISSUE THREAD

**Issue by gabrieltomescu** [mjmlio/mjml#606] opened 2017-03-21 14:17 UTC
Using the Try it Live option, I'm applying the border-radius property to a ```mj-wrappper```: https://mjml.io/try-it-live/Sycd3T6sg

![image](https://cloud.githubusercontent.com/assets/1161699/24151503/5dd2f280-0e1f-11e7-85e7-d0cc89c78643.png)

The problem is that border-radius is not working properly when a border is applied to the ```mj-wrapper```, in this case ```2px solid #000```.

Here is the code snippet:
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-spacer/>
      <mj-wrapper full-width="full-width" background-color="cyan" border="2px solid #000" border-radius="8px">
        <mj-section>
          <mj-column>
            <mj-text>Hello</mj-text>
          </mj-column>
        </mj-section>
      </mj-wrapper>
    </mj-container>
  </mj-body>
</mjml>
```

A potential solution could be to move the ```border``` and ```background``` properties to the wrapping ```div``` around the table generated by ```mj-wrapper```, instead of on the table itself.

**Comment by iRyusa** [comment] 2017-03-21 14:29
Hi @gabrieltomescu the issue with border + radius come from `table` border-collapse. You can't use both border & radius on a table with border-collapse.

if we're moving the border to the div, it will break the render on Outlook (the border is broken on the right side for unknown reason ) cf : 
![image](https://cloud.githubusercontent.com/assets/570317/24152151/1e395be2-0e4b-11e7-9bb1-65a648d21be7.png)

**Comment by gabrieltomescu** [comment] 2017-03-21 15:30
@iRyusa I see. Reading a bit about this, it seems like the enclosed table is 'breaking out' of the surrounding ```div```, which acts like it has ```overflow: hidden;```

Thanks for the quick response on this. Feel free to close this if you feel it cannot be achieved given the Outlook limitations.

**Comment by iRyusa** [comment] 2017-03-21 15:34
Well I close this one until someone has a possible fix for this !

**Closed** 2017-03-21 15:35 UTC

**Comment by ramykhuffash** [comment] 2017-11-16 12:51
A quick hack I use for this is to wrap with an mj-section with padding of 1px (or however thick you want your border) and a background color of what you want your border to be with a border-radius.

Then the contents of that mj-section can have a white background, so the background of the wrapping section looks like a border with a border-radius.

Eg `<mj-section padding="1px" border-radius="4px" background-color="#ddd">
                      <mj-section padding="0" background-color="white">`

I've not tested in many clients though...

**Comment by HansGerber** [comment] 2018-11-28 11:29
> A quick hack I use for this is to wrap with an mj-section with padding of 1px (or however thick you want your border) and a background color of what you want your border to be with a border-radius.
> 

Accordings to the docs "Sections cannot be nested into sections".
(https://mjml.io/documentation/#mjml-section)

**Comment by iRyusa** [comment] 2018-11-28 11:41
We now count the border in the width calc so it should no longer happen (nesting section is basically the same as nesting section in wrapper, but it way safer to use wrapper)

**Comment by HansGerber** [comment] 2018-11-28 12:01
I have the same problem as the original poster (using core and cli version 4.2.0)

I used the solution mentioned by @ramykhuffash and it worked however I'm getting the warning
"Line 45 of C:\xampp\htdocs\wvh\art-v1-email-templates\templates\neighborhood-soft-delete-mail-02.mjml (mj-section) — mj-section cannot be used inside mj-section, only inside: mj-attributes, mj-body, mj-wrapper"

Can this be ignored then?

**Comment by iRyusa** [comment] 2018-11-28 12:07
It works fine with MJML 4.2 : https://app.emailonacid.com/app/acidtest/r2XPAU4qubQiVeUutwWg6w8AaoETgtEp0Xa4YpIV8bTdX/list

With this code:  

```xml
<mjml>
  <mj-body>
      <mj-wrapper background-color="cyan" border="2px solid #000" border-radius="8px">
        <mj-section>
          <mj-column>
            <mj-text>Hello</mj-text>
          </mj-column>
        </mj-section>
      </mj-wrapper>
  </mj-body>
</mjml>
```

**Comment by avit** [comment] 2019-09-05 18:07
@iRyusa I am not seeing this working quite right with the above markup in mjml 4.4.1:

<img width="60" alt="Screen Shot 2019-09-05 at 11 00 53 AM" src="https://user-images.githubusercontent.com/4278/64367163-80a3b080-cfcc-11e9-8257-5505dc508c20.png">

The resulting HTML looks like:

```
<div style="background:green;background-color:green;margin:0px auto;border-radius:12px;max-width:810px;">
      <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="background:green;background-color:green;width:100%;border-radius:12px;">
        <tbody>
          <tr>
            <td style="border:1px solid #000;direction:ltr;font-size:0px;padding:20px 0 0;text-align:center;">
```

I'm seeing the border is on the inner `td` without a radius. Is this a regression since 4.2?

**Comment by iRyusa** [comment] 2019-09-05 18:18
Due to table’s border collapse, the border radius isn’t applied to the actual border. You have to override the border collapse to initial & maybe apply the radius on the html cf 

https://github.com/mjmlio/mjml/issues/1641
