### ISSUE TITLE
Columns outside of container - Outlook

### ISSUE THREAD

**Issue by maciekgrzybek** [mjmlio/mjml#618] opened 2017-03-27 11:27 UTC
I've got problem with rendering one columns section - columns are outside the main container (only in Outlook 2000, 2002, 2003).
 It looks like that
![screenshot-litmus com-2017-03-27-12-22-02](https://cloud.githubusercontent.com/assets/16546428/24353980/13822944-12e8-11e7-8aee-edc9699239f0.png)
and it supposed to look like this:
![screenshot-litmus com-2017-03-27-12-24-04](https://cloud.githubusercontent.com/assets/16546428/24354033/4fcbb96a-12e8-11e7-8844-bcd2c153108a.png)

`		
		<mj-section>
			<mj-column>
				<mj-image src="images/bg2.jpg" padding="0px"/>
			</mj-column>
		</mj-section>

		
		<mj-section padding-top="0" padding-bottom="0" text-align="center">
			<mj-column>
				<mj-image src="images/ico1.png" padding="0px"/>
				<mj-text mj-class="header center">WEEKEND MAKE-UP WITH<br>LAURIE ELLE AND<br>ILLAMASQUA</mj-text>
				<mj-text mj-class="plain-text center">Laurie Elle’s Illamasqua make up tutorial<br>will help you to look your best this weekend.</mj-text>
				<mj-button mj-class="empty-btn pink center">See more</mj-button>
			</mj-column>
		</mj-section>

		
		<mj-section text-align="center">
			<mj-column width="300px"> 
				<mj-image src="images/woman.jpg" align="center" />
				<mj-text mj-class="header center">A BLAZER FOR<br>EVERY OCCASION</mj-text>
				<mj-button mj-class="empty-btn pink center">See more</mj-button>
			</mj-column>
			<mj-column width="300px">
				<mj-image src="images/man.jpg" align="center" />
				<mj-text mj-class="header center">MENS FITNESS<br>FOCUS</mj-text>
				<mj-button mj-class="empty-btn aqua center">View trend</mj-button>
			</mj-column>
		</mj-section>

		
		<mj-section>
			<mj-column>
				<mj-image src="images/bg3.jpg" padding="0px"/>
			</mj-column>
		</mj-section>

		
		<mj-section padding-top="0" padding-bottom="0" text-align="center">
			<mj-column>
				<mj-image src="images/ico2.png" padding="0px"/>
				<mj-text mj-class="header center">WEDDING PLANNING WITH<br>PAPERCHASE</mj-text>
				<mj-text mj-class="plain-text center">Whether you’re a couple prepping for the big day or a guest searching for an<br>off-the-registry gift, Paperchase’s wedding collection will certainly del</mj-text>
				<mj-button mj-class="empty-btn aqua center">View collection</mj-button>
			</mj-column>
		</mj-section>`

**Comment by iRyusa** [comment] 2017-03-27 11:34
Hi @maciekgrzybek 

Outlook 2000 to 2003 has a small issue with images with an higher natural width than the column. Try to resize image width to the column width and then it should work.

**Comment by maciekgrzybek** [comment] 2017-03-27 12:45
Hi @iRyusa , thanks for fast reply, unfortunately that didn't help, any other ideas? I tried to center align section, column, text, button - nothing.

**Comment by iRyusa** [comment] 2017-03-27 12:50
What version of MJML are you using ? Can you try to provide both template & images hosted somewhere so we can try to reproduce the behaviour here ? Thanks

**Comment by maciekgrzybek** [comment] 2017-03-27 13:19
It's MJML 3.3.0 
Maybe I'm doing some basic mistake I don't know, I just started using MJML.
Here's the mjml file with images.
[test.mjml.zip](https://github.com/mjmlio/mjml/files/872534/test.mjml.zip)

**Comment by iRyusa** [comment] 2017-03-27 14:19
The problem is indeed the actual width of the images. For example in the 2 column sections, image's width is 520px while it's contained in a 300px column. Outlook is displaying the image has 520px wide and doesn't take the width set in the HTML into account. 

To avoid this, resize the width of the actual image to 250px. We're removing the padding to the actual size, `mj-image` has a default padding of `10px 25px`so 300px-50px, if you want a full-column image, just set the padding to 0.

In a complete different note, your template looks amazing ! We’d love to feature it in our gallery (https://mjml.io/templates), are you in? We’ll add credits to you/your website

**Comment by maciekgrzybek** [comment] 2017-03-27 15:15
Awesome, now it's working -  cheers! I would love to, but unfortunately it's not my template, I'm just using it for training purposes. Next one will be my own template, so I'll definitely upload it :)

**Comment by iRyusa** [comment] 2017-03-28 12:29
No problem ! I'm closing the issue if it's ok then 👍

**Closed by iRyusa** 2017-03-28 12:29 UTC
