### ISSUE TITLE
Hero Image not rendering on Outlook 2016

### ISSUE THREAD

**Issue by cly3** [mjmlio/mjml#1526] opened 2019-02-21 11:39 UTC
<mj-hero>  is not rendering in Outlook 2016 on PC desktop. It looks good on all other platforms/clients.

```
<mjml>

  <mj-head>

    <mj-attributes>
      <mj-text align="left" color="#fff" font-size="15px" line-height="1.5" font-family="roboto"/>
      <mj-section background-color="#373737" />
    </mj-attributes>

  </mj-head>

  <mj-body background-color="#e4e4e4">
    <mj-section background-color="#e4e4e4">
    <mj-column width="30%" vertical-align="middle">
      <mj-image align="center" href="#" align="left" src="#" />
    </mj-column>
    <mj-column width="70%" vertical-align="middle">
      <mj-text font-family="arial" align="center" color="#373737"><p style="font-size:10px;">UNIVERSITY OF MARS | FEB 2019</p></mj-text>
    </mj-column>
      </mj-section>


      <mj-hero mode="fixed-height"
                height="469px"
                background-width="450"
                background-height="469px"
                background-url="https://www.fireflyorthoses.com/wp-content/uploads/37.png">

        <mj-text padding-top="40%"
                 font-size="45px"
                 line-height="1"
                 align="center"
                 padding-top="70px"
                  font-weight="900"><a style="text-shadow:3px 3px #838383; font-family:brandon grotesque; letter-spacing:3;">KEEP IN TOUCH</a></mj-text>



              <mj-button padding-top="2%"
                         background-color="#fff"
                         color="#fb4f14"
                         inner-padding="10px"
                         font-size="19px"
                         href="www.google.ie" align="center">
                JOIN THE MAILING LIST
              </mj-button>


      </mj-hero>
    <mj-section>
    <mj-column width="80%">
      <mj-image width="200%" padding-top="10%" src="https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjh-Kfx1szgAhUNQxUIHS5HCBQQjRx6BAgBEAU&url=https%3A%2F%2Fpngimage.net%2Flogo-placeholder-png-4%2F&psig=AOvVaw1Zio4OabCYKE56Tis3NQdu&ust=1550833285664519" />
      <mj-text>
        <p>Hi [firstname, fallback=there]</p>
 



                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.  </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>

            <p>Best Wishes,</p>

      <p align="left">John | Company </p>
      </mj-text>

      </mj-column>

      </mj-section>

  <mj-section background-color="#e4e4e4">
    <mj-column width="80%">
      <mj-text align="left"><p style="font-size:13px; color:#808080;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut.</p> </mj-text>
    </mj-column>
    </mj-section>


               <mj-section background-color="#e4e4e4" padding="0 0 0 0">
        <mj-column>
          <mj-text align="center" color="grey">
            COMPANY NAME
          </mj-text>

        </mj-column>
      </mj-section>

    


     <mj-section background-color="#e4e4e4">
        <mj-column>
          <mj-text align=center color="grey" font-size="13">
            <preferences>subscription preferences</preferences> &nbsp;|&nbsp; <unsubscribe> unsubscribe</unsubscribe>
          </mj-text>
        </mj-column>
      </mj-section>


  </mj-body>
</mjml>
```

**Describe the bug**

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`
2. Render it to HTML by doing '...'
3. Send the HTML to an email address with '...'

**Expected behavior**
The email is rendering correctly on webclients, including outlook's webclient, but not on Outlook 2016 on desktop. 

**MJML environment (please complete the following information):**
 - OS: 
 - MJML Version  4.0.0
 - MJML tool used -  MJML App]

**Email sending environment(for rendering issues)**:
 - Campaign Monitor

**Affected email clients (for rendering issues):**
 - Email Client Outlook
 - OS: Windows
 

**Screenshots**
![outlook2016](https://user-images.githubusercontent.com/34556416/53166413-1cd80e00-35cd-11e9-8938-2ef0adf04b2d.png)

**Comment by kmcb777** [comment] 2019-02-21 12:56
Hi @cly3, i can't reproduce the issue, i tested your code on emailonacid and it renders fine :
<img width="1162" alt="screen shot 2019-02-21 at 13 55 18" src="https://user-images.githubusercontent.com/8144509/53170461-6da53200-35e0-11e9-8cb8-39b03f856c97.png">

**Comment by cly3** [comment] 2019-02-21 14:16
thanks for getting back to me @kmcb777. I work of Mac OS but I'm testing on colleague's windows pc which is running Microsoft Office 365 Business. Maybe this runs a different version of Office?

**Comment by iRyusa** [comment] 2019-02-21 14:17
As you're sending through campaign monitor, try send it with putsmail.com it might be campaign monitor altering the HTML

**Comment by cly3** [comment] 2019-02-21 14:28
@iRyusa – afraid the results are the same, even when sent through PutsMail.

**Comment by iRyusa** [comment] 2019-02-21 14:32
I see that you have some padding un `%` those are not supported on outlook try with some px maybe :/ 

But at this point i don't really know what's going on as litmus test/eoa test shows up fine, any chance that you're altering the output html ?

**Comment by iRyusa** [comment] 2019-02-27 14:54
Any update on this ? Did you try with latest version ?

**Comment by iRyusa** [comment] 2019-03-18 13:34
Closing for now, feel free to reopen if you have more information to share

**Closed by iRyusa** 2019-03-18 13:34 UTC

**Comment by crashworx** [comment] 2019-06-23 04:48
I can reproduce this issue as well
i get a background image that doesn't render.
I'm using the online live editor.

Looks find in everything except Outlook 2016.

Here is the mjml
<mj-hero background-color="#f1f2f5" background-url="https://www.abcdefg.com/img-email/banner-help.png" padding="20px" background-height="220px">

and here is the output HTML.

    
    <div style="margin:0 auto;max-width:600px;">
      <table border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;">
        <tr style="vertical-align:top;">
          <td background="https://www.abcdefg.com/img-email/banner-help.png" style="background:#f1f2f5 url(https://www.abcdefg.com/img-email/banner-help.png) no-repeat center center / cover;background-position:center center;background-repeat:no-repeat;padding:20px;vertical-align:top;"
            height="-40">

**Comment by m-kaddatz** [comment] 2019-07-17 14:11
hey, i found a little hack to solve this issue. In the vml tags, you have to play with this attributes:

`origin="0.5, 0" position="0.5, 0" `

after some tests, its gonna work with (depends also on image-size):

`origin="1, 0" position="1, 1"`

Additionally, you also have to remove the **background-color** on the next couple <div> tags.

`
        <div
            style="background:**#ffffff** url(image.jpg) top center / auto no-repeat;Margin:0px auto;max-width:630px;">
            <div style="line-height:0;font-size:0;">
                <table align="center"
                    background="image.jpg"
                    border="0" cellpadding="0" cellspacing="0" role="presentation"
                    style="background:**#ffffff** url(image.jpg) top center / auto no-repeat;width:100%;">
.
.
.
`
