### ISSUE TITLE
MJML is not properly working

### ISSUE THREAD

**Issue by vysakhjayadas** [mjmlio/mjml#2594] opened 2022-12-06 11:39 UTC
Hi Team,
The MJML app is working very slowly after OS upgrade. We have tried in multiple device
Slowness issue is reported in Monterey  12.6 and Ventura 13.0.1
Mjml Version 3.0.4
Working fine in Catalina.
Multiple MJML users are affected after macOS upgrade . We have erased the mac and checked. Still facing issue on Monterey and Ventura devices. 
Please let me know any other details are required.

**Comment by iRyusa** [comment] 2022-12-06 11:41
Still a duplicate of the last issue...

**Closed by iRyusa** 2022-12-06 11:41 UTC
