### ISSUE TITLE
MJML - Outlook 2013 Only - Images Crop 

### ISSUE THREAD

**Issue by nanoarts** [mjmlio/mjml#1308] opened 2018-08-08 08:01 UTC
Hi everyone,
I try MJML , nice stuff ! but i have a little problem 👍 

when i try this export , on outlook my img are crop..

 you can see the code here : [https://mjml.io/try-it-live/BJsg0M_Bm](https://mjml.io/try-it-live/BJsg0M_Bm)
and the example on outlook 2013 : [https://d2tygfsszdug5i.cloudfront.net/client/vag6pg8137/media/4bme198jb8.PNG](https://d2tygfsszdug5i.cloudfront.net/client/vag6pg8137/media/4bme198jb8.PNG)

and i don't find how to resolve that ( it try raw, padding, hieght on section on column , on image ...)

**Comment by kmcb777** [comment] 2018-08-08 09:55
Hi @nanoarts which mjml version are you using ?
I couldn't reproduce, it seems to render fine on all outlook versions :
![image](https://user-images.githubusercontent.com/8144509/43830263-2d87165e-9b01-11e8-9a36-f373805da552.png)

Usually the fix for this kind of outlook-image problem is to set `style="line-height: 1;"` on the td that's around the <img>, but it's when you use a raw <img> tag, it shouldn't happen with <mj-image>

**Comment by nanoarts** [comment] 2018-08-08 12:04
hi,
 it's strange ...do you check on emailonacid ?

i using the MJML editor on my desktop ( i download him today from the website ) ( after i send with the editor a test email on email on acid )

**Comment by kmcb777** [comment] 2018-08-08 12:12
@nanoarts yes i check on emailonacid
i tested again with the desktop app, using the "Copy html" button, and i get the same result.
if you still get this problem, could you copy the generated html here ?

**Comment by nanoarts** [comment] 2018-08-10 08:54
ok thk to try i put some height on the html file and that's fixed ...but yeah i don't understand why i have that and not you ... 

I have a new responsive email to do , so i will retry MJML :)

**Comment by iRyusa** [comment] 2018-08-10 09:17
Well if we unable to reproduce, I'm closing the issue for now. Feel free to reopen if you find a way for us to reproduce

**Closed by iRyusa** 2018-08-10 09:17 UTC

**Comment by nanoarts** [comment] 2018-08-10 12:59
New mail same problem : 

code here : [ici](https://mjml.io/try-it-live/SJpmYR9rm)

Screenshoot on emailonAcid : [ici](https://d2tygfsszdug5i.cloudfront.net/client/vag6pg8137/media/m52vkl335v.PNG)

**Comment by iRyusa** [comment] 2018-08-10 13:14
I think I've found the issue but you'll have to fix it manually.

It seems like having an image inside a VML block inside a mj-wrapper need to have a `width` & `height` in order to be displayed properly.

So just set the `mj-image` height to the actual desired height and it works fine.

Note that there's a bug with padding in Outlook inside a vml block, so you have to remove the left & right padding on mj-image to center it properly.

I won't reopen the issue because it's quirk of Word (only 2013 tho 🤔) and it looks we can't really do anything without image height here

**Comment by nanoarts** [comment] 2018-08-10 13:19
yep i use mj-wrapper because i need a background behind everything ...but if you have a another idea i can remove the mj-wrapper

**Comment by nanoarts** [comment] 2018-08-10 13:35
ok i can put a height on image in the MJML editor ? or i need do that in the html build ? because when i try on the MJML editor : height="xxx" or style="xxxx" they are an error "attribut target are illegal " ...maybe its better with the online editor ( no error ^^ )

**Comment by kmcb777** [comment] 2018-08-13 13:32
@nanoarts Validation errors are just warnings, meaning that the attribute is not handled and will just be ignored. This kind of validation is just not done on the online editor ;)
`target` wasn't handled on mj-image when the last app release was made, but this will be fixed in the next version.
Anyway this has no influence on the handling of the `length` attribute 👍

**Comment by nanoarts** [comment] 2018-08-14 07:52
yops , so i try to remove the warper and cut my backgorund for every section ... 

Like that's :
https://mjml.io/try-it-live/HyWWcWe87

and always problem on outlook 2013 ..And now with lotus ^^" ( i hate emailing :D )

**Comment by iRyusa** [comment] 2018-08-14 08:19
Just keep the wrapper and set the height to image as mentioned here: 
`So just set the mj-image height to the actual desired height and it works fine.`
