### ISSUE TITLE
mj-raw elements are taken into account for width calculation of mj-column

### ISSUE THREAD

**Issue by Buuhuu** [mjmlio/mjml#1186] opened 2018-05-08 14:32 UTC
In the most basic setup, `mj-column` gets its relative width calculated from the number of siblings in the same `mj-section` [1] [2]ff. This also takes `mj-raw` into account. This seems odd to me, is that the expected behaviour? 

If not, I would propose to not take `mj-raw` into account, counting the siblings. 

**Context** 
I'm evaluating the use of mjml in a enterprise content management system. The CMS uses some specific html tag to inject its wysiwyg behaviour into the rendered markup (only in editing mode). For that we use the `mj-raw` component which works fine. The experience though is not 100% perfect as the sizing is not calculated as it will be in non-editing mode.

**Reproduction Steps:**

1. Consider the following mjml 
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>Hello</mj-text>
      </mj-column>
      <mj-column>
        <mj-text>World</mj-text>
      </mj-column>
      <mj-raw>
        <div style="background-color: red; height: 100px; width: 100px"></div>
      </mj-raw>
    </mj-section>
  </mj-body>
</mjml>
```
2. Run the example https://mjml.io/try-it-live/BJHSkEJCf

**Expected behavior:**

As there are 2 columns in the section. I expect the with of each of it being 50%, not 33% as calculated based on the count of siblings. Even worse, when adding some html comments (`<!-- comment -->`), as they automatically are wrapped in `mj-raw`

**Observed behavior:**

The columns get 33% width (`mj-column-pre-33`)

**MJML version:**

4.0.5

[1] https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L137
[2] https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/createComponent.js#L146

**Comment by iRyusa** [comment] 2018-05-09 08:40
Hi & thanks for reporting this,

This is a duplicate of #1152, we'll fix it for 4.1 release. For now setting the width on column manually is the best way to handle the case

**Closed by iRyusa** 2018-05-09 08:40 UTC
