### ISSUE TITLE
Issue with columns not aligning properly in certain clients

### ISSUE THREAD

**Issue by Reached** [mjmlio/mjml#574] opened 2017-03-01 15:05 UTC
Hi there,

I am really enjoying to use MJML, however I am facing an issue that I can't seem to solve on my own at the moment. 

I want have my logo on the left side, and the social icons on the right side, my implementation works fine in modern clients like my mail.app and on my IOS device, but it breaks in Outlook Gmail etc. 

Here is a screenshot displaying the issue and the expected result:

(The first image is the correct result, and the other one is taken from Outlook=

http://imgur.com/a/3sK2M

This is the code that was used to create what you see in the screenshots:

```
<mjml>
  <mj-body>
    <mj-container background-color="#d9e6e5" width="600px">
        <mj-section padding-top="30px">
          <mj-column width="33.33333333333333%" vertical-align="middle">
            <mj-image src="https://gallery.mailchimp.com/69fe280f6a0b01f2684b4f174/images/f0278b13-1e35-4da6-a0c9-705d2f771dbf.png" width="250px" height="50px" alt="" padding="0"></mj-image>
          </mj-column>
          <mj-column width="66.66666666666666%" vertical-align="middle">
            <mj-social padding="0" mode="horizontal" text-mode="false" align="right" display="facebook instagram youtube"></mj-social>
          </mj-column>
        </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

Can anyone help here? Is this even possible to do?

**Comment by iRyusa** [comment] 2017-03-01 15:45
Hi @Reached ,

This is totally the expected behaviour, you're seeing the mobile version in Outlook.com cf this comment https://github.com/mjmlio/mjml/issues/40#issuecomment-233979300 on #40 ( I'm not sure how you're seeing mobile in Gmail ). 

One "cheap solution" is to keep a `33.3333%` empty column in an keep align center instead of center. This is not the best workaround but the mobile version will be much better.

One other solution is to use mj-group, but the logo will be almost unreadable.

**Comment by Reached** [comment] 2017-03-01 19:32
Hi @iRyusa !

Thanks for getting back to me this fast, I guess I will have to go with the empty centered column to get to my end result, thanks again.

**Comment by ngarnier** [comment] 2017-03-02 08:35
Hey @Reached, you want the logo and social icons to still be side by side on mobile devices right? So you should use [mj-group](https://mjml.io/documentation/#mjml-group) to prevent columns from stacking.

Here is an example implementation: https://mjml.io/documentation/#mjml-group

Be aware that due to a bug in iOS9, you should remove the blank space between the columns or minify the HTML:
> iOS 9 Issue: If you use a HTML beautifier for MJML output, iOS9 will render your columns inside a mj-group as stacked. On the output HTML, remove the blank space between the two columns inside a mj-group.

Does it help?

**Comment by Reached** [comment] 2017-03-02 08:36
Hi @ngarnier, actually they should be stacking on mobile devices :)

Desktop: Side by side
Mobile: Stacked (with the social icons below the logo)

Thanks for helping!

**Comment by ngarnier** [comment] 2017-03-02 08:53
Hi @Reached, oh ok, my bad. Indeed my example is to prevent stacking, I thought that's what you wanted to do.

So if I understood correctly you want the logo and social icons aligned centered on mobile? Here are two ways to do it: 
- the "cheap" solution suggested by @iRyusa, with `align="center"` on both columns
- a more advanced solution using media queries

Here's an example for both solutions (you might want to fine tune the CSS selector): https://mjml.io/try-it-live/SJ3kqIHcg

**Comment by Reached** [comment] 2017-03-02 09:06
So I tried both solutions, with the advanced version it looked like the columns were not aligned (and possibly still stacked - i have attached a screenshot of this), it looked good in Gmail now though :).

http://imgur.com/l5OOwBa

With the "cheap" solution, the columns just stacked. I think I should mention that this is in Outlook's web app.

**Comment by ngarnier** [comment] 2017-03-02 09:07
Alright, I'm sorry but I think I definitely don't understand what you want to do then... Can you provide a design of how you want the columns to appear on desktop and on mobile? I'm a bit lost :)

**Comment by ngarnier** [comment] 2017-03-02 09:14
Just to make sure it's clear: Outlook.com will display the mobile version of the email. There's no alternative here as Outlook.com doesn't support responsive styles.

**Comment by Reached** [comment] 2017-03-02 09:34
Sorry for explaining it badly :)

This is the (expected) result for desktop and mobile:
http://imgur.com/a/KqDtx

**Comment by ngarnier** [comment] 2017-03-02 13:21
No worries, it's sometimes hard to pass visual ideas with text! 

So we understood each other, the way to achieve it is what I sent you (the more advanced solution). Unfortunately, some clients don't support responsive styles / media queries, so if you use them it won't work on: 
- Outlook.com - doesn't support responsive styles, so it will show the mobile layout (columns stacked) without changing the alignment
- Gmail App - Android (using IMAP) - doesn't support `<style>` in the head, so no media queries: it will show the mobile layout (columns stacked) without changing the alignment
- Android Mail 5.1 & 6.0 - doesn't support `<style>` in the head, so no media queries: it will show the mobile layout (columns stacked) without changing the alignment

It will look good everywhere else. If you're not happy with how it looks on Outlook.com/Android, you shouldn't use media queries to change alignment. Prefer keeping the elements on the same line with `mj-group` or use the 3-columns version.

Here are 2 demos to compare options.
- With media queries: https://litmus.com/checklist/emails/public/468419c
- With mj-group or an empty column: https://litmus.com/checklist/emails/public/c9e508e

Is it clearer?

**Comment by Reached** [comment] 2017-03-03 08:34
Hi @ngarnier ! Thanks for taking the time to explain this, I guess for this case I need the desktop version to be similar in all of the clients (also outlook.com), so i decided to create some custom styling that changes the behaviour of the mj-group a bit on mobile, so essentially it's just stacking the items on smaller screens while maintaining the layout on desktop in all clients :).

I have a small question regarding this approach, since I don't seem to be able to apply my classes with my special styling to the elements in my .mjml file, so I have to do it manually in the compiled html, should I create a separate issue for this?

**Comment by ngarnier** [comment] 2017-03-03 11:17
You can use `mj-style` ([example](https://mjml.io/try-it-live/components/head-style)) to add specific styles in your MJML that will be applied to the HTML elements generated from the MJML, using CSS selectors. 

There's a pull-request moving forward about the ability to add a class that will be passed to the HTML from MJML: https://github.com/mjmlio/mjml/pull/532 (I think that's what you'd need).

**Comment by Reached** [comment] 2017-03-03 11:21
I think #532 is definitely what I need here :), I am already using mj-style, but the style should only apply to those two divs in my newsletter, seems like I have to wait for the mj-class to arrive.

Thanks for taking your time!

**Comment by ngarnier** [comment] 2017-03-03 12:42
No worries, glad you found a solution :).

I'm closing as I think your issue is solved!

**Closed by ngarnier** 2017-03-03 12:42 UTC
Labels: Discussion
