### ISSUE TITLE
MJML APP slowdown on Mac OS

### ISSUE THREAD

**Issue by gitluger** [mjmlio/mjml#2584] opened 2022-11-23 17:06 UTC
My MJML app does not work properly on my 2020 MacBook Pro. I'm currently running macOS Ventura and the app was also failing in BigSur. It opens, but it takes a while for code and images to download. There's also a delay when trying to enter or exit new files.
Does anyone know what version of MJML works best?

**Comment by iRyusa** [comment] 2022-11-23 17:15
Looks good on Monterey and Big Sur for me. Are you behind a proxy or slow Internet ?

**Comment by iRyusa** [comment] 2022-12-06 15:50
For people affected, please try to : 
- Remove every file related to MJML APP (config file, ...)
- Try to open Electron console with CMD+OPT+I and check if there's any error or infinite loop in the `console` tab.
- Can you try to record a video of this
- Can you open Activity Monitor to see if there's something CPU related or Memory related ?
- Can you check with older 2.X version to see if it does the same ?

**Comment by iRyusa** [comment] 2022-12-06 17:56
That’s something you can ignore. Nothing wrong in the console either. Trying everything to reproduce on my end but still no luck :/On 6 Dec 2022, at 18:49, Luis Rivas ***@***.***> wrote:﻿
Hi iRyusa, thanks for your help!
Here's what I'm seeing in the Electron console:
Tip:
Download the React DevTools for a better development experience: https://fb.me/react-devtools You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq
Errors:
React-Hot-Loader: misconfiguration detected, using production version in non-production environment.
React-Hot-Loader: Hot Module Replacement is not enabled.
AppContainer @ /Applications/MJML.app/Contents/Resources/app.asar/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js:1
How do I add the React DevTools to the MJML app? Do I need to?

**Comment by gitluger** [comment] 2022-12-06 18:04
CPU Usage:

When loading the master template (holds a lot of content modules) it uses 80%-100% to download. Once everything is downloaded, it goes from 0% - 40% as I scroll through the code.

Smaller files: 0% - 15%

Mid-size files: 0% - 30%

**Comment by gitluger** [comment] 2022-12-06 18:25
Here's a recording of the issue. Thanks again for your help, iRyusa![https://www.loom.com/share/297579d0847d4aa89fbc65e0f19b5c8d](url)

**Comment by iRyusa** [comment] 2022-12-06 19:41
I wonder if it’s related to the size of the email as it seem quite large ? Can you test with older 2.X version ?Thanks for the video On 6 Dec 2022, at 19:26, Luis Rivas ***@***.***> wrote:﻿
Here's a recording of the issue. Thanks again for your help, iRyusa

**Comment by gitluger** [comment] 2022-12-06 22:07
The large file would instantly download on my 2017 MacBook Pro in macOS Catalina. We have other teammates using that same file with no issues (PC and Mac).

The MJML app was slower on this 2020 MacBook Pro when it was running on macOS Monterey. We saw an improvement with code and images downloading when we upgraded to macOS Ventura, but the delay in the app opening and the delay in exiting files has been consistent.

I don't have admin permissions, but I will coordinate with Vysakh (IT) and try masOS Big Sur. Thanks, iRyusa!

**Comment by iRyusa** [comment] 2022-12-07 00:17
We did some long due dep update on MJML 3.x. Just for a sanity check can
you test with the older release (2.X)
https://github.com/mjmlio/mjml-app/releases/tag/v2.12.0 ? As Electron app
are not really tied to the OS version.

**Comment by emiliaclaire** [comment] 2022-12-07 09:44
Hi, I'm also experiencing the same issues and I opened Activity Monitor whilst opening the MJML app and this is what I saw:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/119937184/206144084-efb4a26e-8611-476e-8863-cf5197323ede.png">
So MJML application was find, but the helper app was taking a lot of CPU, but when I forced it to stop, the app stopped opening/loading. 

I also tried to download the older version but it was no better than the current MJML application that I have installed on my Mac.

**Comment by iRyusa** [comment] 2022-12-07 11:27
Thanks for those info, can you do a video too ?

**Comment by emiliaclaire** [comment] 2022-12-09 09:52
It's too big to upload here but I hope this works: https://we.tl/t-tG6gnfM6j6

This was actually the slowest I have ever experienced, usually once the main view has loaded, you click on an email template and it loads straight away, but then going 'Back' to the main view is very slow. However, this time, it was just slow for the whole process.

**Comment by iRyusa** [comment] 2022-12-09 10:01
Thanks for this, you're all working with the same big template it seems ? I'll try to load up many project as you to see if I can replicate. I don't really know what's going on it seems something just goes into an infinite loop and just eat the CPU really badly.

**Comment by emiliaclaire** [comment] 2022-12-13 09:13
They are the templates I used to work with that operated completely fine on macOS Catalina and it happens with every email I try and load. It's only since updating to Monterey, that I started having such an issue with MJML

**Comment by emiliaclaire** [comment] 2022-12-14 13:53
Hmm ok, let us know if you manage to make a breakthrough at all. We seem to be at a dead-end but need to use MJML to complete our daily tasks at work so any support or advice would be fantastic.

**Comment by iRyusa** [comment] 2022-12-14 13:59
Maybe use
https://marketplace.visualstudio.com/items?itemName=mjmlio.vscode-mjml
vscode plugin for now instead. Does it behave the same on a small template
like Racoon ?

**Comment by iRyusa** [comment] 2023-04-20 08:16
Closing this as we can't really reproduce here. I think it's something related to a "big" template with lot of inline that hang the worker. But without the template to reproduce it's hard to say.

**Closed by iRyusa** 2023-04-20 08:16 UTC
