### ISSUE TITLE
MJML W10 app | mj-social shows all icons when imported

### ISSUE THREAD

**Issue by ChrisPlaneta** [mjmlio/mjml#1318] opened 2018-08-17 07:27 UTC
I'm using W10 MJML App v 2.9.0. 

In my emails I use common header and footer and then import them to all emails (with `<mj-include path="./footer.mjml" />`). 

The problem is that when in the footer code I enter

```
<mj-social font-size="13px" icon-size="24px" mode="horizontal" padding-left="25" padding="10px 25px" align="right">
      	<mj-social-element name="facebook" href="https://www.facebook.com/GranitoveDrezy/" background-color="#4d4d4d"></mj-social-element>
</mj-social>
```

and then import that into an email, the mj-social-element gets disregarded and the element shows 3 icons (FB, TW & G+) with no urls.

**Reproduction Steps:**

1. Install MJML App v 2.9.0
2. Create a footer.mjml with the code above
3. include this footer into a different template like mail-1.mjml and see what shows

**Expected behavior:**

A facebook icon should appear linking to correct url

**Observed behavior:**

3 icons show up - FB, G+ and TW withh no URLs

**Screenshots and GIFs**

https://www.dropbox.com/s/fxd7t0keyewf0q4/1.jpg?dl=0
https://www.dropbox.com/s/3hx5y6j4sxsbybh/2.jpg?dl=0

**MJML version:**

4.0.3

**Email clients the bug is seen on:**

All

**Comment by kmcb777** [comment] 2018-08-17 14:50
Hi @ChrisPlaneta it's actually because you're using mjml3 in the main file (mj-container doesn't exist anymore in mjml4) so the whole file is getting migrated into mjml4, but since you're using the mjml4 syntax for mj-social, when this gets migrated it messes up the code.
You can remove the mj-container if you use mjml4 syntax (which you should)
I'll close this issue because it's much likely the cause :)

**Closed by kmcb777** 2018-08-17 14:50 UTC
