### ISSUE TITLE
EmptyMJMLError with included header

### ISSUE THREAD

**Issue by br4nnigan** [mjmlio/mjml#566] opened 2017-02-27 11:16 UTC
So i updated my globally installed mjml from 3.0.2 to 3.2.2 and now I try to compile something where i have use mj-include for a header part and get this error (it worked with the older version):

`Error: [MJMLError] EmptyMJMLError: No root "<mjml>" or "<mj-body>" found in the file, or "<mj-body>" is empty`

Is this working as intended?

**Comment by iRyusa** [comment] 2017-02-27 11:19
Hi @br4nnigan 

Can you provide some code about this ? Can you test it with latest MJML 3.3 beta ?

Thanks

**Comment by br4nnigan** [comment] 2017-02-27 11:24
Simplified code:

header.mjml:

    <mjml>
    <mj-body>


template.mjml:

    <mj-include path="./header" />
    </mj-body>
    </mjml>

`> mjml template.mjml` 

Gonna test with 3.3beta

**Comment by br4nnigan** [comment] 2017-02-27 12:41
Same result with 3.3.0-beta.6

**Comment by br4nnigan** [comment] 2017-02-27 13:00
Found the real culprit: the code i posted works, but if you add a mj-head to header.mjml it breaks (doesn't matter if mj-head has contents):

    <mjml>
    <mj-head>
    </mj-head>
    <mj-body>

**Comment by dalefish** [comment] 2017-02-27 13:18
Try going back to 3.1.1 (with inline removed). I heavily rely on includes
(nested includes too) with no issue in 3.1.1

Kind Regards,

:----------------------------:
Dale McConnell

**Comment by iRyusa** [comment] 2017-02-27 13:19
Can you provide the full template please?

If you have a mj-head inside a included template it will be added to the main template, cf #367

You have 2 choice to include a file:

Either it has directly content without surrounding `mjml/mj-body/mj-head` so the include is replace by content like:

```xml
<mj-text>Inline replace!</mj-text>
```
Or you can include a complete document so it will add the mj-head to the main document and the content inside `mj-container` will replace the `<mj-include>` like:

```xml
<!-- head.mjml -->
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-class name="header-button" font-size="32px" />
    </mj-attributes>
  </mj-head>
  <mj-body>
     <mj-container>
       <!-- Everything here will be included -->
       <mj-text align="center">
         <h1>Hello from header</h1>
       </mj-text>
       <mj-button mj-class="header-button">Click me</mj-button>
     </mj-container>
  </mj-body>
</mjml>
```

```xml
<mjml>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
           <mj-include path="./head.mjml" />
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>

**Comment by br4nnigan** [comment] 2017-02-27 13:35
@iRyusa the documentation says that wrapping tags (mjml > mj-body > mj-container) in included files is optional, but apparently i have been using this feature too wildly, for the current version that is. By the way if i remove the white space in the mj-head of my example the code does not break. So I can't imagine this is working as intended anyway.

My Idea was to create several mails with reusable header and footer.

**Comment by iRyusa** [comment] 2017-02-27 13:39
As I said from my earlier comment it's optional, just adding them allow you to use `mj-head` inside a partial. 
Documentation isn't really clear about this change introduce in 3.2, we'll have to update this.

**Comment by simon-am** [comment] 2017-03-23 10:20
@br4nnigan Did you work out a way of <mj-include> a <mj-head>. Or any way of having global styles across different templates? Really struggling with this. Including a full template with a <mj-head> seems to break the main template.

**Comment by iRyusa** [comment] 2017-03-23 10:24
@simon-am Can you share some code about this please ? 
https://github.com/mjmlio/mjml/issues/566#issuecomment-282717619 Should be relevant

**Comment by simon-am** [comment] 2017-03-23 10:38
@iRyusa thanks for getting back
So the below does not render the 'main body'.

`

<mjml>
  <mj-head>
    <mj-attributes>
      
      <mj-section background-color="#ffffff" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>Some global text</mj-text>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
`

`

<mjml>
  <mj-body>
    <mj-include path="head.mjml" />
    <mj-container>
      <mj-section>
        <mj-column>
          <mj-text>Main body</mj-text>
        </mj-column>
      </mj-section>
    </mj-container >
  </mj-body>
</mjml>
`

My original set up had the head.mjml opening the `mjml>mj-body` tags and a footer.mjml closing them. I think 3. onwards broke this? I think I understand that every mjml template should now have full opening and closing tags? This makes sense but struggling to make it work.

**Comment by iRyusa** [comment] 2017-03-23 10:40
Just put the `<mj-include path="head.mjml" />` inside `mj-container` and then it should work.
You can't have more than 1 elements inside `mj-body`

**Comment by simon-am** [comment] 2017-03-23 10:42
@iRyusa Brilliant - thanks so much.

**Closed** 2017-04-06 15:08 UTC

**Comment by mrksbnch** [comment] 2018-03-24 15:09
This does not work for me in the latest version (mjml-core: 4.0.1, mjml-cli: 4.0.3):

```
<!-- hero.mjml -->
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-class
        name="class-name"
        full-width="full-width"
        padding="0"
      />
    </mj-attributes>
  <mj-head>
  <mj-body>
    <mj-section mj-class="class-name">
      <mj-column>
        <mj-text padding="0 25px" color="#fff">
          Enroll a device for multi-factor authentication.
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

```
<!-- main.mjml -->
<mjml>
  <mj-head>
  </mj-head>
  <mj-body>
    <mj-include path="./partials/hero.mjml" />
  </mj-body>
</mjml>
```

It does just output an empty <div> in <body>.

**Comment by jdotjdot** [comment] 2018-06-09 23:52
I'm finding when I have a partial using `<mj-include>` that has an `<mj-head>` with content in it (generally `<mj-attributes>`, when I add the `<mj-include>` to my main document, it stops rendering everything below the include.  When I remove the `<mj-head>` component, the full document renders, including the partial.

In order to include an `<mj-head>`, the partial is built as a fully-built MJML document, like so:

```
<mjml>
  <mj-head>
    <mj-attributes>...</mj-attributes>
  </mj-head>
  <mj-body>
    ...
  </mj-body>
</mjml>
```

**Comment by kmcb777** [comment] 2018-06-11 11:28
Hi @jdotjdot, as iRyusa said please open a new issue and provide the exact mjml you're using, I was unable to reproduce this issue.
@mrksbnch I tested with your example above, and it turns out the <mj-head> is not properly closed in hero.mjml, the `/` is missing. If i add it then the include renders correctly.
