### ISSUE TITLE
Problem with mj-image inside mj-navbar

### ISSUE THREAD

**Issue by ColoO** [mjmlio/mjml#295] opened 2016-06-02 11:06 UTC
Error when i put
`<mj-image src=""></mj-image>`
you can see this syntax when you open : https://mjml.io/try-it-live

work with 
`<mj-image src="" />`

code example : 
```
<mjml>
  <mj-body>
    <mj-container>
      <mj-navbar background-color="#c5d64c" padding="0">
        <mj-column width="20%" padding="0">
          <mj-image width="68px" src="http://evol-mobilite.info/image-nl/26mai/evol-bar.png" />
        </mj-column>
        <mj-column width="80%" padding="0">
          <mj-inline-links hamburger="hamburger" base-url="#">
            <mj-link href="velos.html" color="#ffffff">Vélos</mj-link>
            <mj-link href="scooters.html" color="#ffffff">Scooters</mj-link>
            <mj-link href="tricycles.html" color="#ffffff">Tricycles</mj-link>
            <mj-link href="accessoires.html" color="#ffffff">Accessoires</mj-link>
            <mj-link href="pieces-detachees.html" color="#ffffff">Pièces détachées</mj-link>
          </mj-inline-links>
        </mj-column>
      </mj-navbar>
      <mj-section>
        <mj-column>
          <!-- generate my error -->
          <mj-image src=""></mj-image>
        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by ngarnier** [comment] 2016-06-02 15:07
Hey @ColoO, thanks for your feedback and opening this issue.

The issue is related to the image tags as you mix `<mj-image />` (in the navbar) with `<mj-image></mj-image>`. A quick way to fix this issue is to stick with the closing tag only or the self-closing tag only but not using both. Hope it helps! 

We're looking into the issue to see how we can fix this.

**Comment by iRyusa** [comment] 2016-06-27 14:25
Hi there! 

At this time, `cheerio` is far too complex to deal with this. However, a "linter" is on track to help dealing with self closing tag. Closing this one, but take a look at #198 for more details

**Closed** 2016-06-27 14:29 UTC
Labels: Render issue
