### ISSUE TITLE
Font sizes increase in Gmail on iPhone XS

### ISSUE THREAD

**Issue by karin-pacholkova** [mjmlio/mjml#2850] opened 2024-04-07 12:58 UTC
I have email with two paragraphs (1st paragraph: 1 column and 2nd paragraph: 2 columns) - both paragraphs have the texts with the same font-sizes. When I look into the email on my iPhone XC in Gmail app in portrait view - the font-sizes are fine (both the same). When I rotate the email to look at it in landscape view, then the text in 1 column paragraph is display bigger than the paragraph with 2 columns. The text in 2 columns paragraph is displayed correctly. 

When I look on the same email in Mail app on my iPhone XS, then both views looks good - with the good font-sizes.

Portrait view in Gmail app (this is the correct font-size):
![portrait](https://github.com/mjmlio/mjml/assets/92757755/43185ec2-16b5-4c04-bea4-7a0f16e1cb23)

Landscape view in Gmail app (1st column has bigger font than it should be):
![landscape](https://github.com/mjmlio/mjml/assets/92757755/5365a53f-b05f-49c5-8e4a-e19480cf781e)

I tried to google but didn't find anything what can help.

May I kindly ask you to advice me or navigate me where I can find the help?

Thank you very much in advance.

**Comment by iRyusa** [comment] 2024-04-07 13:03
I don't think the behavior come from MJML here.
Can you share some code to reproduce here : https://mjml.io/try-it-live

**Comment by karin-pacholkova** [comment] 2024-04-07 17:34
Hi iRyusa,
I put the code here - https://mjml.io/try-it-live/OyuYGshWDo
Thank you very much for your advice or help.
Karin

**Comment by karin-pacholkova** [comment] 2024-04-09 05:21
Hi Riusya, I tried to use also:
-webkit-text-size-adjust:none;
but no effect.
Do you have any clues, please?
Thank you very much in advance.

**Comment by iRyusa** [comment] 2024-04-09 07:58
I've reproduced but it seems to be something that come from gmail app and not MJML code as it ignores the inline style.

I don't think we'll be able to fix.

**Comment by karin-pacholkova** [comment] 2024-04-09 10:40
Many thanks for your efforts and the time you put into this!

**Comment by iRyusa** [comment] 2024-04-09 11:49
That's a really weird behavior from that email client :/ 

I'm closing the issue then 👌

**Closed by iRyusa** 2024-04-09 11:49 UTC
