### ISSUE TITLE
Render MJML Email as PDF

### ISSUE THREAD

**Issue by JakeKydd** [mjmlio/mjml#888] opened 2017-11-17 20:56 UTC
I am having trouble rendering some MJML Emails as PDFs (including transactional emails).
The issue is, whilst MJML emails act incredibly responsive in email clients on Desktop and Mobile phones, including the Browser, they don't scale exactly well when trying to print to PDF.

What looks on the screen as barely one page becomes 2 weirdly formatted pages in PDF.
Is there a way to avoid this and render the email as is to PDF?

**Comment by iRyusa** [comment] 2017-11-17 22:48
Hi @JakeKydd 

To be honest, I think rendering "fine" in majority of email clients in the market is already a big challenge for us. 

As PDF printing goes, it should do the same thing as you're printing the email and it's totally out of our control ( email clients alter the HTML when sending a printable version ).

We would accept any PR on this without any problem if the root cause isn't that big, but if it does alter the structure deeply to be printable compliant then I think it would add so much overhead for a small usecase.

Hope it does anwser your concern, I'm closing the issue

**Closed by iRyusa** 2017-11-17 22:48 UTC
