### ISSUE TITLE
Rendering issue when using $ within email

### ISSUE THREAD

**Issue by lRlevolution** [mjmlio/mjml#305] opened 2016-06-16 22:00 UTC
hi all! I had an issue where a dollar sign ($) was causing duplicate content - most likely somehow interfering with the jquery? using &#36; actually renders correctly. 

anyway - check out this video:

http://screencast.com/t/Zm9Dbk1w

**Comment by iRyusa** [comment] 2016-06-16 22:04
Mhh that's really weird.. i'll take a look tomorrow on this one you should use `&#36;` in the meantime

**Comment by lRlevolution** [comment] 2016-06-17 20:35
im also having another simiar issue. For some reason its stripping away a mj-text within mj-group. You can see the code below.

<mjml>
  <mj-body>
    <mj-container background-color="#F5F5F5" width="600px">

      
      <mj-section padding="20px 0 0" background-color="#F5F5F5">
        <mj-column background-color="#FFFFFF">
          <mj-text align="center" color="#666666" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="17" font-weight="bold" line-height="23px" padding-left="30" padding-right="30" padding-bottom="0" padding-top="30px">
              <p style="font-size:23px; margin:0 0 20px; font-weight: 500; letter-spacing:0.02em; line-height:27px;">HANDPICKED JUST FOR YOU</p>
          </mj-text>
        </mj-column>
      </mj-section>

      
      <mj-section padding="0 0 20px" background-color="#FFFFFF">
        <mj-group vertical-align="top">

          
          <mj-column>
            <mj-image href="%%RS_RPU1%%?utm_medium=email&utm_source=email&utm_campaign=newsletter&utm_content=dory060916&htm_tid=rec1" padding="2px 7px" src="https://d1s4gadwegul2m.cloudfront.net/production/spree/images/21687/main_image_retina/018834-00_b.jpg?1461973251" />
            <mj-text align="center" color="#666666" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="14px" font-weight="400" line-height="18px" padding="2px 10px">
              <span style="font-size:14px !important; line-height:18px; color:#666666 !important; font-weight:400;text-align:center;">%%RS_RN1%%</span>
            </mj-text>
          </mj-column>

          
          <mj-column>
            <mj-image href="%%RS_RPU2%%?utm_medium=email&utm_source=email&utm_campaign=newsletter&utm_content=dory060916&htm_tid=rec2" padding="2px 7px" src="https://d1s4gadwegul2m.cloudfront.net/production/spree/images/19367/main_image_retina/017413-00.jpg?1459372668" />
            <mj-text align="center" color="#666666" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="14px" font-weight="400" line-height="18px" padding="2px 10px">
              <span style="font-size:14px !important; line-height:18px; color:#666666 !important; font-weight:400;text-align:center;">%%RS_RN2%%</span>
            </mj-text>
          </mj-column>
        </mj-group>

        <mj-group vertical-align="top">
          
          <mj-column>
            <mj-image href="%%RS_RPU3%%?utm_medium=email&utm_source=email&utm_campaign=newsletter&utm_content=dory060916&htm_tid=rec3" padding="2px 7px" src="https://d1s4gadwegul2m.cloudfront.net/production/spree/images/21687/main_image_retina/018834-00_b.jpg?1461973251" />
            <mj-text align="center" color="#666666" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="14px" font-weight="400" line-height="18px" padding="2px 10px">
              <span style="font-size:14px !important; line-height:18px; color:#666666 !important; font-weight:400;text-align:center;">%%RS_RN3%%</span>
            </mj-text>
          </mj-column>

          
          <mj-column>
            <mj-image href="%%RS_RPU4%%?utm_medium=email&utm_source=email&utm_campaign=newsletter&utm_content=dory060916&htm_tid=rec4" padding="2px 7px" src="https://d1s4gadwegul2m.cloudfront.net/production/spree/images/19367/main_image_retina/017413-00.jpg?1459372668" />
            <mj-text align="center" color="#666666" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="14px" font-weight="400" line-height="18px" padding="2px 10px">
              <span style="font-size:14px !important; line-height:18px; color:#666666 !important; font-weight:400;text-align:center;">%%RS_RN4%%</span>
            </mj-text>
          </mj-column>
        </mj-group>

      </mj-section>


  
<mj-section padding="0px" background-color="#ffffff">
  <mj-column background-color="#FFFFFF">

  
    <mj-image align="center" padding="15px"  src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/share.jpg" href="https://www.#.com" alt="TODAY ONLY, Save An Additional 20%* on your first order too!"></mj-image>
    </mj-column>
  </mj-section>

    
 <mj-section padding="5px 0" background-color="#f6f6f6">
      <mj-column width="100%">

              
                  <mj-text align="center" color="#000000" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="13" padding-left="25" padding-right="25" padding-bottom="10" padding-top="20">
                        <table width="250px" cellspacing="0" cellpadding="0" border="0" align="center">
                              <tbody><tr>

                                <td width="37" align="center"><a target="_blank" href="http://facebook.com/shophollar"><img width="37" border="0" style="display:block;" alt="facebook.com/shophollar" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/facebook.png" mc:edit="fac"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a target="_blank" href="http://instagram.com/hollar"><img width="37" border="0" style="display:block;" alt="Instagram: @hollar" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/insta.png" mc:edit="twit"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37"><a target="_blank" href="http://pinterest.com/hollar"><img width="37" border="0" style="display:block;" alt="pinterest.com/hollar" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/pinterest.png" mc:edit="link"></a></td>

                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a target="_blank" href="http://twitter.com/hollar"><img width="37" border="0" style="display:block;" alt="Twitter: @hollar" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/twitter.png" mc:edit="pint"></a></td>
                                <td width="10">&nbsp;</td>

                                <td width="37" align="center"><a target="_blank" href="http://blog.hollar.com/2016/04/5-reasons-why-you-should-follow-hollarsnaps-on-snapchat/"><img width="37" border="0" style="display:block;" alt="Snapchat: @hollarsnaps" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/snapchat.png" mc:edit="pint"></a></td>

                                <td width="10">&nbsp;</td>

                                 <td width="37" align="center"><a target="_blank" href="http://blog.hollar.com/ "><img width="40" border="0" style="display:block;" alt="Hollar Blog" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/blog.png" mc:edit="pint"></a></td>

                              </tr>

                            </tbody></table>
                      </mj-text>

                      <mj-text align="center" color="#000000" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="13" padding-left="25" padding-right="25" padding-bottom="20" padding-top="15">
                          <table width="200" cellspacing="0" cellpadding="0" border="0" align="center">
                            <tbody><tr>
                                <td width="100" align="center"><a style="border: none; outline: none; text-decoration: none;" href="https://itunes.apple.com/us/app/hollar-so.-much.-good.-stuff/id1076108089?mt=8"><img alt="" src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/app_ios.png"></a></td>
                                <td width="100" align="center"><a style="border: none; outline: none; text-decoration: none;" href="https://play.google.com/store/apps/details?id=com.hollar.android"><img src="http://hosting-source.bm23.com/35647/public/Offer_Product-Rec/Product_Recs/app_droid.png"></a></td>
                                    </tr>
                              </tbody></table>
                         </mj-text>

             
              <mj-text align="center" link-color="#8b908b" padding-bottom="0" padding-top="10" padding-left="0" padding-right="0" font-size="11px" font-weight="normal" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif">
                <a href="%%!manage_url%%" style="text-decoration: none; color: #8b908b;">EMAIL PREFERENCES&#xA0;&#xA0;|</a><a href="http://www.hollar.com/contact" style="text-decoration: none; color: #8b908b;">&#xA0;&#xA0;CONTACT US&#xA0;&#xA0;|</a><a href="https://hollar.com/privacy" style="text-decoration: none; color: #8b908b;">&#xA0;&#xA0;PRIVACY POLICY&#xA0;&#xA0;|</a><a href="%%!unsubscribe_url%%" style="text-decoration: none; color: #8b908b;">&#xA0;&#xA0;UNSUBSCRIBE</a>
              </mj-text>
 
              <mj-text align="center" color="#808080" font-family="'Helvetica Neue', Helvetica, Arial, sans-serif" font-size="11" line-height="22px" padding-left="45" padding-right="45" padding-bottom="10" padding-top="0">
                    <p style="font-size:11px; line-height:22px; color:#8b908b;">Free shipping offer is automatically applied at checkout on all first-time orders over &#36;10. For subsequent orders over &#36;25 pre-tax, free shipping will be applied at checkout. Offers valid on U.S. orders only.</p>
                    
                    <p style="font-size:11px; line-height:20px; color: #8b908b !important;"><strong>Hollar Support Team</strong>
                    <br> Monday - Friday | 7:00am - 4:00pm PST<br>
                    <a href="tel:888-682-5119" style="color: #8b908b !important; text-decoration:none !important;">888-682-5119</a>
                    <br>
                      <a href="mailto:support@hollar.com?Subject=Hollar%20Support" style="color: #8b908b !important; text-decoration:none !important;" target="_blank">support@hollar.com</a></p>

                      <p style="font-size:11px; line-height:22px; color:#8b908b;">If you'd like to unsubscribe, click <a href="%%!unsubscribe_url%%" style="color:#8b908b; text-decoration:none !important;">here</a><br /> Copyright &copy; 2016 %%!account_organization%%. All rights reserved. <br> %%!account_address1%% %%!account_address2%%,
          %%!account_city%%, %%!account_state%% %%!account_zip%%</p>
      </mj-text>

    </mj-column>
  </mj-section>

</mj-body>

**Comment by iRyusa** [comment] 2016-06-27 14:03
I'm not able to reproduce with a simple template, can you try to isolate the section with this issue in the try it live?

**Comment by iRyusa** [comment] 2016-07-07 11:35
I'm closing this one until we found an easier way to reproduce, if you're experiencing it again, replace special chars with HTML equivalent http://www.ascii.cl/htmlcodes.htm

**Closed by iRyusa** 2016-07-07 11:35 UTC
Labels: Cannot reproduce

**Comment by jaypeedevlin** [comment] 2016-07-11 19:32
I am having the same issue (dollar sign causes duplicate content) FWIW.

**Comment by iRyusa** [comment] 2016-07-11 19:57
Is this on a "simple" mjml ? Would love to debug that but no way to reproduce it :/

**Comment by jaypeedevlin** [comment] 2016-07-11 20:30
Unfortunately not simple at all - even more complex than the OP I would say.

Joshua Devlin
M: +1 832 266 2564
E: josh@devlinsonline.com.au
